<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tracbel.Crm.Dominio\Tracbel.Crm.Dominio.csproj" />
    <ProjectReference Include="..\..\src\Tracbel.Crm.Aplicacao\Tracbel.Crm.Aplicacao.csproj" />
    <ProjectReference Include="..\..\src\Tracbel.Crm.Infraestrutura\Tracbel.Crm.Infraestrutura.csproj" />
    <ProjectReference Include="..\..\src\Tracbel.Crm.Integracao\Tracbel.Crm.Integracao.csproj" />
  </ItemGroup>

</Project>
