/* ==============================================================
   Objeto ..........: dbo.fIV_GetPessoaFones
   Tipo ............: SQL_SCALAR_FUNCTION
   Criado em .......: 2013-11-01 10:16:41
   Modificado em ...: 2022-03-06 17:11:25
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE FUNCTION [dbo].[fIV_GetPessoaFones] (@SeqPessoa Integer)  RETURNS VARCHAR(200)  AS  BEGIN    Declare @vsRetorno varchar(200)    Declare @vsHifen varchar (3)    Declare @vsFoneDDD1 varchar (5)    Declare @vsFoneDDD2 varchar (5)    Declare @vsFoneDDD3 varchar (5)    Declare @vnFoneNRO1 numeric   Declare @vnFoneNRO2 numeric    Declare @vnFoneNRO3 numeric    Declare @vsFoneCMPL1 varchar (15)    Declare @vsFoneCMPL2 varchar (15)    Declare @vsFoneCMPL3 varchar (15)    DECLARE c01 CURSOR FOR    SELECT FONEDDD1,FONEDDD2,FONEDDD3,   FONENRO1, FONENRO2, FONENRO3,   FONECMPL1,FONECMPL2,FONECMPL3    FROM GE_PESSOA   WHERE SEQPESSOA = @SeqPessoa   OPEN c01      FETCH NEXT FROM c01 INTO    @vsFoneDDD1 , @vsFoneDDD2 , @vsFoneDDD3 ,   @vnFoneNRO1 , @vnFoneNRO2 , @vnFoneNRO3 ,    @vsFoneCMPL1 , @vsFoneCMPL2 , @vsFoneCMPL3    Set @vsRetorno = ''   If @@FETCH_STATUS = 0   BEGIN   If @vnFoneNRO1 > 9999999    Begin    If len (@vsFoneDDD1) >= 2    Set @vsRetorno = @vsRetorno ++ '(' ++ @vsFoneDDD1 ++ ') '    Set @vsRetorno = @vsRetorno ++ CONVERT(VARCHAR,@vnFoneNRO1)   If len (@vsFoneCMPL1) > 2    Set @vsRetorno = @vsRetorno ++ ' ' ++ @vsFoneCMPL1 ++ ') '    End   If @vnFoneNRO2 > 9999999    Begin    If len (@vsFoneDDD2) >= 2    Set @vsRetorno = @vsRetorno ++ ' (' ++ @vsFoneDDD2 ++ ') '    Set @vsRetorno = @vsRetorno ++ CONVERT(VARCHAR,@vnFoneNRO2)   If len (@vsFoneCMPL2) > 2    Set @vsRetorno = @vsRetorno ++ ' ' ++ @vsFoneCMPL2 ++ ') '    End   If @vnFoneNRO3 > 9999999    Begin    If len (@vsFoneDDD3) >= 2    Set @vsRetorno = @vsRetorno ++ ' (' ++ @vsFoneDDD3 ++ ') '    Set @vsRetorno = @vsRetorno ++ CONVERT(VARCHAR,@vnFoneNRO3)   If len (@vsFoneCMPL3) > 2    Set @vsRetorno = @vsRetorno ++ ' ' ++ @vsFoneCMPL3 ++ ') '    End   END    CLOSE c01   DEALLOCATE c01    RETURN @vsRetorno  END  