/* ==============================================================
   Objeto ..........: dbo.vrtc_f_aliastablelogget
   Tipo ............: SQL_SCALAR_FUNCTION
   Criado em .......: 2026-04-20 17:52:51
   Modificado em ...: 2026-04-20 17:52:51
   Linhas ..........: 71
   Escreve em tabela: nao
   Tabelas referidas: (nenhuma)
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE FUNCTION dbo.vrtc_f_aliastablelogget
(
    @p_tabela VARCHAR(200)
)
RETURNS VARCHAR(100)
AS
BEGIN
    DECLARE
          @v_tab   VARCHAR(200)
        , @v_alias VARCHAR(100);

    SET @v_tab = UPPER(@p_tabela);

    IF @v_tab = 'GE_PESSOA'
        SET @v_alias = 'GE_LOG_PESSOA';
    ELSE IF @v_tab = 'IV_AGENDA'
        SET @v_alias = 'IV_AGENDALOG';
    ELSE IF @v_tab = 'IV_HISTORICO'
        SET @v_alias = 'GE_LOG_HISTORICO';
    ELSE IF @v_tab = 'GE_CONTATO'
        SET @v_alias = 'GE_LOG_CONTATO';
    ELSE IF @v_tab = 'IV_PROCESSO'
        SET @v_alias = 'GE_LOG_PROCESSO';
    ELSE IF @v_tab = 'IV_CARTCRED'
        SET @v_alias = 'GE_LOG_CARTCRED';
    ELSE IF @v_tab IN (
          'DMN_DOCTP','GE_APLICACAO','GE_APPMODULO','GE_ATRIBUTOFIXO'
        , 'GE_CAMPOEXIG','GE_CAMPOPERM','GE_DIANAOUTIL','GE_EMPRESA'
        , 'GE_FERIADO','GE_MEMBRO','GE_MOD','GE_MODULO','GE_MODULOPERM'
        , 'GE_OBJDINAMICO','GE_OBJDINAPLIC','GE_PARAMETROGLOBAL','GE_PARAMLISTA'
        , 'GE_PERMISSAO','GE_POLSEG','GE_POLSEGACES','GE_POLSEGCTRL'
        , 'GE_POLSEGITEM','GE_POLSEGITLST','GE_POLSEGPARAMS','GE_POLSEGPERM'
        , 'GE_REGIAO','GE_RELPASTACONS','GE_RELTEMPLATE','GE_ROTA','GE_SISTEMA'
        , 'GE_URACENARIO','GE_USRACSP','GE_USRPARAM','GE_USUARIO'
        , 'GE_USUARIOCMPL','GE_USUARIOLINK','GE_USUARIOPERM','GEP_PARENVIA'
        , 'GEP_PARRECEBE','GEP_PARRECENVIA','GEP_PROCESSO','IV_ACAO'
        , 'IV_ACAOATENDENTE','IV_ACAOAUTO','IV_ACAOAUTOCTRL','IV_ACAOCMPL'
        , 'IV_ACAOCTRL','IV_ACAOMON','IV_ACAOREM','IV_ACAOTODO'
        , 'IV_ACAOURACENARIO','IV_AGDPLANTRG','IV_ATENDENTE','IV_BASEINFORMACAO'
        , 'IV_CARTCONTRATANTE','IV_CARTMARCA','IV_CARTPRODUTO','IV_CBRCRITERIO'
        , 'IV_CBRCRITERIODEF','IV_CBRCRITERIOMSG','IV_CLASSERES'
        , 'IV_CODPRCEMPR','IV_CODPROCCOMENT','IV_CODPROCESSO'
        , 'IV_CONHECFONEMA','IV_CONHECIMENTO','IV_DEPARTAMENTO','IV_DOCTOAPL'
        , 'IV_DOCTOAPLUSO','IV_DOCTOTIPO','IV_VENDEDOR','IV_VENDEDOREMPR'
        , 'IV_ESTRPRODUTO','IV_EVENTO','IV_EVENTOACAO','IV_FORMULARIO'
        , 'IV_GLOBALPAR','IV_GLOBALPARCTRL','IV_GLOBALPARLISTA','IV_LISTSQL'
        , 'IV_MOTIVO','IV_OBJVENDA','IV_OCRMDEST','IV_OPBLOQ','IV_OPERADOR'
        , 'IV_PAREVTEXTRES','IV_PCTE','IV_PCTEATRFX','IV_PROCACAO'
        , 'IV_PROCFASE','IV_PROCPERSP','IV_PROCST','IV_PROCTPREL','IV_PROCVINC'
        , 'IV_PRODUTO','IV_PROPRIEDADE','IV_PROPRILISTA','IV_QUESTAO'
        , 'IV_QUESTAOLISTA','IV_RECURSO','IV_RECUSO','IV_RESCLASSE'
        , 'IV_RESEVTOUT','IV_RESJOB','IV_RESMSGPAPEL','IV_RESPARAM'
        , 'IV_RESULTADO','IV_RESULTADOCMPL','IV_RESULTADOINSTR','IV_RESULTADOREQ'
        , 'IV_RESULTADOWEB','IV_RESVINC','IV_RETPROCREGRA','IV_SEGPERFIL'
        , 'IV_TXTPADCONTA','IV_TXTPADRAO','IV_TXTPADRAOUSO','IVC_EQUIPE'
        , 'IVC_EQUIPEUSR','IVC_RAMAL','IVS_CARTCATEGORIA','IVS_CARTCID'
        , 'IVS_CARTDEPTO','IVS_CARTEIRA','IVS_CATEGORIA','IVS_DEPTO'
        , 'IVS_DEPTOEMPR','IVS_DEPTOPOT','IVS_DEPTORES','IVS_NEGCATEGORIA'
        , 'IVS_NEGOCIO','IVS_REGIONAL','IVS_SEGM','IVS_USRMETA'
        , 'CRMSRVPROCSETUP','DMNPARAM','IVPARAMCRM','IVPARAMFICNEG'
        , 'IVPARAMHIG','IVPARAMINT','IVPARJUPITER','IVPARSMSEMP'
        , 'IVPARSMTPEMP','IVS1PAR01','PRJPARAM','PROCONPAR01'
        , 'RUNIMPORTIMP','SDIPAR01','SDIPAR01S'
        , 'IVP_CATEGORIA','IVP_FAMILIA','IVP_GRUPO','IVP_MARCA','IVP_PRODUTO'
    )
        SET @v_alias = 'GE_LOG_CONFIG';
    ELSE
        SET @v_alias = 'GE_LOG_TRANS';

    RETURN @v_alias;
END