import { chromium } from 'playwright';
const nav = await chromium.launch();
const pg = await nav.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
const erros = [];
pg.on('pageerror', e => erros.push(e.message));
pg.on('console', m => { if (m.type()==='error') erros.push('console: '+m.text()); });
await pg.goto('http://localhost:5173/#/', { waitUntil: 'networkidle' });
await pg.waitForTimeout(2200);
const alt = await pg.evaluate(() => document.body.scrollHeight);
console.log('altura:', alt, '| referencia (css px):', 1981);
await pg.screenshot({ path: 'c:/tmp/v360-novo.png', fullPage: true });
console.log('erros:', erros.length ? erros.slice(0,3) : 'nenhum');
await nav.close();
