/* ==============================================================
   Objeto ..........: dbo.bi_cobertura
   Tipo ............: VIEW
   Criado em .......: 2019-10-28 13:24:38
   Modificado em ...: 2019-10-28 13:24:38
   Linhas ..........: 33
   Escreve em tabela: nao
   Tabelas referidas: IV_CLASSERES, IV_HISTORICO, IV_PROCDADO, IV_RESCLASSE, IV_RESULTADO, IVS_PES
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW bi_cobertura as
SELECT HIST.SEQPESSOA
     , HIST.PROCESSO
     , PDD.ProcessoDNA
     , PDD.ProcessoPai
     , CRES.CLASSE
     , RES.RESULTADO 			AS COD_RESULTADO
     , RES.DESCRICAO 			AS RESULTADO
     , HIST.RESULTADOCMPL
     , HIST.DTAREALIZACAO 		AS DTAREALIZACAO
     , HIST.VENDEDOR
     , PDD.CAMPANHA
FROM IV_HISTORICO HIST
  JOIN IVS_PES PES ON PES.SEQPESSOA = HIST.SEQPESSOA AND PES.SEQDEPTO = 2
  JOIN IV_PROCDADO PDD ON PDD.PROCESSO = HIST.PROCESSO
  JOIN IV_RESULTADO RES ON RES.RESULTADO = HIST.RESULTADO
  JOIN IV_RESCLASSE RCL ON RCL.RESULTADO = RES.RESULTADO
  JOIN IV_CLASSERES CRES ON CRES.SEQCLASSERES = RCL.SEQCLASSERES
	AND CRES.CLASSE IN ( '1-Cobertura' )
WHERE YEAR(HIST.DTAREALIZACAO) >= YEAR('2015')
  AND HIST.SEQHISTORICO = 
  
  ( SELECT MAX(H.SEQHISTORICO)
	FROM 			IV_HISTORICO 	H
		JOIN  		IV_RESCLASSE 	RCL 	ON RCL.RESULTADO 		= H.RESULTADO
		JOIN 		IV_CLASSERES 	CRES 	ON CRES.SEQCLASSERES 	= RCL.SEQCLASSERES AND CRES.CLASSE IN ( '1-Cobertura' ) 
		-- AJUSTE REALIZADO NO DIA 28/10/2019 PARA QUE A COSULTA TRAGA APENAS O ULTIMO RESULTADO COBERTURA BASEADO NO DNA, DIFERENTE DO
		-- FAZIA QUE ERA O ULTIMO RESULTADO BASEADO NO NUMERO DE PROCESSO, DE FORMA QUE ESTAVA DUPLICANDO A FAZE COBERTURA.
		LEFT JOIN	IV_PROCDADO		dna		ON H.PROCESSO			= DNA.Processo -- TABELA ADICIONADA NO DIA 28/10/2019
			WHERE 
				H.PROCESSO = HIST.PROCESSO 		-- FILTRO ORIGINAL DESENVOLVIDO PELA VORTICE
				--DNA.ProcessoDNA=PDD.ProcessoDNA   	-- NOVO FILTRO DESENVOLVIDO NO DIA 28/10/2019.
				)