/* ==============================================================
   Objeto ..........: dbo.BI_CARTEIRA_VN
   Tipo ............: VIEW
   Criado em .......: 2015-08-07 10:52:39
   Modificado em ...: 2026-02-06 11:12:01
   Linhas ..........: 80
   Escreve em tabela: nao
   Tabelas referidas: GE_EMPRESA, GE_PESSOA, GE_USUARIO, IV_HISTORICO, IVS_CARTEIRA, IVS_DEPTO, IVS_PES
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

-- dbo.BI_CARTEIRA_VN source

CREATE VIEW [dbo].[BI_CARTEIRA_VN] AS
SELECT PES.SEQPESSOA ,
   CRT.NROEMPRESA AS NROEMPRESA,
   EMP.NOMEREDUZIDO AS CART_EMPRESA,
   CASE WHEN PES.POTENCIAL >= 'A' THEN PES.POTENCIAL
    ELSE NULL END AS CART_POTENCIAL,
   CRT.CARTEIRA ,
   PES.SEQDEPTO,
   DPT.DEPTO AS DEPTOCARTEIRA,
   CARTEIRA + '-' + USR.CODUSUARIO   AS CART_CEN,
   HRK.DTAREALIZACAO AS CART_DATA_ULT_CONTATO, --PES.DTAULTCTTO
   PES.DTAULTCTTOEXT AS CART_DATA_ULT_VISITA,
   CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END
         AS CART_CICLO       ,
   ( GETDATE() - HRK.DTAREALIZACAO ) AS CART_DIAS_ULT_VISITA, --PES.DTAULTCTTO
   CASE WHEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE() - HRK.DTAREALIZACAO), 0) <= CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END THEN  1
         ELSE 0
     END AS CART_IND_VISITADO  , --PES.DTAULTCTTO
   CASE WHEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE() -  HRK.DTAREALIZACAO), 0) <= CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END THEN  'Visitado'
         ELSE 'Não Visitado' --PES.DTAULTCTTO
     END AS CART_Acompanhamento,
	 (SELECT P3.CARTEIRA FROM GE_PESSOA P1, IVS_PES P2, IVS_CARTEIRA P3
	    WHERE P1.SEQPESSOA = PES.SEQPESSOA
		  AND P2.SEQPESSOA = P1.SEQPESSOAPRC AND P2.SEQDEPTO in (2)
		  AND P3.SEQCARTEIRA = P2.SEQCARTEIRA) AS CART_PRINCIPAL,
	 (SELECT P2.NOMERAZAO FROM GE_PESSOA P1, GE_PESSOA P2 
	    WHERE P1.SEQPESSOA = PES.SeqPessoa
		  AND P2.SEQPESSOA = P1.SEQPESSOAPRC) AS CONGLOMERADO,
	 HRK.FormaPrimCont AS Forma_contato,
	 HRK.PROCESSO,
	 (SELECT NOME FROM GE_USUARIO WHERE SEQUSUARIO = CRT.SeqUsrResp)
	 AS NOME_VENDEDOR,
	 CASE WHEN ISNULL ( HRK.DTAREALIZACAO, '01/01/1990') = '01/01/1990' 
	           THEN 'Sem contato'
	      WHEN (GETDATE() - HRK.DTAREALIZACAO) >= 365 
		       THEN 'Mais de 1 ano'
	      WHEN (GETDATE() - HRK.DTAREALIZACAO) >= 180 
		       THEN 'Mais de 6 meses'
	      WHEN (GETDATE() - HRK.DTAREALIZACAO) < 180 
		       THEN 'Menos de 6 meses'
	      END AS CART_TEMPO_CONTATO, --PES.DTAULTCTTO
     (SELECT SEQPESSOAPRC FROM GE_PESSOA WHERE SEQPESSOA = PES.SEQPESSOA) AS SEQPESSOACONGLO

FROM IVS_PES PES
  LEFT JOIN IVS_DEPTO DPT ON DPT.SEQDEPTO = PES.SEQDEPTO
  LEFT JOIN IVS_CARTEIRA CRT
       JOIN GE_EMPRESA EMP ON EMP.NROEMPRESA = CRT.NROEMPRESA
    ON CRT.SEQCARTEIRA = PES.SEQCARTEIRA
  LEFT JOIN (SELECT HIS.SEQPESSOA, HIS.FormaPrimCont,HIS.PROCESSO,HIS.DTAREALIZACAO, 
	    ROW_NUMBER () OVER ( PARTITION BY HIS.SEQPESSOA ORDER BY HIS.DTAREALIZACAO DESC ) AS RANKHIS
        FROM IV_HISTORICO HIS
        WHERE HIS.RESULTADO IN ( 250, 252, 254, 255, 257, 258, 260, 263, 265, 267, 299, 300, 302, 304, 305, 
                                306, 307, 308, 570, 1286, 3223, 3225, 3227, 3226, 3231, 3232, 3663, 3234, 3235, 3236, 3639, 3640, 2605, 1929, 2612, 2622, 1175, 2547, 2553, 2554, 2555, 2548, 2549, 2550, 2563, 2564, 2565, 2566, 2568, 3572, 3573, 3575, 3576)) HRK ON HRK.SeqPessoa = PES.SeqPessoa
								                              AND HRK.RANKHIS = 1
  LEFT JOIN GE_USUARIO USR ON USR.SEQUSUARIO = CRT.SEQUSRRESP
WHERE PES.SEQDEPTO IN (2);
