/* ==============================================================
   Objeto ..........: dbo.BI_CARTEIRA_MANITOU
   Tipo ............: VIEW
   Criado em .......: 2018-03-23 10:26:59
   Modificado em ...: 2018-03-23 10:26:59
   Linhas ..........: 48
   Escreve em tabela: nao
   Tabelas referidas: GE_EMPRESA, GE_USUARIO, IVS_CARTEIRA, IVS_DEPTO, IVS_PES
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW [dbo].[BI_CARTEIRA_MANITOU] AS
SELECT PES.SEQPESSOA ,
   CRT.NROEMPRESA AS NROEMPRESA,
   EMP.NOMEREDUZIDO AS CART_EMPRESA,
   CASE WHEN PES.POTENCIAL >= 'A' THEN PES.POTENCIAL
    ELSE NULL END AS CART_POTENCIAL,
   CRT.CARTEIRA ,
   PES.SEQDEPTO,
   CARTEIRA + '-' + USR.CODUSUARIO   AS CART_CEN,
   PES.DTAULTCTTO AS CART_DATA_ULT_CONTATO,
   PES.DTAULTCTTOEXT AS CART_DATA_ULT_VISITA,
   CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END
         AS CART_CICLO       ,
   ( GETDATE() - PES.DTAULTCTTOEXT ) AS CART_DIAS_ULT_VISITA, 
   CASE WHEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE() - PES.DTAULTCTTOEXT), 0) <= CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END THEN  1
         ELSE 0
     END AS CART_IND_VISITADO  ,
   CASE WHEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE() -  PES.DTAULTCTTOEXT), 0) <= CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END THEN  'Visitado'
         ELSE 'Não Visitado'
     END AS CART_Acompanhamento
FROM IVS_PES PES
  JOIN IVS_DEPTO DPT ON DPT.SEQDEPTO = PES.SEQDEPTO
  JOIN IVS_CARTEIRA CRT
       JOIN GE_EMPRESA EMP ON EMP.NROEMPRESA = CRT.NROEMPRESA
    ON CRT.SEQCARTEIRA = PES.SEQCARTEIRA
  LEFT JOIN GE_USUARIO USR ON USR.SEQUSUARIO = CRT.SEQUSRRESP
WHERE PES.SEQDEPTO = 9