/* ==============================================================
   Objeto ..........: dbo.BI_CARTEIRA_PUK
   Tipo ............: VIEW
   Criado em .......: 2026-02-05 14:45:28
   Modificado em ...: 2026-03-03 16:24:27
   Linhas ..........: 88
   Escreve em tabela: nao
   Tabelas referidas: GE_EMPRESA, GE_PESSOA, GE_USUARIO, IV_HISTORICO, IVS_CARTEIRA, IVS_DEPTO, IVS_PES
   Outras refs .....: tba_usuarios
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

-- dbo.BI_CARTEIRA_PUK fonte

CREATE VIEW [dbo].[BI_CARTEIRA_PUK] AS
SELECT PES.SEQPESSOA ,
   CRT.NROEMPRESA AS NROEMPRESA,
   EMP.NOMEREDUZIDO AS CART_EMPRESA,
    CASE 
  WHEN CAST(PES.POTENCIAL AS VARCHAR(1)) IN ('A','B','C','D')
    THEN CAST(PES.POTENCIAL AS VARCHAR(1))
  ELSE NULL
END AS CART_POTENCIAL,
   CRT.CARTEIRA ,
   PES.SEQDEPTO,
   DPT.DEPTO AS DEPTOCARTEIRA,
   CONCAT(CRT.CARTEIRA, '-', USR.CODUSUARIO) AS CART_CEN,
   HRK.DTAREALIZACAO AS CART_DATA_ULT_CONTATO, --PES.DTAULTCTTO
   PES.DTAULTCTTOEXT AS CART_DATA_ULT_VISITA,
   PES.POTENCIAL AS POTENCIAL_TESTE,
   CASE 
  WHEN PES.POTENCIAL IS NULL THEN 30
  WHEN PES.POTENCIAL = 'A' THEN 30
  WHEN PES.POTENCIAL = 'B' THEN 60
  WHEN PES.POTENCIAL = 'C' THEN 90
  WHEN PES.POTENCIAL = 'D' THEN 120
  --WHEN PES.POTENCIAL = 'A' THEN DPT.CICLOAEXT
  --WHEN PES.POTENCIAL = 'B' THEN DPT.CICLOBEXT
  --WHEN PES.POTENCIAL = 'C' THEN DPT.CICLOCEXT
  --WHEN PES.POTENCIAL = 'D' THEN DPT.CICLODEXT
  ELSE 360
END AS CART_CICLO,
   ( GETDATE() - HRK.DTAREALIZACAO ) AS CART_DIAS_ULT_VISITA, --PES.DTAULTCTTO
   CASE WHEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE() - HRK.DTAREALIZACAO), 0) <= CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END THEN  1
         ELSE 0
     END AS CART_IND_VISITADO  , --PES.DTAULTCTTO
   CASE WHEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE() -  HRK.DTAREALIZACAO), 0) <= CASE PES.POTENCIAL
     WHEN 'A' THEN DPT.CICLOAEXT
     WHEN 'B' THEN DPT.CICLOBEXT
     WHEN 'C' THEN DPT.CICLOCEXT
     WHEN 'D' THEN DPT.CICLODEXT
     WHEN NULL THEN 30
       ELSE   360
         END THEN  'Visitado'
         ELSE 'Não Visitado' --PES.DTAULTCTTO
     END AS CART_Acompanhamento,
	 (SELECT P3.CARTEIRA FROM GE_PESSOA P1, IVS_PES P2, IVS_CARTEIRA P3
	    WHERE P1.SEQPESSOA = PES.SEQPESSOA
		  AND P2.SEQPESSOA = P1.SEQPESSOAPRC AND P2.SEQDEPTO in (28)
		  AND P3.SEQCARTEIRA = P2.SEQCARTEIRA) AS CART_PRINCIPAL,
	 (SELECT P2.NOMERAZAO FROM GE_PESSOA P1, GE_PESSOA P2 
	    WHERE P1.SEQPESSOA = PES.SeqPessoa
		  AND P2.SEQPESSOA = P1.SEQPESSOAPRC) AS CONGLOMERADO,
	 HRK.FormaPrimCont AS Forma_contato,
	 HRK.PROCESSO,
	 (SELECT NOME FROM GE_USUARIO WHERE SEQUSUARIO = CRT.SeqUsrResp)
	 AS NOME_VENDEDOR,
	 CASE WHEN HRK.DTAREALIZACAO IS NULL
	           THEN 'Sem contato'
	      WHEN (GETDATE() - HRK.DTAREALIZACAO) >= 365 
		       THEN 'Mais de 1 ano'
	      WHEN (GETDATE() - HRK.DTAREALIZACAO) >= 180 
		       THEN 'Mais de 6 meses'
	      WHEN (GETDATE() - HRK.DTAREALIZACAO) < 180 
		       THEN 'Menos de 6 meses'
	      END AS CART_TEMPO_CONTATO, --PES.DTAULTCTTO
     (SELECT SEQPESSOAPRC FROM GE_PESSOA WHERE SEQPESSOA = PES.SEQPESSOA) AS SEQPESSOACONGLO

FROM IVS_PES PES
  LEFT JOIN IVS_DEPTO DPT ON DPT.SEQDEPTO = PES.SEQDEPTO
  LEFT JOIN IVS_CARTEIRA CRT
       JOIN GE_EMPRESA EMP ON EMP.NROEMPRESA = CRT.NROEMPRESA
    ON CRT.SEQCARTEIRA = PES.SEQCARTEIRA
  LEFT JOIN (SELECT HIS.SEQPESSOA, HIS.FormaPrimCont,HIS.PROCESSO,HIS.DTAREALIZACAO, 
	    ROW_NUMBER () OVER ( PARTITION BY HIS.SEQPESSOA ORDER BY HIS.DTAREALIZACAO DESC ) AS RANKHIS
        FROM IV_HISTORICO HIS
        JOIN tba_usuarios U
            ON U.CodUsuario = HIS.CODUSUARIO
            AND U.DEPARTAMENTO = 'DSI-PUK'
        WHERE HIS.RESULTADO IN ( 3708, 3710, 3711, 3780, 3712, 3777, 1175, 2622, 2612, 1929, 3231, 3790, 3234, 3235, 3236, 3237)) HRK ON HRK.SeqPessoa = PES.SeqPessoa
								                              AND HRK.RANKHIS = 1
  LEFT JOIN GE_USUARIO USR ON USR.SEQUSUARIO = CRT.SEQUSRRESP
WHERE PES.SEQDEPTO IN (28);