/* ==============================================================
   Objeto ..........: dbo.BI_DTAPROVCREDITO
   Tipo ............: VIEW
   Criado em .......: 2023-06-09 11:05:03
   Modificado em ...: 2023-10-16 16:06:47
   Linhas ..........: 38
   Escreve em tabela: nao
   Tabelas referidas: IV_HISTORICO, IV_PROCESSO
   Outras refs .....: IV_Q$GESTAO_CREDITO, IV_Q$GESTAO_CREDITO_IMP
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW [dbo].[BI_DTAPROVCREDITO] AS
SELECT PROCESSO, 
       DTVENDA_AUTORIZADA, 
	   DTVENDA_PAGTO, 
	   DTAPROVACAO_CREDITOTRT, 
	   DTAPROVACAO_CREDITOIMP, 
	   DTAPROVACAO_CREDITOAMS
FROM (
SELECT PRC.PROCESSO,
       (SELECT MIN(DTAREALIZACAO) FROM IV_HISTORICO WHERE PROCESSO = PRC.PROCESSO AND RESULTADO = 2145)
	   AS DTVENDA_AUTORIZADA,
       (SELECT MAX(DTAREALIZACAO) FROM IV_HISTORICO WHERE PROCESSO = PRC.PROCESSO AND RESULTADO IN ( 2182, 2181, 2183, 2184 ) )
	   AS DTVENDA_PAGTO,
	   ( SELECT MIN(
		   CASE WHEN INSTITUICAO_FIINSTIT = ANALISE_2 THEN DATA_RESPOSTA__1_
				WHEN INSTITUICAO_FIINSTIT = INSTITUICAO_FINANCEI THEN DATA_RESPOSTA__2_
				WHEN INSTITUICAO_FIINSTIT = ANALISE_3 THEN DADATA_RESPOSTATA_RE
				ELSE NULL END) AS DT
	     FROM IV_Q$GESTAO_CREDITO
		 WHERE PROCESSO = PRC.PROCESSO) AS DTAPROVACAO_CREDITOTRT,
	   ( SELECT MIN(
		   CASE WHEN INSTITUICAO_FIINSTIT = ANALISE_2 THEN DATA_RESPOSTA__1_
				WHEN INSTITUICAO_FIINSTIT = INSTITUICAO_FINANCEI THEN DATA_RESPOSTA__2_
				WHEN INSTITUICAO_FIINSTIT = ANALISE_3 THEN DADATA_RESPOSTATA_RE
				ELSE NULL END) AS DT
	     FROM IV_Q$GESTAO_CREDITO_IMP
		 WHERE PROCESSO = PRC.PROCESSO) AS DTAPROVACAO_CREDITOIMP,
	   ( SELECT MIN(
		   CASE WHEN INSTITUICAO_FIINSTIT = ANALISE_2 THEN DATA_RESPOSTA__1_
				WHEN INSTITUICAO_FIINSTIT = INSTITUICAO_FINANCEI THEN DATA_RESPOSTA__2_
				WHEN INSTITUICAO_FIINSTIT = ANALISE_3 THEN DADATA_RESPOSTATA_RE
				ELSE NULL END) AS DT
	     FROM IV_Q$GESTAO_CREDITO_IMP
		 WHERE PROCESSO = PRC.PROCESSO) AS DTAPROVACAO_CREDITOAMS
FROM IV_PROCESSO PRC
) XA
WHERE XA.DTVENDA_AUTORIZADA IS NOT NULL
