/* ==============================================================
   Objeto ..........: dbo.BI_OPORT_FUNIL2_BKP
   Tipo ............: VIEW
   Criado em .......: 2016-02-26 14:53:33
   Modificado em ...: 2016-03-22 19:20:05
   Linhas ..........: 82
   Escreve em tabela: nao
   Tabelas referidas: IV_PROCDADO, IV_PROCESSO, IV_PROCPERSP, IV_PROCSTATMONIT
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */


CREATE view [dbo].[BI_OPORT_FUNIL2_BKP] AS
SELECT PDD.PROCESSO AS ONE_PROCESSO,
       PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Monitoramento' as FUNIL_TIPO,
	   SMON.DTAMONIT AS STAT_DTAMONIT,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(SMON.DTAMONIT, SMON.DTAMONIT) ), 0) AS ONE_DATA_REALIZADOF,
       SMON.STATUS AS STAT_STATUS,
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_PROCDADO PMON ON PMON.CODPROCESSO = 9400 AND PMON.PROCESSO = PDD.PROCESSOPAI
  JOIN IV_PROCSTATMONIT SMON ON SMON.PROCESSO = PDD.PROCESSOPAI
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 35
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

  union
  SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Oportunidade' as FUNIL_TIPO,
	   ISNULL(PDD.DTAPRIMRESULTADO, PRC.DTAREALIZACAO),
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(PDD.DTAPRIMRESULTADO, PRC.DTAREALIZACAO) ), 0) AS ONE_DATA_REALIZADOF,
       NULL,
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 35
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

 UNION
 SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Pedido' as FUNIL_TIPO,
	   SMON.DTAMONIT,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(SMON.DTAMONIT, SMON.DTAMONIT) ), 0) AS ONE_DATA_REALIZADOF,
       SMON.STATUS,
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_PROCSTATMONIT SMON ON SMON.PROCESSO = PRC.PROCESSO AND SMON.STATUS = 'PEDIDO REALIZADO'
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 35
   AND PRC.STATUS != 'VENDA PERDIDA'
   AND PRC.STATUS != 'DESISTIU DA COMPRA'
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

 union
 SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Venda' as FUNIL_TIPO,
 	   SMON.DTAMONIT,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(SMON.DTAMONIT, SMON.DTAMONIT) ), 0) AS ONE_DATA_REALIZADOF,
       SMON.STATUS,
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_PROCSTATMONIT SMON ON SMON.PROCESSO = PRC.PROCESSO AND SMON.STATUS = 'FATURADO'
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 35
   AND PRC.STATUS != 'VENDA PERDIDA'
   AND PRC.STATUS != 'DESISTIU DA COMPRA'
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

;