/* ==============================================================
   Objeto ..........: dbo.BI_OPORT_FUNIL2
   Tipo ............: VIEW
   Criado em .......: 2016-03-01 16:58:48
   Modificado em ...: 2016-10-10 16:13:54
   Linhas ..........: 132
   Escreve em tabela: nao
   Tabelas referidas: IV_HISTORICO, IV_PROCDADO, IV_PROCESSO, IV_PROCPERSP, IV_PROCSTATMONIT
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE view [dbo].[BI_OPORT_FUNIL2] AS
SELECT PDD.PROCESSO AS ONE_PROCESSO,
       PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Monitoramento' as FUNIL_TIPO,
	   SMON.DTAMONIT AS STAT_DTAMONIT,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(SMON.DTAMONIT, SMON.DTAMONIT) ), 0) AS ONE_DATA_REALIZADOF,
       SMON.STATUS AS STAT_STATUS,
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_PROCDADO PMON ON PMON.CODPROCESSO = 9400 AND PMON.PROCESSO = PDD.PROCESSOPAI
  JOIN IV_PROCSTATMONIT SMON ON SMON.PROCESSO = PDD.PROCESSOPAI
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 0
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

  union

  SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Oportunidade' as FUNIL_TIPO,
	   ISNULL(PDD.DTAPRIMRESULTADO, PRC.DTAREALIZACAO),
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(PDD.DTAPRIMRESULTADO, PRC.DTAREALIZACAO) ), 0) AS ONE_DATA_REALIZADOF,
       NULL,
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 3
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

 UNION

 SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Pedido' as FUNIL_TIPO,
	   HIS.DTAREALIZACAO,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(HIS.DTAREALIZACAO, HIS.DTAREALIZACAO) ), 0) AS ONE_DATA_REALIZADOF,
       'PEDIDO REALIZADO',
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_HISTORICO HIS ON HIS.PROCESSO = PRC.PROCESSO 
                       AND HIS.RESULTADO IN (206, 255, 256, 421)
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 16
   AND PRC.STATUS != 'VENDA PERDIDA'
   AND PRC.STATUS != 'DESISTIU DA COMPRA'
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

 union
 SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Venda' as FUNIL_TIPO,
 	   HIS.DTAREALIZACAO,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(HIS.DTAREALIZACAO, HIS.DTAREALIZACAO) ), 0) AS ONE_DATA_REALIZADOF,
       'VENDA REALIZADA',
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_HISTORICO HIS ON HIS.PROCESSO = PRC.PROCESSO 
                       AND HIS.RESULTADO IN ( 212, 330)
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   AND PRC.FASEORDEM > 16
   AND PRC.STATUS != 'VENDA PERDIDA'
   AND PRC.STATUS != 'DESISTIU DA COMPRA'
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

    union
 SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Venda Perdida' as FUNIL_TIPO,
 	   HIS.DTAREALIZACAO,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(HIS.DTAREALIZACAO, HIS.DTAREALIZACAO) ), 0) AS ONE_DATA_REALIZADOF,
       'VENDA PERDIDA',
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_HISTORICO HIS ON HIS.PROCESSO = PRC.PROCESSO 
                       AND HIS.RESULTADO IN ( 221, 258, 610 )
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   ---AND PRC.FASEORDEM > 35
   AND PRC.STATUS = 'VENDA PERDIDA'
   AND PRC.STATUS != 'DESISTIU DA COMPRA'
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)

   union
 SELECT PDD.PROCESSO AS ONE_PROCESSO,
      PDD.CAMPANHA AS ONE_CAMPANHAFUN,
       'Desistiu da Compra' as FUNIL_TIPO,
 	   HIS.DTAREALIZACAO,
	   DATEADD(DD, DATEDIFF(DD, 0, ISNULL(HIS.DTAREALIZACAO, HIS.DTAREALIZACAO) ), 0) AS ONE_DATA_REALIZADOF,
       'DESISTIU DA COMPRA',
       1 AS FUNIL_VALOR
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  JOIN IV_HISTORICO HIS ON HIS.PROCESSO = PRC.PROCESSO 
                       AND HIS.RESULTADO IN (220, 257, 259 )
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
 WHERE PDD.CODPROCESSO IN (7)
   ---AND PRC.FASEORDEM > 35
   AND PRC.STATUS != 'VENDA PERDIDA'
   AND PRC.STATUS = 'DESISTIU DA COMPRA'
   AND  ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO) >= convert(datetime,'01/01/2010',103)




