/* ==============================================================
   Objeto ..........: dbo.bi_Oportunidades
   Tipo ............: VIEW
   Criado em .......: 2019-10-28 13:26:15
   Modificado em ...: 2022-09-15 11:55:08
   Linhas ..........: 35
   Escreve em tabela: nao
   Tabelas referidas: IV_CLASSERES, IV_HISTORICO, IV_PROCDADO, IV_RESCLASSE, IV_RESULTADO, IVS_PES
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW [dbo].[bi_Oportunidades] as
SELECT HIST.SEQPESSOA
     , HIST.PROCESSO
     , PDD.ProcessoDNA
     , PDD.ProcessoPai
     , CRES.CLASSE
     , RES.RESULTADO 			AS COD_RESULTADO
     , RES.DESCRICAO 			AS RESULTADO
     , HIST.RESULTADOCMPL     
     , HIST.DTAREALIZACAO 		AS DTAREALIZACAO
     , HIST.VENDEDOR
     , PDD.CAMPANHA
FROM IV_HISTORICO HIST
  JOIN IVS_PES PES ON PES.SEQPESSOA = HIST.SEQPESSOA AND PES.SEQDEPTO = 2
  JOIN IV_PROCDADO PDD ON PDD.PROCESSO = HIST.PROCESSO
  JOIN IV_RESULTADO RES ON RES.RESULTADO = HIST.RESULTADO
  JOIN IV_RESCLASSE RCL ON RCL.RESULTADO = RES.RESULTADO
  JOIN IV_CLASSERES CRES ON CRES.SEQCLASSERES = RCL.SEQCLASSERES
	AND CRES.CLASSE IN ( '2-Oportunidade' ) 
WHERE YEAR(HIST.DTAREALIZACAO) >= YEAR('2015')
  AND HIST.SEQHISTORICO = 
  ( SELECT MAX(H.SEQHISTORICO)
	FROM 		IV_HISTORICO H
		JOIN  		IV_RESCLASSE RCL 	ON RCL.RESULTADO 		= H.RESULTADO
		JOIN 		IV_CLASSERES CRES 	ON CRES.SEQCLASSERES 	= RCL.SEQCLASSERES AND CRES.CLASSE IN ('2-Oportunidade') 
		LEFT JOIN	IV_PROCDADO		dna		ON H.PROCESSO		= DNA.Processo -- TABELA ADICIONADA NO DIA 28/10/2019	
			WHERE 
				--H.PROCESSO = HIST.PROCESSO  			-- FILTRO ORIGINAL DESENVOLVIDO PELA VORTICE
				DNA.ProcessoDNA=PDD.ProcessoDNA
				) 			-- NOVO FILTRO DESENVOLVIDO NO DIA 28/10/2019.
				AND NOT EXISTS 
				(SELECT 1 
  					FROM IV_HISTORICO H
    				WHERE H.PROCESSO = HIST.PROCESSO AND H.RESULTADO IN ( 2140, 2142) AND H.DTAREALIZACAO > HIST.DTAREALIZACAO )
