/* ==============================================================
   Objeto ..........: dbo.BI_OPORTUNIDADE_ENC
   Tipo ............: VIEW
   Criado em .......: 2015-09-09 20:12:03
   Modificado em ...: 2023-11-13 15:39:04
   Linhas ..........: 101
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_ACAO, IV_AGENDA, IV_HISTORICO, IV_PROCDADO, IV_PROCESSO, IV_PROCPERSP, IV_ProcStatMonit, IV_RESULTADO
   Outras refs .....: IV_Q$ACOMPANH_VENDA_JDE, IV_Q$GESTAO_CREDITO, IV_Q$GESTAO_CREDITO_AMS, IV_Q$GESTAO_CREDITO_IMP
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW [dbo].[BI_OPORTUNIDADE_ENC] AS  

SELECT PDD.SEQPESSOA,
       PDD.PROCESSO AS ONE_PROCESSO,
       PDD.CAMPANHA AS ONE_CAMPANHAENC,
       CASE
         WHEN PRC.FASEORDEM < 50 THEN
          '5-Entrega'
         else
          '9-Encerrado'
       END AS ONE_ETAPA,
       CAST(PRC.FASEORDEM AS VARCHAR(2)) + '-' + PRC.FASE AS ONE_FASE,
       PRC.FASEORDEM AS ONE_FASE_ORDEM,

	   CASE WHEN PMON.STATUS = '** Nenhum **'    THEN 'Faturado'
			WHEN PMON.STATUS = 'A iniciar'		THEN 'Em andamento'
			WHEN PMON.STATUS = 'CANCELADO'		THEN 'Cancelado'
			WHEN PMON.STATUS = 'CONCLUIDO'		THEN 'Finalizado'
			WHEN PMON.STATUS = 'DESISTIU DA COMPRA' THEN 'Desistiu da compra'
			WHEN PMON.STATUS = 'DESISTENCIA COMPRA' THEN 'Desistiu da compra'
			WHEN PMON.STATUS = 'EM ABERTO'		THEN 'Em andamento'
			WHEN PMON.STATUS = 'EM ANDAMENTO'	THEN 'Em andamento'
---			WHEN PMON.STATUS = 'ENTREGA'			THEN 'Faturado'
			WHEN PMON.STATUS = 'FATURADO'		THEN 'Faturado'
			WHEN PMON.STATUS = 'PEDIDO REALIZADO' THEN 'Em andamento'
			WHEN PMON.STATUS = 'VENDA PERDIDA'	THEN 'Venda perdida'
			WHEN PMON.STATUS = 'VENDA REALIZADA'	THEN 'Faturado'
			WHEN ISNULL(PMON.STATUS, '@')='@' or PMON.STATUS='' THEN '*Atualizar*' 
			WHEN PMON.STATUS = 'PENDENTE'	    THEN '*Atualizar*'
			ELSE PMON.STATUS END AS ONE_STATUS,
	   PMON.STATUS AS ONE_STATUSDESC,

       DATEADD(DD, DATEDIFF(DD, 0, PRC.DTAINCLUSAO), 0) AS ONE_DATA_INICIO,
       DATEADD(DD,
               DATEDIFF(DD,
                        0,
                        ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO)),
               0) AS ONE_DATA_REALIZADO,
       RIGHT(CAST(YEAR(ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO)) AS
                  VARCHAR(4)),
             2) + '/' +
       RIGHT('0' + CAST(MONTH(ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO)) AS
                        VARCHAR(2)),
             2) AS ONE_ANOMES_REALIZADO,
       RIGHT('0' +
             CAST(MONTH ( ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO)) AS VARCHAR(2)),
             2) AS ONE_MES_REALIZADO,
	   ACV.FORM,
	   ACV.FATUR_REALIZADO,
       --DATEADD(DD,
       --        DATEDIFF(DD,
       --                 0,
       --                 ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO)),
       --        0) - DATEADD(DD, DATEDIFF(DD, 0, PRC.DTAINCLUSAO), 0) AS ONE_DURACAO_DIAS,
       DATEDIFF(DD, 0, ISNULL(PRC.DTAREALIZACAO, PDD.DTAULTRESULTADO)) - DATEDIFF(DD, 0, PRC.DTAINCLUSAO) AS ONE_DURACAO_DIAS,
       PRC.VALOR AS ONE_VALOR,
       PRC.PERSPECTIVA AS ONE_PERSP_PERCT,
       case when isnull(PESP.PERSPECTIVA, '@')='@' then 'n.info.' 
	        when PESP.PERSPECTIVA='' then 'n.info.' 
	        else PESP.PERSPECTIVA end AS ONE_PERSPECTIVA,
       PRC.USURESPONSAVEL AS ONE_CEN,
       PDD.NROEMPRESA,
	   (SELECT SEQPESSOAPRC FROM GE_PESSOA WHERE SEQPESSOA = PDD.SEQPESSOA) AS SEQPRINC,
	   (SELECT AC2.DESCRICAO FROM IV_ACAO AC2, IV_RESULTADO RE2 WHERE RE2.Resultado = PDD.UltResultado AND AC2.ACAO = RE2.ACAO) AS ONE_DESC_ACAO,
	   PDD.UsuGeracao AS ONE_ATENDENTE,
	   PDD.CodProcesso AS ONE_CODPROCESSO
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
  LEFT JOIN (SELECT PROCESSO, 
                  STATUS, 
				  ROW_NUMBER() OVER ( PARTITION BY PROCESSO ORDER BY DTAMONIT DESC ) AS RANKMON 
	       FROM IV_ProcStatMonit 
	       ) PMON ON PMON.Processo = PRC.Processo AND PMON.RANKMON=1
  LEFT JOIN IV_PROCPERSP PESP
    ON PESP.CODPROCESSO = PDD.CODPROCESSO
   AND PESP.PERSPORDEM = PRC.PERSPECTIVA
  LEFT JOIN (SELECT XA.PROCESSO, XA.FATUR_REALIZADO, XA.FORM, 
                    ROW_NUMBER() OVER ( PARTITION BY XA.PROCESSO ORDER BY XA.FATUR_REALIZADO, XA.FORM ) AS RANKFORM
			 FROM (SELECT PROCESSO, faturamento_realiz   AS FATUR_REALIZADO, 1 AS FORM FROM IV_Q$ACOMPANH_VENDA_JDE
				   UNION
				   SELECT PROCESSO, FATURAMENTO_REALIZAD, 2 FROM IV_Q$GESTAO_CREDITO
				   UNION
				   SELECT PROCESSO, FATURAMENTO_REALIZAD, 3 FROM IV_Q$GESTAO_CREDITO_IMP
				   UNION
				   SELECT PROCESSO, FATURAMENTO_REALIZAD, 4 FROM IV_Q$GESTAO_CREDITO_AMS) XA
				   WHERE XA.FATUR_REALIZADO IS NOT NULL ) ACV
			ON ACV.PROCESSO = PDD.PROCESSO 
		   AND ACV.RANKFORM = 1
 WHERE PDD.CODPROCESSO IN ( 7, 37 )    /* Tirado monitoramento 9400 26/03/2023 */
   AND ISNULL(PRC.DtaRealizacao, PDD.DtaUltResultado) >=
       convert(datetime, '01/01/2010', 103)
   AND 1 = ( case when upper(PRC.STATUS) = 'FINALIZADO'  
                  then case when PDD.CODPROCESSO = 9400 then 0 else 1 end
				  else 1 end )
   AND NOT EXISTS (SELECT 1 FROM IV_AGENDA AG2
                         WHERE AG2.ACAO IN ( SELECT ACAO FROM IV_ACAO WHERE EMUSO='S' )
						   AND AG2.Processo = PDD.Processo
						   AND NOT EXISTS (SELECT 1 FROM IV_HISTORICO WHERE PROCESSO = AG2.PROCESSO))

