/* ==============================================================
   Objeto ..........: dbo.bi_pedidos
   Tipo ............: VIEW
   Criado em .......: 2019-10-28 13:27:03
   Modificado em ...: 2019-10-28 13:27:03
   Linhas ..........: 31
   Escreve em tabela: nao
   Tabelas referidas: IV_CLASSERES, IV_HISTORICO, IV_PROCDADO, IV_RESCLASSE, IV_RESULTADO, IVS_PES
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW bi_pedidos as
SELECT HIST.SEQPESSOA
     , HIST.PROCESSO
     , PDD.ProcessoDNA
     , PDD.ProcessoPai
     , CRES.CLASSE
     , RES.RESULTADO 			AS COD_RESULTADO
     , RES.DESCRICAO 			AS RESULTADO
     , HIST.RESULTADOCMPL     
     , HIST.DTAREALIZACAO 		AS DTAREALIZACAO
     , HIST.VENDEDOR
     , PDD.CAMPANHA
FROM IV_HISTORICO HIST
  JOIN IVS_PES PES ON PES.SEQPESSOA = HIST.SEQPESSOA AND PES.SEQDEPTO = 2
  JOIN IV_PROCDADO PDD ON PDD.PROCESSO = HIST.PROCESSO
  JOIN IV_RESULTADO RES ON RES.RESULTADO = HIST.RESULTADO
  JOIN IV_RESCLASSE RCL ON RCL.RESULTADO = RES.RESULTADO
  JOIN IV_CLASSERES CRES ON CRES.SEQCLASSERES = RCL.SEQCLASSERES
	AND CRES.CLASSE IN ( '3-Pedido' )    
WHERE YEAR(HIST.DTAREALIZACAO) >= YEAR('2015')
  AND HIST.SEQHISTORICO = ( SELECT MAX(H.SEQHISTORICO)
			FROM IV_HISTORICO H
			  JOIN  IV_RESCLASSE RCL ON RCL.RESULTADO = H.RESULTADO
			  JOIN IV_CLASSERES CRES ON CRES.SEQCLASSERES = RCL.SEQCLASSERES
				AND CRES.CLASSE IN ( '3-Pedido' )                  
			WHERE H.PROCESSO = HIST.PROCESSO )
  AND NOT EXISTS ( SELECT 1 
  					FROM IV_HISTORICO 
                   WHERE PROCESSO = HIST.PROCESSO 
                   AND RESULTADO IN (269, 311) 
                   AND DTAREALIZACAO > HIST.DTAREALIZACAO)