/* ==============================================================
   Objeto ..........: dbo.BI_VISITA
   Tipo ............: VIEW
   Criado em .......: 2015-08-07 11:03:00
   Modificado em ...: 2016-03-22 19:20:05
   Linhas ..........: 72
   Escreve em tabela: nao
   Tabelas referidas: IV_AGENDA, IV_HISTORICO, IV_RESULTADO, IVS_CARTDEPTO, IVS_CARTEIRA, IVS_DEPTORES
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW BI_VISITA AS
SELECT AGD.SEQAGENDA AS SEQAGDDPLAN,
       AGD.SEQUSUARIO,
       AGD.SEQPESSOA,
       CASE WHEN AGD.DTAAGENDAORIGINAL IS NULL THEN
         CASE WHEN HST.DTAREALIZACAO < AGD.DTAAGENDA THEN HST.DTAREALIZACAO
           ELSE AGD.DTAAGENDA
           END
         ELSE AGD.DTAAGENDAORIGINAL
           END AS VISITA_DATA_PLANEJADA,
       AGD.ASSUNTO AS VISITA_ASSUNTO,
       CASE
         WHEN HST.SEQHISTORICO > 0 THEN
          'Sim'
         ELSE
          'Não'
       END AS VISITA_OK,
       HST.DTAREALIZACAO AS VISITA_DATA_REALIZADA,
       RES.DESCREDUZIDA  AS VISITA_RESULTADO,
       HST.RESULTADOCMPL AS VISITA_RESULTADO_CMPL,
       HST.CODUSUARIO    AS VISITA_REALIZADA_POR,
       HST.FORMAPRIMCONT AS VISITA_CANAL,
       CASE
         WHEN DRES.INDEXTFORMACTTO = 1 AND HST.FORMAPRIMCONT = 'Externo' THEN
          'Sim'
         ELSE
          'Não'
       END AS VISITA_EXTERNA
  FROM IV_AGENDA AGD
  LEFT JOIN IV_HISTORICO HST
  JOIN IV_RESULTADO RES
    ON RES.RESULTADO = HST.RESULTADO
  JOIN IVS_DEPTORES DRES
    ON DRES.RESULTADO = HST.RESULTADO
   AND DRES.SEQDEPTO = 2 ON HST.AGENDAORIGEM = AGD.SEQAGENDA
 WHERE AGD.SEQUSUARIO IN (SELECT CRT.SEQUSRRESP
                            FROM IVS_CARTEIRA CRT
                            JOIN IVS_CARTDEPTO CDP
                              ON CDP.SEQCARTEIRA = CRT.SEQCARTEIRA
                             AND CDP.SEQDEPTO = 2)
   AND (AGD.REALIZADA = 'N' OR AGD.DTAREALIZACAO >= (GETDATE() - 180))
UNION ALL
SELECT HST.SEQHISTORICO * -1,
       HST.SEQUSUARIO,
       HST.SEQPESSOA,
       NULL AS DTAAGENDA,
       '* Avulso * ' as ASSUNTO,
       'Sim' as VISITADO,
       HST.DTAREALIZACAO,
       RES.DESCREDUZIDA,
       HST.RESULTADOCMPL AS VISITA_RESULTADO_CMPL,
       HST.CODUSUARIO,
       HST.FORMAPRIMCONT,
       CASE
         WHEN DRES.INDEXTFORMACTTO = 1 AND HST.FORMAPRIMCONT = 'Externo' THEN
          'Sim'
         ELSE
          'Não'
       END AS VISITA
  FROM IV_HISTORICO HST
  JOIN IV_RESULTADO RES
    ON RES.RESULTADO = HST.RESULTADO
  JOIN IVS_DEPTORES DRES
    ON DRES.RESULTADO = HST.RESULTADO
   AND DRES.SEQDEPTO = 2
 WHERE HST.AGENDAORIGEM IS NULL
   AND HST.SEQUSUARIO IN (SELECT CRT.SEQUSRRESP
                            FROM IVS_CARTEIRA CRT
                            JOIN IVS_CARTDEPTO CDP
                              ON CDP.SEQCARTEIRA = CRT.SEQCARTEIRA
                             AND CDP.SEQDEPTO = 2)
   AND HST.DTAREALIZACAO >= (GETDATE() - 180)