/* ==============================================================
   Objeto ..........: dbo.BI_VENDA_MAQ_ENC
   Tipo ............: VIEW
   Criado em .......: 2015-08-25 16:22:22
   Modificado em ...: 2023-11-13 16:40:34
   Linhas ..........: 235
   Escreve em tabela: nao
   Tabelas referidas: GE_LgTb, IV_PROCDADO, IV_PROCESSO, IV_PROCSTATMONIT
   Outras refs .....: BI_DTAPROVCREDITO, IV_Q$ACOMP_VEND_MAQUINAS, IV_Q$ACOMPANH_VENDA_JDE, IV_Q$GESTAO_CREDITO, IV_Q$GESTAO_CREDITO_AMS, IV_Q$GESTAO_CREDITO_IMP, IV_Q$GESTAO_PRODUTO___AMS, IV_Q$GESTAO_PRODUTO_IMPL
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW [dbo].[BI_VENDA_MAQ_ENC] AS
SELECT DISTINCT 
       1 as TIPOFORM,
       ACV.processo AS ONE_PROCESSO,
       ACV.TP_PGTO1 AS VDAE_TIPO_FINANCIAMENTO,
       ACV.INSTITUI_FINANCEIRA1 AS VDAE_INST_FINANCEIRA,
       ACV.VLR_TOTAL1 AS VDAE_VALOR,
       ACV.MODEL_EQUIP1 AS VDAE_MODELO,
       ACV.MARCA_1 AS VDAE_MARCA,
       ACV.TIPO_EQUIP1 AS VDAE_TIPO_MAQUINA,
       case
         when ACV.PROB_APROV_CRED1 = 'Alta' then
          '1-Alta'
         when ACV.PROB_APROV_CRED1 = 'Média' then
          '2-Média'
         else
          '3-Baixa'
       end AS VDAE_PROB_APROVACAO,
	   CASE WHEN ISNULL(ACV.PAC_EMITIDO, GETDATE()) = GETDATE() THEN 'NÃO' ELSE 'SIM' END AS VDAE_PAC_EMITIDO,
       ACV.pac_emitido AS VDAE_DATA_PAC,
       ( SELECT  MIN(PSM.DTAMONIT) FROM IV_PROCSTATMONIT PSM WHERE PSM.PROCESSO = ACV.PROCESSO AND PSM.STATUS = 'FAT AUTORIZADO') AS VDAE_DATA_FAT_AUTORIZ,
       CASE WHEN ISNULL(ACV.FATURAMENTO_REALIZ, GETDATE()) = GETDATE() THEN 'NÃO' ELSE 'SIM' END AS VDAE_FATURAMENTO_REALIZADO,
       ACV.faturamento_realiz AS VDAE_DATA_FATURAMENTO,
       ACV.PREV_FATURAM1 AS VDAE_DATA_PREVISTA_FATURAMENTO,
       RIGHT( CAST ( YEAR( ACV.PREV_FATURAM1 ) AS VARCHAR(4) ), 2)  + '/' + 
       RIGHT( '0' + CAST ( MONTH( ACV.PREV_FATURAM1 ) AS VARCHAR(2)), 2) AS VDAE_MES_PREVISTO_FATURAMENTO,
       RIGHT( CAST ( YEAR( ACV.faturamento_realiz ) AS VARCHAR(4) ), 2)  + '/' + 
       RIGHT( '0' + CAST ( MONTH( ACV.faturamento_realiz ) AS VARCHAR(2)), 2) AS VDAE_MES_FATURAMENTO,
       ACV.origem_faturamento AS VDAE_ORIGEM_FATURAMENTO,
       DATEDIFF(DD, ACV.data_pedido_de_venda, ACV.pac_emitido ) AS VDAE_DIAS_PEDIDO_PAC,
	   DATEDIFF(DD, ACV.data_pedido_de_venda, ACV.faturamento_realiz ) AS VDAE_DIAS_PEDIDO_FATURAMENTO,
	   DATEDIFF(DD, ACV.pac_emitido, ACV.faturamento_realiz ) AS VDAE_DIAS_PAC_FATURAMENTO,
    --   DATEADD(DD, DATEDIFF(DD, 0, ACV.pac_emitido - ACV.data_pedido_de_venda ), 0) AS VDAE_DIAS_PEDIDO_PAC,
	   --DATEADD(DD, DATEDIFF(DD, 0, ACV.faturamento_realiz - ACV.data_pedido_de_venda ), 0) AS VDAE_DIAS_PEDIDO_FATURAMENTO,
	   --DATEADD(DD, DATEDIFF(DD, 0, ACV.faturamento_realiz - ACV.pac_emitido ), 0) AS VDAE_DIAS_PAC_FATURAMENTO
	   QPROV.DTVENDA_AUTORIZADA AS VDAE_DTVENDA_AUTORIZADA , 
	   QPROV.DTVENDA_PAGTO AS VDAE_DTVENDA_PAGTO, 
	   QPROV.DTAPROVACAO_CREDITOTRT AS VDAE_DTAPROVACAO_CREDITOTRT, 
	   QPROV.DTAPROVACAO_CREDITOIMP AS VDAE_DTAPROVACAO_CREDITOIMP, 
	   QPROV.DTAPROVACAO_CREDITOAMS AS VDAE_DTAPROVACAO_CREDITOAMS,
	   NULL AS INST_SELECIONADA,
	   NULL AS VDAE_DT_LIBERACAO

 FROM IV_Q$ACOMPANH_VENDA_JDE ACV
 LEFT JOIN BI_DTAPROVCREDITO QPROV ON QPROV.PROCESSO = ACV.Processo
 WHERE ACV.PROCESSO IN (SELECT PDD.PROCESSO
                      FROM IV_PROCDADO PDD
                      JOIN IV_PROCESSO PRC
                        ON PRC.PROCESSO = PDD.PROCESSO
                     WHERE PDD.CODPROCESSO IN (7)
                       AND PRC.FASEORDEM > 35)

UNION ALL

---- FORMULARIO NOVO MAQUI / CREDITO

SELECT      DISTINCT 
            2 as TIPOFORM,
			GFI.processo                        AS ONE_PROCESSO,
            GFI.FORMA_PAGAMENTO                 AS VDAE_TIPO_FINANCIAMENTO,
            GFI.INSTITUICAO_FIINSTIT            AS VDAE_INST_FINANCEIRA,
            GFI.VALOR_TOTAL                     AS VDAE_VALOR,
            AVM.MODELO_EQUIPAMENTO              AS VDAE_MODELO,
            AVM.MARCA                           AS VDAE_MARCA,
            AVM.TIPO_EQUIPAMENTO                AS VDAE_TIPO_MAQUINA,
            GFI.PROBABILIDADE                   AS VDAE_PROB_APROVACAO,
            CASE WHEN GFI.STATUS_PROCESSO='Autorizado' then 'SIM' else 'NÃO' END 
                                                AS VDAE_PAC_EMITIDO,
            ( SELECT DTALOG FROM GE_LgTb 
                  WHERE tb='IV_QUESTIONARIO' and KN1 = GFI.SEQQUESTIONARIO AND CODAPL = ' IVS1QST01' 
                    AND OBS LIKE '%Status Processo Financ de Em Analise, para Fatur Autorizado%' ) 
                                                AS VDAE_DATA_PAC,
            NULL AS VDAE_DATA_FAT_AUTORIZ,
            CASE WHEN ISNULL(GFI.NOTA_FISCAL, 0)<>0 THEN 'SIM' else 'NÃO' END 
                                                AS VDAE_FATURAMENTO_REALIZADO,
            GFI.FATURAMENTO_REALIZAD            AS VDAE_DATA_FATURAMENTO,
            NULL AS VDAE_DATA_PREVISTA_FATURAMENTO,
            NULL AS VDAE_MES_PREVISTO_FATURAMENTO,
            RIGHT( '0' + CAST ( MONTH( GFI.FATURAMENTO_REALIZAD ) AS VARCHAR(2)), 2) 
                 AS VDAE_MES_FATURAMENTO,
            NULL AS VDAE_ORIGEM_FATURAMENTO,
            NULL AS VDAE_DIAS_PEDIDO_PAC,
            NULL AS VDAE_DIAS_PEDIDO_FATURAMENTO,
            NULL AS VDAE_DIAS_PAC_FATURAMENTO,
		   QPROV.DTVENDA_AUTORIZADA AS VDAE_DTVENDA_AUTORIZADA , 
		   QPROV.DTVENDA_PAGTO AS VDAE_DTVENDA_PAGTO, 
		   QPROV.DTAPROVACAO_CREDITOTRT AS VDAE_DTAPROVACAO_CREDITOTRT, 
		   QPROV.DTAPROVACAO_CREDITOIMP AS VDAE_DTAPROVACAO_CREDITOIMP, 
		   QPROV.DTAPROVACAO_CREDITOAMS AS VDAE_DTAPROVACAO_CREDITOAMS,

		   INSTITUICAO_FIINSTIT AS INST_SELECIONADA,
		   CASE WHEN INSTITUICAO_FIINSTIT = ANALISE_2 AND 
		             STATUS_ANALISE_BC = 'Aprovado' 
			    THEN DATA_RESPOSTA__1_
				WHEN INSTITUICAO_FIINSTIT = INSTITUICAO_FINANCEI AND 
		             STATUS_BC_2 = 'Aprovado' 
			    THEN DATA_RESPOSTA__2_
				WHEN INSTITUICAO_FIINSTIT = ANALISE_3 AND 
		             ANALISE_BC_3 = 'Aprovado' 
			    THEN DADATA_RESPOSTATA_RE
				END
				AS VDAE_DT_LIBERACAO

FROM IV_Q$GESTAO_CREDITO GFI
JOIN IV_Q$ACOMP_VEND_MAQUINAS AVM ON AVM.PROCESSO = GFI.PROCESSO AND AVM.FORMULARIO_NUMERO = GFI.FORMULARIO_NUMERO
 LEFT JOIN BI_DTAPROVCREDITO QPROV ON QPROV.PROCESSO = GFI.Processo
WHERE GFI.PROCESSO IN (SELECT PDD.PROCESSO
                      FROM IV_PROCDADO PDD
                      JOIN IV_PROCESSO PRC
                        ON PRC.PROCESSO = PDD.PROCESSO
                     WHERE PDD.CODPROCESSO IN (37)
                       AND PRC.FASEORDEM > 45)


--- FORMULARIO NOVO IMPL / CREDITO

UNION ALL

SELECT      DISTINCT 
            3 as TIPOFORM,
			GFI.PROCESSO                        AS ONE_PROCESSO,
            GFI.FORMA_PAGAMENTO                 AS VDAE_TIPO_FINANCIAMENTO,
            GFI.INSTITUICAO_FIINSTIT            AS VDAE_INST_FINANCEIRA,
            GFI.VALOR_TOTAL                     AS VDAE_VALOR,
            AVM.MODELO_IMPLEMENTO               AS VDAE_MODELO,
            AVM.MARCA                           AS VDAE_MARCA,
            AVM.TIPO_EQUIPAMENTO                AS VDAE_TIPO_MAQUINA,
            GFI.PROBABILIDADE                   AS VDAE_PROB_APROVACAO,
            CASE WHEN GFI.STATUS_PROCESSO='Autorizado' then 'SIM' else 'NÃO' END 
                                                AS VDAE_PAC_EMITIDO,
            ( SELECT DTALOG FROM GE_LgTb 
                  WHERE tb='IV_QUESTIONARIO' and KN1 = GFI.SEQQUESTIONARIO AND CODAPL = ' IVS1QST01' 
                    AND OBS LIKE '%Status Processo Financ de Em Analise, para Fatur Autorizado%' ) 
                                                AS VDAE_DATA_PAC,
            NULL AS VDAE_DATA_FAT_AUTORIZ,                                                
            CASE WHEN ISNULL(GFI.NOTA_FISCAL, 0)<>0 THEN 'SIM' else 'NÃO' END 
                                                AS VDAE_FATURAMENTO_REALIZADO,
            GFI.FATURAMENTO_REALIZAD      AS VDAE_DATA_FATURAMENTO,
            NULL AS VDAE_DATA_PREVISTA_FATURAMENTO,
            NULL AS VDAE_MES_PREVISTO_FATURAMENTO,
            RIGHT( '0' + CAST ( MONTH( GFI.FATURAMENTO_REALIZAD ) AS VARCHAR(2)), 2) 
                 AS VDAE_MES_FATURAMENTO,
            NULL AS VDAE_ORIGEM_FATURAMENTO,
            NULL AS VDAE_DIAS_PEDIDO_PAC,
            NULL AS VDAE_DIAS_PEDIDO_FATURAMENTO,
            NULL AS VDAE_DIAS_PAC_FATURAMENTO,
		   QPROV.DTVENDA_AUTORIZADA AS VDAE_DTVENDA_AUTORIZADA , 
		   QPROV.DTVENDA_PAGTO AS VDAE_DTVENDA_PAGTO, 
		   QPROV.DTAPROVACAO_CREDITOTRT AS VDAE_DTAPROVACAO_CREDITOTRT, 
		   QPROV.DTAPROVACAO_CREDITOIMP AS VDAE_DTAPROVACAO_CREDITOIMP, 
		   QPROV.DTAPROVACAO_CREDITOAMS AS VDAE_DTAPROVACAO_CREDITOAMS,

		   INSTITUICAO_FIINSTIT AS INST_SELECIONADA,
		   CASE WHEN INSTITUICAO_FIINSTIT = ANALISE_2 AND 
		             STATUS_ANALISE_BC = 'Aprovado' 
			    THEN DATA_RESPOSTA__1_
				WHEN INSTITUICAO_FIINSTIT = INSTITUICAO_FINANCEI AND 
		             STATUS_BC_2 = 'Aprovado' 
			    THEN DATA_RESPOSTA__2_
				WHEN INSTITUICAO_FIINSTIT = ANALISE_3 AND 
		             ANALISE_BC_3 = 'Aprovado' 
			    THEN DADATA_RESPOSTATA_RE
				END
				AS VDAE_DT_LIBERACAO

FROM IV_Q$GESTAO_CREDITO_IMP GFI
JOIN IV_Q$GESTAO_PRODUTO_IMPL AVM ON AVM.PROCESSO = GFI.PROCESSO AND AVM.FORMULARIO_NFORMULAR = GFI.FORMULARIO_NUMERO
 LEFT JOIN BI_DTAPROVCREDITO QPROV ON QPROV.PROCESSO = GFI.Processo
WHERE GFI.PROCESSO IN (SELECT PDD.PROCESSO
                      FROM IV_PROCDADO PDD
                      JOIN IV_PROCESSO PRC
                        ON PRC.PROCESSO = PDD.PROCESSO
                     WHERE PDD.CODPROCESSO IN (37)
                       AND PRC.FASEORDEM > 45)

--- FORMULARIO NOVO AMS / CREDITO
UNION ALL

SELECT      DISTINCT
            4 as TIPOFORM,
			GFI.PROCESSO                        as ONE_PROCESSO,
            GFI.FORMA_PAGAMENTO                 AS VDAE_TIPO_FINANCIAMENTO,
            GFI.INSTITUICAO_FIINSTIT            AS VDAE_INST_FINANCEIRA,
            GFI.VALOR_TOTAL                     AS VDAE_VALOR,
            AVM.ITENS_AMS                       AS VDAE_MODELO,
            'John Deere'                        AS VDAE_MARCA,
            'AMS'                               AS VDAE_TIPO_MAQUINA,
            GFI.PROBABILIDADE                   AS VDAE_PROB_APROVACAO,
            CASE WHEN GFI.STATUS_PROCESSO='Autorizado' then 'SIM' else 'NÃO' END 
                                                AS VDAE_PAC_EMITIDO,
            ( SELECT DTALOG FROM GE_LgTb 
                  WHERE tb='IV_QUESTIONARIO' and KN1 = GFI.SEQQUESTIONARIO AND CODAPL = ' IVS1QST01' 
                    AND OBS LIKE '%Status Processo Financ de Em Analise, para Fatur Autorizado%' ) 
                                                AS VDAE_DATA_PAC,
            NULL AS VDAE_DATA_FAT_AUTORIZ,                                                                                                
            CASE WHEN ISNULL(GFI.NOTA_FISCAL, 0)<>0 THEN 'SIM' else 'NÃO' END 
                                                AS VDAE_FATURAMENTO_REALIZADO,
            GFI.FATURAMENTO_REALIZAD      AS VDAE_DATA_FATURAMENTO,
            NULL AS VDAE_DATA_PREVISTA_FATURAMENTO,
            NULL AS VDAE_MES_PREVISTO_FATURAMENTO,
            RIGHT( '0' + CAST ( MONTH( GFI.FATURAMENTO_REALIZAD ) AS VARCHAR(2)), 2) 
                 AS VDAE_MES_FATURAMENTO,            
            NULL AS VDAE_ORIGEM_FATURAMENTO,
            NULL AS VDAE_DIAS_PEDIDO_PAC,
            NULL AS VDAE_DIAS_PEDIDO_FATURAMENTO,
            NULL AS VDAE_DIAS_PAC_FATURAMENTO,
		   QPROV.DTVENDA_AUTORIZADA AS VDAE_DTVENDA_AUTORIZADA , 
		   QPROV.DTVENDA_PAGTO AS VDAE_DTVENDA_PAGTO, 
		   QPROV.DTAPROVACAO_CREDITOTRT AS VDAE_DTAPROVACAO_CREDITOTRT, 
		   QPROV.DTAPROVACAO_CREDITOIMP AS VDAE_DTAPROVACAO_CREDITOIMP, 
		   QPROV.DTAPROVACAO_CREDITOAMS AS VDAE_DTAPROVACAO_CREDITOAMS,

		   INSTITUICAO_FIINSTIT AS INST_SELECIONADA,
		   CASE WHEN INSTITUICAO_FIINSTIT = ANALISE_2 AND 
		             STATUS_ANALISE_BC = 'Aprovado' 
			    THEN DATA_RESPOSTA__1_
				WHEN INSTITUICAO_FIINSTIT = INSTITUICAO_FINANCEI AND 
		             STATUS_BC_2 = 'Aprovado' 
			    THEN DATA_RESPOSTA__2_
				WHEN INSTITUICAO_FIINSTIT = ANALISE_3 AND 
		             ANALISE_BC_3 = 'Aprovado' 
			    THEN DADATA_RESPOSTATA_RE
				END
				AS VDAE_DT_LIBERACAO

FROM IV_Q$GESTAO_CREDITO_AMS GFI
JOIN IV_Q$GESTAO_PRODUTO___AMS AVM ON AVM.PROCESSO = GFI.PROCESSO AND AVM.FORMULARIO_NUMERO = GFI.FORMULARIO_NUMERO
 LEFT JOIN BI_DTAPROVCREDITO QPROV ON QPROV.PROCESSO = GFI.Processo
WHERE GFI.PROCESSO IN (SELECT PDD.PROCESSO
                      FROM IV_PROCDADO PDD
                      JOIN IV_PROCESSO PRC
                        ON PRC.PROCESSO = PDD.PROCESSO
                     WHERE PDD.CODPROCESSO IN (37)
                       AND PRC.FASEORDEM > 45)
