/* ==============================================================
   Objeto ..........: dbo.BI_VENDA_MAQ
   Tipo ............: VIEW
   Criado em .......: 2022-10-27 11:47:20
   Modificado em ...: 2023-03-01 09:57:02
   Linhas ..........: 268
   Escreve em tabela: nao
   Tabelas referidas: GE_LgTb, IV_AGENDA, IV_HISTORICO, IV_PROCDADO, IV_PROCESSO, IV_RESULTADO
   Outras refs .....: IV_Q$ACOMP_VEND_MAQUINAS, IV_Q$ACOMPANH_VENDA_JDE, IV_Q$GESTAO_CREDITO, IV_Q$GESTAO_CREDITO_AMS, IV_Q$GESTAO_CREDITO_IMP, IV_Q$GESTAO_PRODUTO___AMS, IV_Q$GESTAO_PRODUTO_IMPL
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW [dbo].[BI_VENDA_MAQ]  (PROCESSO, VDA_TIPO_FINANCIAMENTO, VDA_INST_FINANCEIRA, VDA_VALOR, VDA_MODELO, VDA_MARCA, 
VDA_CHASSI, VDA_TIPO_MAQUINA, VDA_PROB_APROVACAO, VDA_PAC_EMITIDO, VDA_DATA_PAC, VDA_FATURAMENTO_REALIZADO, VDA_DATA_FATURAMENTO,
VDA_DATA_PREVISTA_FATURAMENTO, VDA_MES_PREVISTO_FATURAMENTO, VDA_ORIGEM_FATURAMENTO, VDA_DIAS_PEDIDO_PAC, VDA_DIAS_PAC_FATURAMENTO, 
data_pedido_de_venda, VDA_DIAS_PEDIDO_FATURAMENTO, APROVACAO_GESTOR, FDD, PREVISAO_ENTREGA,
STATUS_BC1, STATUS_BC2, STATUS_BC3, COTACAO, INFORMACAO_PREPARACA, DATA_ENTREGA, TRANSPORTADORA, PREVISAO_ENTREGA_PRE,
INST_SELECIONADA
) AS
SELECT	XA.PROCESSO,
		XA.VDA_TIPO_FINANCIAMENTO,
		XA.VDA_INST_FINANCEIRA,
		XA.VDA_VALOR,
		XA.VDA_MODELO,
		XA.VDA_MARCA,
		XA.CHASSI,
		XA.VDA_TIPO_MAQUINA,
		XA.VDA_PROB_APROVACAO,
		XA.VDA_PAC_EMITIDO,
		XA.VDA_DATA_PAC,
		XA.VDA_FATURAMENTO_REALIZADO,
		XA.VDA_DATA_FATURAMENTO,
		XA.VDA_DATA_PREVISTA_FATURAMENTO,
		XA.VDA_MES_PREVISTO_FATURAMENTO, 
		XA.VDA_ORIGEM_FATURAMENTO, 
		XA.VDA_DIAS_PEDIDO_PAC, 
		XA.VDA_DIAS_PAC_FATURAMENTO, 
		XA.data_pedido_de_venda, 
		XA.VDA_DIAS_PEDIDO_FATURAMENTO, 
		CASE WHEN ISNULL(XA.APROVACAO_GESTOR, '@')='@' THEN XA.APROVACAO_GESTOR_AGD ELSE XA.APROVACAO_GESTOR END
		AS APROVACAO_GESTOR, 
		XA.FDD, 
		XA.PREVISAO_ENTREGA,
		XA.STATUS_BC1, 
		XA.STATUS_BC2, 
		XA.STATUS_BC3,
		XA.COTACAO, 
		XA.INFORMACAO_PREPARACA, 
		XA.DATA_ENTREGA, 
		XA.TRANSPORTADORA, 
		XA.PREVISAO_ENTREGA_PRE,
		XA.INST_SELECIONADA
FROM
(
----- formulario de marquinas - antigo
SELECT ACV.processo
    ,ACV.TP_PGTO1 AS VDA_TIPO_FINANCIAMENTO
    ,ACV.INSTITUI_FINANCEIRA1 AS VDA_INST_FINANCEIRA
    ,ACV.VLR_TOTAL1 AS VDA_VALOR
    ,ACV.MODEL_EQUIP1 AS VDA_MODELO
    ,ACV.MARCA_1 AS VDA_MARCA
	,ACV.NRO_CHASSI1 AS CHASSI
    ,ACV.TIPO_EQUIP1 AS VDA_TIPO_MAQUINA
    ,case when ACV.PROB_APROV_CRED1 = 'Alta' then '1-Alta'
          when ACV.PROB_APROV_CRED1 = 'Média' then '2-Média'
            else '3-Baixa'
     end AS VDA_PROB_APROVACAO
    ,CASE WHEN ISNULL(ACV.PAC_EMITIDO, GETDATE()) = GETDATE() THEN 'NÃO' ELSE 'SIM' END AS VDA_PAC_EMITIDO
    ,ACV.pac_emitido AS VDA_DATA_PAC
    ,CASE WHEN ISNULL(ACV.FATURAMENTO_REALIZ, GETDATE()) = GETDATE() THEN 'NÃO' ELSE 'SIM' END AS VDA_FATURAMENTO_REALIZADO
    ,ACV.faturamento_realiz AS VDA_DATA_FATURAMENTO
    ,ACV.PREV_FATURAM1 AS VDA_DATA_PREVISTA_FATURAMENTO
    ,RIGHT( CAST ( YEAR( ACV.PREV_FATURAM1 ) AS VARCHAR(4) ), 2)  + '/' + 
     RIGHT( '0' + CAST ( MONTH( ACV.PREV_FATURAM1 ) AS VARCHAR(2)), 2) AS VDA_MES_PREVISTO_FATURAMENTO
    ,ACV.origem_faturamento AS VDA_ORIGEM_FATURAMENTO
    ,DATEADD(DD, DATEDIFF(DD, 0, ACV.pac_emitido - ACV.data_pedido_de_venda ), 0) AS VDA_DIAS_PEDIDO_PAC
	,DATEADD(DD, DATEDIFF(DD, 0, ACV.faturamento_realiz - ACV.pac_emitido ), 0) AS VDA_DIAS_PAC_FATURAMENTO
	,ACV.data_pedido_de_venda
	, case when ACV.faturamento_realiz > ACV.data_pedido_de_venda then
           DATEADD(DD, DATEDIFF(DD, 0, ACV.faturamento_realiz - ACV.data_pedido_de_venda ), 0) end
		   AS VDA_DIAS_PEDIDO_FATURAMENTO
	,HIS.Descricao AS APROVACAO_GESTOR
	,(SELECT Distinct 'Em aberto' FROM IV_AGENDA WHERE PROCESSO = ACV.PROCESSO AND ACAO = 35 AND REALIZADA='N')
	   AS APROVACAO_GESTOR_AGD
	,NULL AS FDD
	,NULL AS PREVISAO_ENTREGA
	,NULL AS STATUS_BC1
	,NULL AS STATUS_BC2
	,NULL AS STATUS_BC3
	,NULL AS COTACAO
	,NULL AS INFORMACAO_PREPARACA
	,NULL AS DATA_ENTREGA
	,NULL AS TRANSPORTADORA
	,NULL AS PREVISAO_ENTREGA_PRE
	,NULL AS INST_SELECIONADA
FROM IV_Q$ACOMPANH_VENDA_JDE ACV
LEFT JOIN (SELECT HH.PROCESSO, RR.DESCRICAO, 
           ROW_NUMBER() OVER (PARTITION BY HH.PROCESSO ORDER BY HH.DTAREALIZACAO DESC ) AS RANK
           FROM IV_HISTORICO HH, IV_RESULTADO RR
		   WHERE HH.ACAOGERADORA = 35 
		     AND RR.RESULTADO = HH.Resultado) HIS ON HIS.PROCESSO = ACV.PROCESSO AND HIS.RANK = 1
WHERE ACV.PROCESSO IN (
SELECT   PDD.PROCESSO
  FROM IV_PROCDADO PDD
  JOIN IV_PROCESSO PRC
    ON PRC.PROCESSO = PDD.PROCESSO
 WHERE PDD.CODPROCESSO IN(  7)
   AND PRC.FASEORDEM < 35
   AND PRC.REALIZADO = 0
)

UNION ALL

----- novo formulario de maquinas / credito
SELECT	GFI.PROCESSO,
		GFI.FORMA_PAGAMENTO			AS VDA_TIPO_FINANCIAMENTO,
		GFI.INSTITUICAO_FIINSTIT	AS VDA_INST_FINANCEIRA,
		GFI.VALOR_TOTAL				AS VDA_VALOR,
		AVM.MODELO_EQUIPAMENTO      AS VDA_MODELO,
		AVM.MARCA      				AS VDA_MARCA,
		AVM.CHASSI					AS CHASSI,
		AVM.TIPO_EQUIPAMENTO		AS VDA_TIPO_MAQUINA,
		GFI.PROBABILIDADE			AS VDA_PROB_APROVACAO,
		CASE WHEN GFI.STATUS_PROCESSO='Autorizado' then 'SIM' else 'NÃO' END AS VDA_PAC_EMITIDO,
		( SELECT DTALOG FROM GE_LgTb 
			WHERE tb='IV_QUESTIONARIO' and KN1 = GFI.SEQQUESTIONARIO AND CODAPL = ' IVS1QST01' 
			  AND OBS LIKE '%Status Processo Financ de Em Analise, para Fatur Autorizado%' ) AS VDA_DATA_PAC,
		CASE WHEN ISNULL(GFI.NOTA_FISCAL, 0)<>0 THEN 'SIM' else 'NÃO' END AS VDA_FATURAMENTO_REALIZADO,
		GFI.FATURAMENTO_REALIZAD 	AS VDA_DATA_FATURAMENTO,
		NULL AS VDA_DATA_PREVISTA_FATURAMENTO,
		NULL AS VDA_MES_PREVISTO_FATURAMENTO,
		NULL AS VDA_ORIGEM_FATURAMENTO,
		NULL AS VDA_DIAS_PEDIDO_PAC,
		NULL AS VDA_DIAS_PAC_FATURAMENTO,
		NULL AS VDA_DIAS_PEDIDO_FATURAMENTO,
		(SELECT MAX(DTAREALIZACAO) 
		 FROM IV_HISTORICO 
		 WHERE PROCESSO = GFI.PROCESSO
		   AND RESULTADO IN ( 1286, 255, 2143, 2176 )) AS data_pedido_de_venda,
	   HIS.Descricao AS APROVACAO_GESTOR,
	   (SELECT Distinct 'Em aberto' FROM IV_AGENDA WHERE PROCESSO = GFI.PROCESSO AND ACAO = 528 AND REALIZADA='N' )
	   AS APROVACAO_GESTOR_AGD,
	   AVM.FDD,
	   AVM.PREVISAO_ENTREGA_PRE,
	   GFI.STATUS_ANALISE_BC AS STATUS_BC1,
	   GFI.STATUS_BC_2		 AS STATUS_BC2,
	   GFI.ANALISE_BC_3		 AS STATUS_BC3,
	   
	   AVM.COTACAO				AS COTACAO,
	   AVM.INFORMACAO_PREPARACA AS INFORMACAO_PREPARACA,
	   AVM.DATA_ENTREGA			AS DATA_ENTREGA,
	   AVM.TRANSPORTADORA		AS TRANSPORTADORA,
	   AVM.PREVISAO_ENTREGA_PRE AS PREVISAO_ENTREGA_PRE,
	   GFI.INSTITUICAO_FIINSTIT AS INST_SELECIONADA

FROM IV_Q$GESTAO_CREDITO GFI
JOIN IV_Q$ACOMP_VEND_MAQUINAS AVM ON AVM.PROCESSO = GFI.PROCESSO AND AVM.FORMULARIO_NUMERO = GFI.FORMULARIO_NUMERO
LEFT JOIN (SELECT HH.PROCESSO, RR.DESCRICAO, 
           ROW_NUMBER() OVER (PARTITION BY HH.PROCESSO ORDER BY HH.DTAREALIZACAO DESC ) AS RANK
           FROM IV_HISTORICO HH, IV_RESULTADO RR
		   WHERE HH.ACAOGERADORA = 528
		     AND RR.RESULTADO = HH.Resultado) HIS ON HIS.PROCESSO = GFI.PROCESSO AND HIS.RANK = 1
UNION ALL

---- NOVO FORMULARIO DE IMPLEMENTOS/CREDITO
SELECT	GFI.PROCESSO,
		GFI.FORMA_PAGAMENTO			AS VDA_TIPO_FINANCIAMENTO,
		GFI.INSTITUICAO_FIINSTIT	AS VDA_INST_FINANCEIRA,
		GFI.VALOR_TOTAL				AS VDA_VALOR,
		AVM.MODELO_IMPLEMENTO       AS VDA_MODELO,
		AVM.MARCA      				AS VDA_MARCA,
		AVM.CHASSI					AS CHASSI,
		AVM.TIPO_EQUIPAMENTO		AS VDA_TIPO_MAQUINA,
		GFI.PROBABILIDADE			AS VDA_PROB_APROVACAO,
		CASE WHEN GFI.STATUS_PROCESSO='Autorizado' then 'SIM' else 'NÃO' END AS VDA_PAC_EMITIDO,
		( SELECT DTALOG FROM GE_LgTb 
			WHERE tb='IV_QUESTIONARIO' and KN1 = GFI.SEQQUESTIONARIO AND CODAPL = ' IVS1QST01' 
			  AND OBS LIKE '%Status Processo Financ de Em Analise, para Fatur Autorizado%' ) AS VDA_DATA_PAC,
		CASE WHEN ISNULL(GFI.NOTA_FISCAL, 0)<>0 THEN 'SIM' else 'NÃO' END AS VDA_FATURAMENTO_REALIZADO,
		GFI.FATURAMENTO_REALIZAD 	AS VDA_DATA_FATURAMENTO,
		NULL AS VDA_DATA_PREVISTA_FATURAMENTO,
		NULL AS VDA_MES_PREVISTO_FATURAMENTO,
		NULL AS VDA_ORIGEM_FATURAMENTO,
		NULL AS VDA_DIAS_PEDIDO_PAC,
		NULL AS VDA_DIAS_PAC_FATURAMENTO,
		NULL AS VDA_DIAS_PEDIDO_FATURAMENTO,
		(SELECT MAX(DTAREALIZACAO) 
		 FROM IV_HISTORICO 
		 WHERE PROCESSO = GFI.PROCESSO
		   AND RESULTADO IN ( 1286, 255, 2143, 2176 )) AS data_pedido_de_venda,
	   HIS.Descricao AS APROVACAO_GESTOR,
	   (SELECT Distinct 'Em aberto' FROM IV_AGENDA WHERE PROCESSO = GFI.PROCESSO AND ACAO = 528 AND REALIZADA='N' )
	   AS APROVACAO_GESTOR_AGD,
	   NULL AS FDD,
	   NULL AS PREVISAO_ENTREGA_PRE,
	   GFI.STATUS_ANALISE_BC AS STATUS_BC1,
	   GFI.STATUS_BC_2		 AS STATUS_BC2,
	   GFI.ANALISE_BC_3		 AS STATUS_BC3,

	   NULL						AS COTACAO,
	   AVM.INFORMACAO_PREPARACA AS INFORMACAO_PREPARACA,
	   AVM.DATA_ENTREGA			AS DATA_ENTREGA,
	   AVM.TRANSPORTADORA		AS TRANSPORTADORA,
	   AVM.PREVISAO_ENTREGA_PRE AS PREVISAO_ENTREGA_PRE,
	   GFI.INSTITUICAO_FIINSTIT AS INST_SELECIONADA

FROM IV_Q$GESTAO_CREDITO_IMP GFI
JOIN IV_Q$GESTAO_PRODUTO_IMPL AVM ON AVM.PROCESSO = GFI.PROCESSO AND AVM.FORMULARIO_NFORMULAR = GFI.FORMULARIO_NUMERO
LEFT JOIN (SELECT HH.PROCESSO, RR.DESCRICAO, 
           ROW_NUMBER() OVER (PARTITION BY HH.PROCESSO ORDER BY HH.DTAREALIZACAO DESC ) AS RANK
           FROM IV_HISTORICO HH, IV_RESULTADO RR
		   WHERE HH.ACAOGERADORA = 528
		     AND RR.RESULTADO = HH.Resultado) HIS ON HIS.PROCESSO = GFI.PROCESSO AND HIS.RANK = 1

UNION ALL
---- NOVO FORMULARIO DE AMS/CREDITO

SELECT	GFI.PROCESSO,
		GFI.FORMA_PAGAMENTO			AS VDA_TIPO_FINANCIAMENTO,
		GFI.INSTITUICAO_FIINSTIT	AS VDA_INST_FINANCEIRA,
		GFI.VALOR_TOTAL				AS VDA_VALOR,
		AVM.ITENS_AMS		        AS VDA_MODELO,
		'John Deere'      			AS VDA_MARCA,
		CASE WHEN ISNULL( AVM.CHASSI_AMS___1, '')='' THEN '' ELSE AVM.CHASSI_AMS___1 + ' || ' END  + 
		CASE WHEN ISNULL( AVM.CHASSI_AMS___2, '')='' THEN '' ELSE AVM.CHASSI_AMS___2 + ' || ' END  + 
		CASE WHEN ISNULL( AVM.CHASSI_AMS___3, '')='' THEN '' ELSE AVM.CHASSI_AMS___3 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___4, '')='' THEN '' ELSE AVM.CHASSI_AMS___4 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___5, '')='' THEN '' ELSE AVM.CHASSI_AMS___5 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___6, '')='' THEN '' ELSE AVM.CHASSI_AMS___6 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___7, '')='' THEN '' ELSE AVM.CHASSI_AMS___7 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___8, '')='' THEN '' ELSE AVM.CHASSI_AMS___8 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___9, '')='' THEN '' ELSE AVM.CHASSI_AMS___9 + ' || ' END  +
		CASE WHEN ISNULL( AVM.CHASSI_AMS___10, '')='' THEN '' ELSE AVM.CHASSI_AMS___10 + ' || ' END  
		AS CHASSI,
		'AMS'		AS VDA_TIPO_MAQUINA,
		GFI.PROBABILIDADE			AS VDA_PROB_APROVACAO,
		CASE WHEN GFI.STATUS_PROCESSO='Autorizado' then 'SIM' else 'NÃO' END AS VDA_PAC_EMITIDO,
		( SELECT DTALOG FROM GE_LgTb 
			WHERE tb='IV_QUESTIONARIO' and KN1 = GFI.SEQQUESTIONARIO AND CODAPL = ' IVS1QST01' 
			  AND OBS LIKE '%Status Processo Financ de Em Analise, para Fatur Autorizado%' ) AS VDA_DATA_PAC,
		CASE WHEN ISNULL(GFI.NOTA_FISCAL, 0)<>0 THEN 'SIM' else 'NÃO' END AS VDA_FATURAMENTO_REALIZADO,
		GFI.FATURAMENTO_REALIZAD 	AS VDA_DATA_FATURAMENTO,
		NULL AS VDA_DATA_PREVISTA_FATURAMENTO,
		NULL AS VDA_MES_PREVISTO_FATURAMENTO,
		NULL AS VDA_ORIGEM_FATURAMENTO,
		NULL AS VDA_DIAS_PEDIDO_PAC,
		NULL AS VDA_DIAS_PAC_FATURAMENTO,
		NULL AS VDA_DIAS_PEDIDO_FATURAMENTO,
		(SELECT MAX(DTAREALIZACAO) 
		 FROM IV_HISTORICO 
		 WHERE PROCESSO = GFI.PROCESSO
		   AND RESULTADO IN ( 1286, 255, 2143, 2176 )) AS data_pedido_de_venda,
	   HIS.Descricao AS APROVACAO_GESTOR,
	   (SELECT Distinct 'Em aberto' FROM IV_AGENDA WHERE PROCESSO = GFI.PROCESSO AND ACAO = 528 AND REALIZADA='N' )
	   AS APROVACAO_GESTOR_AGD,
	   NULL AS FDD,
	   NULL AS PREVISAO_ENTREGA_PRE,
	   GFI.STATUS_ANALISE_BC AS STATUS_BC1,
	   GFI.STATUS_BC_2		 AS STATUS_BC2,
	   GFI.ANALISE_BC_3		 AS STATUS_BC3,

	   NULL					AS COTACAO,
	   NULL				 AS INFORMACAO_PREPARACA,
	   AVM.DATA_ENTREGA			AS DATA_ENTREGA,
	   AVM.TRANSPORTADORA		AS TRANSPORTADORA,
	   AVM.PREVISAO_ENTREGA_PRE AS PREVISAO_ENTREGA_PRE,
	   GFI.INSTITUICAO_FIINSTIT AS INST_SELECIONADA

FROM IV_Q$GESTAO_CREDITO_AMS GFI
JOIN IV_Q$GESTAO_PRODUTO___AMS AVM ON AVM.PROCESSO = GFI.PROCESSO AND AVM.FORMULARIO_NUMERO = GFI.FORMULARIO_NUMERO
LEFT JOIN (SELECT HH.PROCESSO, RR.DESCRICAO, 
           ROW_NUMBER() OVER (PARTITION BY HH.PROCESSO ORDER BY HH.DTAREALIZACAO DESC ) AS RANK
           FROM IV_HISTORICO HH, IV_RESULTADO RR
		   WHERE HH.ACAOGERADORA = 528
		     AND RR.RESULTADO = HH.Resultado) HIS ON HIS.PROCESSO = GFI.PROCESSO AND HIS.RANK = 1

) XA


