/* ==============================================================
   Objeto ..........: dbo.GE$OBJDINAMICO
   Tipo ............: VIEW
   Criado em .......: 2025-02-17 17:35:38
   Modificado em ...: 2025-02-17 17:35:38
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_OBJDINAMICO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

     CREATE   VIEW GE$OBJDINAMICO (  SEQOBJDYN, VF, DESCRICAO, USO, TIPO,          USOJUNCAOPESSOA, USOPESSOA, USOPROCESSO, USOAGENDA, USOHISTORICO,          USOACAO, USORESULTADO, USOREQRESULTADO , USORESULTADOCMPL, USOWORKFLOW,         DESCRICAOOBJ		) AS  SELECT  SEQOBJDYN, 1 AS VF, DESCRICAO, USO,   TIPO,        OBJ.USOJUNCAOPESSOA, OBJ.USOPESSOA, OBJ.USOPROCESSO,        OBJ.USOAGENDA, OBJ.USOHISTORICO, OBJ.USOACAO, OBJ.USORESULTADO , 	   OBJ.USOREQRESULTADO , OBJ.USORESULTADOCMPL, OBJ.USOWORKFLOW , 	   DESCRICAO FROM GE_OBJDINAMICO OBJ WHERE OBJ.TIPO != 'TESTE' UNION SELECT  SEQOBJDYN, 1 AS VF, MENSVERDADEIRO, USO,  TIPO,        OBJ.USOJUNCAOPESSOA, OBJ.USOPESSOA, OBJ.USOPROCESSO,        OBJ.USOAGENDA, OBJ.USOHISTORICO, OBJ.USOACAO, OBJ.USORESULTADO , 	   OBJ.USOREQRESULTADO , OBJ.USORESULTADOCMPL, OBJ.USOWORKFLOW, 	   OBJ.DESCRICAO	    FROM GE_OBJDINAMICO OBJ WHERE OBJ.TIPO = 'TESTE' AND MENSVERDADEIRO IS NOT NULL UNION SELECT SEQOBJDYN, 0 AS VF, MENSFALSO, USO,  TIPO,        OBJ.USOJUNCAOPESSOA, OBJ.USOPESSOA, OBJ.USOPROCESSO,        OBJ.USOAGENDA, OBJ.USOHISTORICO, OBJ.USOACAO, OBJ.USORESULTADO , 	   OBJ.USOREQRESULTADO , OBJ.USORESULTADOCMPL, OBJ.USOWORKFLOW , 	   OBJ.DESCRICAO	    FROM GE_OBJDINAMICO OBJ WHERE OBJ.TIPO = 'TESTE' AND MENSFALSO IS NOT NULL    