/* ==============================================================
   Objeto ..........: dbo.IV$ATIVREQUISITO
   Tipo ............: VIEW
   Criado em .......: 2017-04-19 09:12:50
   Modificado em ...: 2017-04-19 09:12:50
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: DMN_DOCTP, IV_FORMULARIO
   Outras refs .....: GE$OBJDINAMICO, IV_ATIVVINC
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE  VIEW IV$ATIVREQUISITO  (GRUPOVINC, BASE, DESCRICAO, VINCULO, SEQVINC, NROVINC, CODVINC, SEQPLANOATIV)  AS  SELECT ATVV.GRUPOVINC,         ' Formulário: ' AS BASE,         FRM.OBJETIVO,         ATVV.VINCULO, ATVV.SEQVINC, ATVV.NROVINC, ATVV.CODVINC, ATVV.SEQPLANOATIV  FROM IV_ATIVVINC ATVV       JOIN IV_FORMULARIO FRM ON  FRM.SEQFORMULARIO = ATVV.NROVINC  WHERE ATVV.VINCULO = 'FORM'  UNION  SELECT ATVV.GRUPOVINC,         ' Documento: ' AS BASE,         DT.DESCR,         ATVV.VINCULO, ATVV.SEQVINC, ATVV.NROVINC, ATVV.CODVINC, ATVV.SEQPLANOATIV  FROM IV_ATIVVINC ATVV       JOIN DMN_DOCTP DT ON DT.SEQDOCTP = ATVV.NROVINC  WHERE ATVV.VINCULO = 'DMNG'  UNION  SELECT ATVV.GRUPOVINC,         ' Objeto dinâmico: ' AS BASE,         OBDY.DESCRICAO,         ATVV.VINCULO, ATVV.SEQVINC, ATVV.NROVINC, ATVV.CODVINC, ATVV.SEQPLANOATIV  FROM IV_ATIVVINC ATVV       JOIN GE$OBJDINAMICO OBDY ON OBDY.SEQOBJDYN = ATVV.NROVINC  WHERE ATVV.VINCULO = 'OBDY'     AND ATVV.EXIGIDO =  OBDY.VF