/* ==============================================================
   Objeto ..........: dbo.IV$HISTORICO
   Tipo ............: VIEW
   Criado em .......: 2025-02-17 17:35:38
   Modificado em ...: 2025-02-17 17:35:38
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: IV_HISTORICO, IV_PROCDADO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

  Create view IV$HISTORICO (           SEQHISTORICO, SEQPESSOA, CONTATO,          NROEMPRESA, CODUSUARIO, ACAOGERADORA,         RESULTADO, RESULTADOCMPL, AGENDAORIGEM,          DTAREALIZACAO, DETALHE, NATUREZA,          VENDEDOR_HIST, ULTALTERACAO, USUALTERACAO,          DEPARTAMENTO, PROCESSO, CODPROCESSO, PROCESSOPAI, PROCESSODNA,         VALOR, QTDE, TEMCIENCIA, VENDEDOR, FORMAPRIMCONT, DURACAO,         ATIVORECEPTIVO, MOTIVO, CAMPANHA, ULTRESULTADO, DTAULTRESULTADO,          ULTRESULTADOCMPL, DTAPRIMRESULTADO)   AS    SELECT  HT.SEQHISTORICO   , HT.SEQPESSOA     , HT.CONTATO ,         HT.NROEMPRESA     , HT.CODUSUARIO    , HT.ACAOGERADORA   ,          HT.RESULTADO      ,HT.RESULTADOCMPL  , HT.AGENDAORIGEM   ,         HT.DTAREALIZACAO  , HT.DETALHE       , HT.NATUREZA       ,          HT.VENDEDOR  ,    HT.ULTALTERACAO   ,  HT.USUALTERACAO   ,          HT.DEPARTAMENTO   , HT.PROCESSO  ,   HT.CODPROCESSO    , PD.PROCESSOPAI    , PD.PROCESSODNA,         HT.VALOR     ,     HT.QTDE    , HT.TEMCIENCIA,  PD.VENDEDOR , PD.FORMAPRIMCONT , HT.DURACAO,         PD.ATIVORECEPTIVO, PD.MOTIVO,  PD.CAMPANHA, PD.ULTRESULTADO, PD.DTAULTRESULTADO,          PD.RESULTADOCMPL,   PD.DTAPRIMRESULTADO  FROM IV_HISTORICO HT      JOIN IV_PROCDADO PD ON PD.PROCESSO = HT.PROCESSO  