/* ==============================================================
   Objeto ..........: dbo.IV$PROCESSO
   Tipo ............: VIEW
   Criado em .......: 2025-02-17 17:46:04
   Modificado em ...: 2025-02-17 17:46:04
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: IV_CODPROCESSO, IV_PROCDADO, IV_PROCESSO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

 Create view IV$PROCESSO(  PROCESSO, NROEMPRESA, SEQPESSOA, CODPROCESSO, PROCESSOPAI,         PROCESSODNA, RESUMO, DESCRICAO, USURESPONSAVEL, USUINCLUSAO,         DTAINCLUSAO, USUALTERACAO, DTAALTERACAO, REALIZADO, DTAREALIZACAO,         STATUS, PERSPECTIVA, FASE, FASEORDEM, DTAPREVCONCLUSAO,          VALOR, QTDE, VENDEDOR, FORMAPRIMCONT, ATIVORECEPTIVO,         MOTIVO, CAMPANHA, ULTRESULTADO, DTAULTRESULTADO, RESULTADOCMPL,          DTAPRIMRESULTADO ,         STATUSDESC, 	TIPOPROCESSO, 	MODELOPROCESSO, 	MODELODESCRICAO )   AS  SELECT PD.PROCESSO, PD.NROEMPRESA, PD.SEQPESSOA, PD.CODPROCESSO,        PD.PROCESSOPAI,  PD.PROCESSODNA ,  PRC.RESUMO , PRC.DESCRICAO,        PRC.USURESPONSAVEL , PRC.USUINCLUSAO , PRC.DTAINCLUSAO , PRC.USUALTERACAO,        PRC.DTAALTERACAO , PRC.REALIZADO , PRC.DTAREALIZACAO  , PRC.STATUS,        PRC.PERSPECTIVA   ,PRC.FASE  ,PRC.FASEORDEM ,  PRC.DTAPREVCONCLUSAO,        PRC.VALOR   ,  PRC.QTDE ,        PD.VENDEDOR , PD.FORMAPRIMCONT , PD.ATIVORECEPTIVO, PD.MOTIVO,        PD.CAMPANHA, PD.ULTRESULTADO, PD.DTAULTRESULTADO, PD.RESULTADOCMPL,        PD.DTAPRIMRESULTADO  ,        PRC.STATUSDESC,        CODP.TIPOPROCESSO AS TIPOPROCESSO,        CODP.DESCRRED AS MODELOPROCESSO,        CODP.DESCRICAO AS MODELODESCRICAO FROM IV_PROCDADO PD      LEFT JOIN IV_PROCESSO PRC ON PRC.PROCESSO = PD.PROCESSO      LEFT JOIN IV_CODPROCESSO CODP ON CODP.CODPROCESSO = PD.CODPROCESSO  