/* ==============================================================
   Objeto ..........: dbo.IV$S_HISTORICO
   Tipo ............: VIEW
   Criado em .......: 2025-02-17 17:35:38
   Modificado em ...: 2025-02-17 17:35:38
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: IV_ACAO, IV_HISTORICO, IV_PROCDADO, IV_PROCPRODUTO, IV_RESULTADO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

     CREATE VIEW IV$S_HISTORICO( SEQPESSOA, CONTATO, NROEMPRESA, ATENDENTE,         ACAO_GERADORA, COD_ACAO_GERADORA, COD_RESULTADO, RESULTADO, RESULTADOCMPL, AGENDAORIGEM,          DTAREALIZACAO, DETALHE, NATUREZA, VENDEDOR_HIST, ULTALTERACAO,          USUALTERACAO, DEPARTAMENTO, CODPROCESSO, PROCESSO,          VALOR, QTDE, VENDEDOR, DURACAO, FORMA_PRIM_CONTATO,         ULTRESULTADO, DTAULTRESULTADO, ULTRESULTADOCMPL,         DTAPRIMRESULTADO, VENDEDOR_PROCESSO,         COD_PRODUTO, QTDE_PROD, VALOR_PROD,         CAMPANHA, ORIGEM, MOTIVO )   AS    SELECT HI.SEQPESSOA, HI.CONTATO, HI.NROEMPRESA,        HI.CODUSUARIO,         isnull(AC.DESCRICAO, '* Receptivo *') AS ACAO_GERADORA  , HI.ACAOGERADORA,        HI.RESULTADO AS COD_RESULTADO,          isnull(AC.DESCREDUZIDA, '* RECEP *') ++ '/' ++ RE.DESCREDUZIDA ++ '-' ++ CONVERT(VARCHAR,HI.RESULTADO) AS RESULTADO,         HI.RESULTADOCMPL, HI.AGENDAORIGEM, HI.DTAREALIZACAO,         HI.DETALHE,         HI.NATUREZA, HI.VENDEDOR, HI.ULTALTERACAO,         HI.USUALTERACAO, HI.DEPARTAMENTO,   HI.CODPROCESSO, HI.PROCESSO,        HI.VALOR, HI.QTDE, HI.VENDEDOR, HI.DURACAO,        PR.FORMAPRIMCONT as FORMA_PRIM_CONTATO,        PR.ULTRESULTADO, PR.DTAULTRESULTADO, PR.RESULTADOCMPL,        PR.DTAPRIMRESULTADO, PR.VENDEDOR,        PP.CODPRODUTO, PP.QTDE, PP.VALOR,        PR.CAMPANHA , PR.MOTIVO, PR.MOTIVO FROM IV_HISTORICO  HI      JOIN IV_RESULTADO RE               LEFT JOIN IV_ACAO AC ON AC.ACAO = RE.ACAO           ON RE.RESULTADO = HI.RESULTADO       LEFT JOIN IV_PROCPRODUTO PP ON PP.PROCESSO = HI.PROCESSO       LEFT JOIN IV_PROCDADO    PR ON PR.PROCESSO = HI.PROCESSO   