/* ==============================================================
   Objeto ..........: dbo.IV$S_CONTATO
   Tipo ............: VIEW
   Criado em .......: 2025-02-17 17:35:38
   Modificado em ...: 2025-02-17 17:35:38
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_CONTATO, GE_CONTATOPAPEL
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

 CREATE VIEW IV$S_CONTATO (SEQPESSOA, SEQ_PESSOA,  EMUSO,        TIPOCONTATO, AREAATUACAO,        RG, CPF, DIGCPF,         SAUDACAO, CONTATO,         FONEDDD1, FONENRO1, FONECMPL1,        FONEDDD2, FONENRO2, FONECMPL2,        FAXDDD, FAXNRO,        SEXO, ESTADOCIVIL,        DTANASCIMENTO,        ATRIBUTO1, ATRIBUTO2, ATRIBUTO3,        ATRIBDTA, ATRIBNUM,        EMAIL, OBSERVACAO, LINKWEB,        PAPEL, DIA_NASC, MES_NASC, ANO_NASC)  AS    SELECT CTT.SEQPESSOA, CTT.SEQPESSOA, CASE CTT.EMUSO WHEN 1 THEN 'SIM' ELSE 'NÃO' END  AS EMUSO,        CTT.TIPOCONTATO, CTT.AREAATUACAO,        CTT.RG, CTT.CPF, CTT.DIGCPF,         CTT.SAUDACAO, CTT.CONTATO,         CTT.FONEDDD1, CTT.FONENRO1, CTT.FONECMPL1,        CTT.FONEDDD2, CTT.FONENRO2, CTT.FONECMPL2,        CTT.FAXDDD, CTT.FAXNRO,               CTT.SEXO,        CASE CTT.ESTADOCIVIL              WHEN 'C' THEN 'CASADO'             WHEN 'S' THEN 'SOLTEIRO'             WHEN 'D' THEN 'DIVORCIADO'             WHEN 'Q' THEN 'DESQUITADO'             WHEN 'V' THEN 'VIÚVO'               ELSE 'NÃO INFORMADO'             END   AS ESTADO_CIVIL,         CTT.DTANASCIMENTO,        CTT.ATRIBUTO1, CTT.ATRIBUTO2, CTT.ATRIBUTO3,        CTT.ATRIBDTA, CTT.ATRIBNUM,        CTT.EMAIL, CTT.OBSERVACAO, CTT.LINKWEB,        CTP.PAPEL,        DAY(CTT.DTANASCIMENTO) AS DIA_NASC,        MONTH(CTT.DTANASCIMENTO) AS MES_NASC,        YEAR(CTT.DTANASCIMENTO) AS ANO_NASC    FROM GE_CONTATO CTT  LEFT JOIN GE_CONTATOPAPEL CTP ON CTP.SEQPESSOA = CTT.SEQPESSOA        AND CTP.SEQCONTATO = CTT.SEQCONTATO    