/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_SERVICOS
   Tipo ............: VIEW
   Criado em .......: 2015-02-14 11:04:49
   Modificado em ...: 2016-03-22 19:20:04
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_SERVICOS, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_SERVICOS ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , Q001_INSATISFEITO, Q001_INDIFERENTE, Q001_SATISFEITO, Q004_0, Q004_1, Q004_2, Q004_3, Q004_4, Q004_5, Q004_6, Q004_7, Q004_8, Q004_9, Q004_10, RECOMEND_DEPTO_SERVI)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.Q001_INSATISFEITO, TABF.Q001_INDIFERENTE, TABF.Q001_SATISFEITO, TABF.Q004_0, TABF.Q004_1, TABF.Q004_2, TABF.Q004_3, TABF.Q004_4, TABF.Q004_5, TABF.Q004_6, TABF.Q004_7, TABF.Q004_8, TABF.Q004_9, TABF.Q004_10, TABF.RECOMEND_DEPTO_SERVI    FROM IV_Q_AFERICAO_SERVICOS TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 