/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA
   Tipo ............: VIEW
   Criado em .......: 2022-06-07 16:32:32
   Modificado em ...: 2022-06-07 16:32:32
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA_VP, REVENDA, MODELO_VP, DATA_DA_VENDA, QUANTIDADE, PRECO_CONCORRENTE, PRECO_JOHN_DEERE, MODELO_JOHN_DEER, MOTIVO, TIPO_DE_EQUIPAMENTO, PARTICIPAMOS_DA_NEGO, HAVIA_MONITORAMENTO, MODELO_IMPLEMENTO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA_VP, TABF.REVENDA, TABF.MODELO_VP, TABF.DATA_DA_VENDA, TABF.QUANTIDADE, TABF.PRECO_CONCORRENTE, TABF.PRECO_JOHN_DEERE, TABF.MODELO_JOHN_DEER, TABF.MOTIVO, TABF.TIPO_DE_EQUIPAMENTO, TABF.PARTICIPAMOS_DA_NEGO, TABF.HAVIA_MONITORAMENTO, TABF.MODELO_IMPLEMENTO    FROM IV_Q_VENDA_PERDIDA TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 