/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_SERVICOS_AMS
   Tipo ............: VIEW
   Criado em .......: 2017-12-21 11:28:39
   Modificado em ...: 2017-12-21 11:28:39
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_SERVICOS_AMS, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_SERVICOS_AMS ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , NUMERO_PEDIDO, VALOR_DA_VENDA, FORMA_DE_PAGAMENTO, SERVICO_VENDIDO, DESCRICAO_DO_SERVICO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.NUMERO_PEDIDO, TABF.VALOR_DA_VENDA, TABF.FORMA_DE_PAGAMENTO, TABF.SERVICO_VENDIDO, TABF.DESCRICAO_DO_SERVICO    FROM IV_Q_VENDA_SERVICOS_AMS TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 