/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_IMPLEMENTO
   Tipo ............: VIEW
   Criado em .......: 2020-08-27 13:17:16
   Modificado em ...: 2020-08-27 13:17:16
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_IMPLEMENTO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_IMPLEMENTO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFEITO_ATENDIMEN, A_AREA_COMERCIAL_ATE, COMBINADO_CUMPRIDO, ORIENTOU_EQUIPAMENTO, CONSULTAR_CONTATO, PROCESSO_FINANCEIRO, PRAZO_ENTREGA, ENTREGA_REALIZAD, FICOU_SATISFEITO, UTILIZOU_PRODUTO, DESEMPENHO, NPS_0_10)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFEITO_ATENDIMEN, TABF.A_AREA_COMERCIAL_ATE, TABF.COMBINADO_CUMPRIDO, TABF.ORIENTOU_EQUIPAMENTO, TABF.CONSULTAR_CONTATO, TABF.PROCESSO_FINANCEIRO, TABF.PRAZO_ENTREGA, TABF.ENTREGA_REALIZAD, TABF.FICOU_SATISFEITO, TABF.UTILIZOU_PRODUTO, TABF.DESEMPENHO, TABF.NPS_0_10    FROM IV_Q_AFERICAO_IMPLEMENTO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 