/* ==============================================================
   Objeto ..........: dbo.IV_Q$SERVICOS_AFERICAO
   Tipo ............: VIEW
   Criado em .......: 2020-05-22 11:05:29
   Modificado em ...: 2020-05-22 11:05:29
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_SERVICOS_AFERICAO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$SERVICOS_AFERICAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFACAO_EM_RELACA, QUAL_SETOR_HA_OPORTU, SATIS_EM_RELACA, RECOMENDACAO_A_COLOR, SER_REALIZADOS, AQUILO_QUE_FOI_ACORD, ATEND_TEC_EXPECTATIV, NOTA_SATISFACAO, O_SR__INDICA_UM_AMIG, QUAL_COLABORADOR_DE_, QUESTAO_TEC, PRAZO_AGENDADOS, ACORDADO_CUMPRIDO, TECNICO_ATENDEU, SERV_EXECUTADO, TEVE_RETORNAR, QUE_NOTA_O_A__SR__A_)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFACAO_EM_RELACA, TABF.QUAL_SETOR_HA_OPORTU, TABF.SATIS_EM_RELACA, TABF.RECOMENDACAO_A_COLOR, TABF.SER_REALIZADOS, TABF.AQUILO_QUE_FOI_ACORD, TABF.ATEND_TEC_EXPECTATIV, TABF.NOTA_SATISFACAO, TABF.O_SR__INDICA_UM_AMIG, TABF.QUAL_COLABORADOR_DE_, TABF.QUESTAO_TEC, TABF.PRAZO_AGENDADOS, TABF.ACORDADO_CUMPRIDO, TABF.TECNICO_ATENDEU, TABF.SERV_EXECUTADO, TABF.TEVE_RETORNAR, TABF.QUE_NOTA_O_A__SR__A_    FROM IV_Q_SERVICOS_AFERICAO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 