/* ==============================================================
   Objeto ..........: dbo.IV_Q$CONDICOES_DE_VENDAS
   Tipo ............: VIEW
   Criado em .......: 2025-08-07 09:29:51
   Modificado em ...: 2025-08-07 09:29:51
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_CONDICOES_DE_VENDAS, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$CONDICOES_DE_VENDAS ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , COND_TIPO_EQUIP, COND_MARCA_EQUIP, COND_MODELO_EQUIP, COND_QUANTIDADE, COND_CONFIGURACAO, COND_PRECO, COND_BONIFICACAO, COND_COND_PAGTO, COND_COMISSAO, COND_PRAZO_ENTREGA)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.COND_TIPO_EQUIP, TABF.COND_MARCA_EQUIP, TABF.COND_MODELO_EQUIP, TABF.COND_QUANTIDADE, TABF.COND_CONFIGURACAO, TABF.COND_PRECO, TABF.COND_BONIFICACAO, TABF.COND_COND_PAGTO, TABF.COND_COMISSAO, TABF.COND_PRAZO_ENTREGA   FROM IV_Q_CONDICOES_DE_VENDAS TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  