/* ==============================================================
   Objeto ..........: dbo.IV_Q$COMPETID_NEGOC_IMPL
   Tipo ............: VIEW
   Criado em .......: 2013-10-08 13:59:35
   Modificado em ...: 2016-03-22 19:20:06
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COMPETID_NEGOC_IMPL, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COMPETID_NEGOC_IMPL ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA_IMPL, REVENDA_CONC, MOD_IMPLEMENTO, QTDE_IMPL, PRECO_CONCORR, COND_PGTO_CONCORR, COND_PGTO_JD, COMPETID_NEGOC)     AS SELECT PES.SEQPESSOA, PES.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA_IMPL, TABF.REVENDA_CONC, TABF.MOD_IMPLEMENTO, TABF.QTDE_IMPL, TABF.PRECO_CONCORR, TABF.COND_PGTO_CONCORR, TABF.COND_PGTO_JD, TABF.COMPETID_NEGOC    FROM  IV_Q_COMPETID_NEGOC_IMPL TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA PES ON PES.SEQPESSOA = QST.SEQPESSOA 