/* ==============================================================
   Objeto ..........: dbo.IV_Q$TICKET_DSI
   Tipo ............: VIEW
   Criado em .......: 2025-01-21 15:05:42
   Modificado em ...: 2025-01-21 15:05:42
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_TICKET_DSI, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$TICKET_DSI ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , NOME_DO_CLIENTE, ORGANIZACAO_OPERATIO, TITULO, RESUMO_DO_PROBLEMA, PRODUTO, CHASSI, CONTATO_DO_CLIENTE)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.NOME_DO_CLIENTE, TABF.ORGANIZACAO_OPERATIO, TABF.TITULO, TABF.RESUMO_DO_PROBLEMA, TABF.PRODUTO, TABF.CHASSI, TABF.CONTATO_DO_CLIENTE   FROM IV_Q_TICKET_DSI TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  