/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_SEMINOVO
   Tipo ............: VIEW
   Criado em .......: 2025-08-27 16:08:01
   Modificado em ...: 2025-08-27 16:08:01
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_SEMINOVO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_SEMINOVO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SMNV_TIPO_VENDA, SMNV_TIPO_EQUIPAMENT, SMNV_MARCA, SMNV_MODELO, SMNV_POTENCIA, SMNV_ANO_FABRICACAO, SMNV_HORAS_KMS, SMNV_VALOR_AVALIADO, SMNV_CHASSI)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SMNV_TIPO_VENDA, TABF.SMNV_TIPO_EQUIPAMENT, TABF.SMNV_MARCA, TABF.SMNV_MODELO, TABF.SMNV_POTENCIA, TABF.SMNV_ANO_FABRICACAO, TABF.SMNV_HORAS_KMS, TABF.SMNV_VALOR_AVALIADO, TABF.SMNV_CHASSI   FROM IV_Q_VENDA_SEMINOVO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  