/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_IMPL
   Tipo ............: VIEW
   Criado em .......: 2015-05-28 10:55:38
   Modificado em ...: 2016-03-22 19:20:04
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_IMPL, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_IMPL ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA_VP, REVENDA, MODELO_VP, DATA_DA_VENDA, QUANTIDADE, PRECO_CONCORRENTE, PRECO_JOHN_DEERE, MODELO_JOHN_DEER, MOTIVO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA_VP, TABF.REVENDA, TABF.MODELO_VP, TABF.DATA_DA_VENDA, TABF.QUANTIDADE, TABF.PRECO_CONCORRENTE, TABF.PRECO_JOHN_DEERE, TABF.MODELO_JOHN_DEER, TABF.MOTIVO    FROM IV_Q_VENDA_PERDIDA_IMPL TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 