/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_PROD
   Tipo ............: VIEW
   Criado em .......: 2022-11-25 10:55:30
   Modificado em ...: 2022-11-25 10:55:30
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_PROD, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_PROD ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA, REVENDA, MODELO, DATA_DA_VENDA, QUANTIDADE, PRECO_CONCORRENTE, MODELO_JOHN_DEERE, PRECO_JOHN_DEERE, MOTIVA, TIPO_EQUIPAMENTO, PARTICIPAMOS_DA_NEGO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA, TABF.REVENDA, TABF.MODELO, TABF.DATA_DA_VENDA, TABF.QUANTIDADE, TABF.PRECO_CONCORRENTE, TABF.MODELO_JOHN_DEERE, TABF.PRECO_JOHN_DEERE, TABF.MOTIVA, TABF.TIPO_EQUIPAMENTO, TABF.PARTICIPAMOS_DA_NEGO    FROM IV_Q_VENDA_PERDIDA_PROD TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 