/* ==============================================================
   Objeto ..........: dbo.IV_Q$VP_SEM_PARTICIPACAO
   Tipo ............: VIEW
   Criado em .......: 2026-02-04 17:50:11
   Modificado em ...: 2026-02-04 17:50:11
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VP_SEM_PARTICIPACAO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VP_SEM_PARTICIPACAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_CONCORRENTE, MARCA_CONCORRENTE, MODELO_CONCORRENTE, COD_MODELO_CONCORREN, QUANTIDADE_VP, REVENDA_VP, DATA_VP, PRECO_VP, PRECO_JD_VP, MODELO_JD_VP, MOTIVO_VP)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_CONCORRENTE, TABF.MARCA_CONCORRENTE, TABF.MODELO_CONCORRENTE, TABF.COD_MODELO_CONCORREN, TABF.QUANTIDADE_VP, TABF.REVENDA_VP, TABF.DATA_VP, TABF.PRECO_VP, TABF.PRECO_JD_VP, TABF.MODELO_JD_VP, TABF.MOTIVO_VP   FROM IV_Q_VP_SEM_PARTICIPACAO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  