/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_VENDA_MAQ
   Tipo ............: VIEW
   Criado em .......: 2018-02-27 16:25:05
   Modificado em ...: 2018-02-27 16:25:05
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_VENDA_MAQ, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_VENDA_MAQ ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFEITO_PERFORMAN, SATISFACAO_CUSTO_OPE, SATISFACAO_ATENDIMEN, QUAL_SETOR_HA_OPORTU, RECOMENDACAO_COLORAD, PROBLEMA_NRESOLVIDO, SR_NOS_INDICA, QUAL_COLABORADOR_DE_)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFEITO_PERFORMAN, TABF.SATISFACAO_CUSTO_OPE, TABF.SATISFACAO_ATENDIMEN, TABF.QUAL_SETOR_HA_OPORTU, TABF.RECOMENDACAO_COLORAD, TABF.PROBLEMA_NRESOLVIDO, TABF.SR_NOS_INDICA, TABF.QUAL_COLABORADOR_DE_    FROM IV_Q_AFERICAO_VENDA_MAQ TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 