/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_MAQ_1_CONT
   Tipo ............: VIEW
   Criado em .......: 2020-07-23 13:46:37
   Modificado em ...: 2020-07-23 13:46:37
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_MAQ_1_CONT, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_MAQ_1_CONT ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , ESTA_SATISFEITO_COM_, DURANTE_NEGOCIACAO, COMBINADO_CUMPRIDO, UTILIZOU_DEMONSTRACA, FINANCEIRO_ADEQUADO, PRAZO_CUMPRIDO, A_ENTREGA_TECNICA_FO, NPS_0_A_10, FICOU_SATISFEITO, QUAL_AVIALIACAO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.ESTA_SATISFEITO_COM_, TABF.DURANTE_NEGOCIACAO, TABF.COMBINADO_CUMPRIDO, TABF.UTILIZOU_DEMONSTRACA, TABF.FINANCEIRO_ADEQUADO, TABF.PRAZO_CUMPRIDO, TABF.A_ENTREGA_TECNICA_FO, TABF.NPS_0_A_10, TABF.FICOU_SATISFEITO, TABF.QUAL_AVIALIACAO    FROM IV_Q_AFERICAO_MAQ_1_CONT TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 