/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_N
   Tipo ............: VIEW
   Criado em .......: 2024-03-08 16:49:19
   Modificado em ...: 2024-04-17 16:47:42
   Linhas ..........: 72
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

/*
VIEW CRIADA POR FELIPE VIOLIN - NO DIA 08/03/2024
A VIEW FOI CRIADA PARA REPLICAÇÃO DO RELATÓRIO 101X DA ITAETÉ
SOLICITANTE DO PROJETO = Adilson Jose da Cruz

select * from IV_Q_VENDA

*/

CREATE   VIEW IV_Q$VENDA_N AS 

SELECT 
	
	TBASE.SEQPESSOA, 
	TBASE.NOMERAZAO, 
	QST.SEQQUESTIONARIO, 
	FRM.SEQFORMULARIO, 
	FRM.DESCRICAO, 
	QST.DTAREALIZACAO, 
	QST.USUINCLUSAO, 
	QST.DTAALTERACAO, 
	QST.USUALTERACAO, 
	QST.OBS, 
	QST.SEQHISTORICO, 
	QST.RESULTADO, 
	QST.PROCESSO, 
	QST.DEPARTAMENTO, 
	QST.LINKDOCTO, 
	QST.LINKNRO, 
	QST.LINKSERIE , 
	TABF.TIPO_DO_EQUIPAMENTO 	as TIPO_EQUIPAMENTO, 
	TABF.MARCA					as MARCA_EQUIPAM, 
	TABF.MODELO_DO_EQUIPAMENT	as MODELO_EQUIPAM, 
	--TABF.CONFIG_MAQUINA, 		nao achei
	''							as CONFIG_MAQUINA, 
	TABF.VALOR_TOTAL			as VALOR_TOTAL, 
	--TABF.VALOR_REC_PROPRIO, 
	0							as VALOR_REC_PROPRIO, 
	TABF.NRO_PEDIDO_DE_VENDA	as NRO_PEDIDO_VENDA, 
	TABF.DATA_PEDIDO_DE_VENDA	as DATA_PED_VENDA, 
	TABF.PEDIDO_TIRADO_PARA		as FINANCIADO_PARA, 
	TABF.ORIGEM_DO_FATURAMENT	as ORIGEM_FATURAMENTO, 
	TABF.VALOR_FINANCIADO		as VLR_FINANCIADO, 
	TABF.VALOR_RECURSO_PROPRI	as VLR_REC_PROPRIO, 
	--TABF.TIPO_DE_FINANCIAME, 
	''							as TIPO_DE_FINANCIAME,
	TABF.INSTITUICAO_FINANCEI	as INST_FINANCEIRA, 
	TABF.NOME_DO_GERENTE		as NOME_GERENTE, 
	--TABF.PFO_PREVISAO_DE_FAT, 
	''							as PFO_PREVISAO_DE_FAT, 
	--TABF.OBSERVACOES, 
	''							as OBSERVACOES,
	TABF.LINHA_DE_CREDITO		as LINHA_DE_CREDITO, 
	TABF.NUMERO_DA_COTACAO		as QUOTE_ID, 
	--TABF.TIPO_CAMBIO,
	'' 							as TIPO_CAMBIO,
	--TABF.CABINADO, 
	''							as CABINADO, 
	TABF.CODIGO_DO_MODELO  
								as CODMODELO,
	TABF.PEDIDO_TIRADO_PARA		as PEDIDO_TIRADO_PARA						
								
	
	
FROM 
		IV_Q_VENDA 			TABF 
JOIN 	IV_QUESTIONARIO 	QST 	ON 	QST.SEQQUESTIONARIO = TABF.SEQQUESTIONARIO 
JOIN 	IV_FORMULARIO 		FRM 	ON	FRM.SEQFORMULARIO 	= QST.SEQFORMULARIO 
JOIN 	GE_PESSOA 			TBASE 	ON 	TBASE.SEQPESSOA 	= QST.SEQPESSOA 

--where QST.PROCESSO = '1353616'
