/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFE_VENDA_MQ_IM_USAD
   Tipo ............: VIEW
   Criado em .......: 2013-03-19 15:29:33
   Modificado em ...: 2016-03-22 19:20:05
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFE_VENDA_MQ_IM_USAD, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFE_VENDA_MQ_IM_USAD ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , Q001_ZERO, Q001_UM, Q001_DOIS, Q001_TRES, Q001_QUATRO, Q001_CINCO, Q001_SEIS, Q001_SETE, Q001_OITO, Q001_NOVE, Q001_DEZ, Q002_INSATISFEITO, Q002_INDIFERENTE, Q002_SATISFEITO, RECOM_COLORADO_JD_VE, Q006_INSATISFEITO, Q006_INDIFERENTE, Q006_SATISFEITO, Q007_ESTRUTURA, Q007_AREA_VENDAS, Q007_AREA_PECAS, Q007_AREA_SERVICO, Q007_ORGANIZACAO, Q007_ESPACO_FISICO, PESQUISA_MQ_IMP)     AS SELECT PES.SEQPESSOA, PES.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.Q001_ZERO, TABF.Q001_UM, TABF.Q001_DOIS, TABF.Q001_TRES, TABF.Q001_QUATRO, TABF.Q001_CINCO, TABF.Q001_SEIS, TABF.Q001_SETE, TABF.Q001_OITO, TABF.Q001_NOVE, TABF.Q001_DEZ, TABF.Q002_INSATISFEITO, TABF.Q002_INDIFERENTE, TABF.Q002_SATISFEITO, TABF.RECOM_COLORADO_JD_VE, TABF.Q006_INSATISFEITO, TABF.Q006_INDIFERENTE, TABF.Q006_SATISFEITO, TABF.Q007_ESTRUTURA, TABF.Q007_AREA_VENDAS, TABF.Q007_AREA_PECAS, TABF.Q007_AREA_SERVICO, TABF.Q007_ORGANIZACAO, TABF.Q007_ESPACO_FISICO, TABF.PESQUISA_MQ_IMP    FROM  IV_Q_AFE_VENDA_MQ_IM_USAD TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA PES ON PES.SEQPESSOA = QST.SEQPESSOA 