/* ==============================================================
   Objeto ..........: dbo.IV_Q$CONT_COMISSAO_22
   Tipo ............: VIEW
   Criado em .......: 2022-04-25 16:22:18
   Modificado em ...: 2022-04-25 16:22:18
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_CONT_COMISSAO_22, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$CONT_COMISSAO_22 ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VALOR_EQUIPAMENTO_IM, VALOR_AMS_ADICIONAL, __COMISSAO__RH_, VALOR_COMISSAO___RH, COMISSAO_PAGA_RH, LINHA_DE_EQUIPAMENTO, HOUVE_PARTICIPACAO_V, ESPECIALISTA_PARTICI, POSSUI_ACELERADOR___, VALOR_COMISSAO_ESPEC, MARGEM_LUCRO_OPERACI, VALOR_COMISSAO_CEN, COMISSAO_ADICIONAL_E, COMISSAO_AMS_ADICION, VALOR_PREMIO_ESPECIA, MARGEM_LUCROOPERACI, FORMULARIO_NUMERO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VALOR_EQUIPAMENTO_IM, TABF.VALOR_AMS_ADICIONAL, TABF.__COMISSAO__RH_, TABF.VALOR_COMISSAO___RH, TABF.COMISSAO_PAGA_RH, TABF.LINHA_DE_EQUIPAMENTO, TABF.HOUVE_PARTICIPACAO_V, TABF.ESPECIALISTA_PARTICI, TABF.POSSUI_ACELERADOR___, TABF.VALOR_COMISSAO_ESPEC, TABF.MARGEM_LUCRO_OPERACI, TABF.VALOR_COMISSAO_CEN, TABF.COMISSAO_ADICIONAL_E, TABF.COMISSAO_AMS_ADICION, TABF.VALOR_PREMIO_ESPECIA, TABF.MARGEM_LUCROOPERACI, TABF.FORMULARIO_NUMERO    FROM IV_Q_CONT_COMISSAO_22 TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 