/* ==============================================================
   Objeto ..........: dbo.IV_Q$COTA_CONSORCIO
   Tipo ............: VIEW
   Criado em .......: 2025-07-10 15:04:58
   Modificado em ...: 2025-07-10 15:04:58
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COTA_CONSORCIO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COTA_CONSORCIO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CONSORCIO_NOME_CLIEN, CONSORCIO_LOJA, CONSORCIO_CEN, CONSORCIO_DATA, CONSORCIO_GRUPO, CONSORCIO_COTA, CONSORCIO_VALOR)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CONSORCIO_NOME_CLIEN, TABF.CONSORCIO_LOJA, TABF.CONSORCIO_CEN, TABF.CONSORCIO_DATA, TABF.CONSORCIO_GRUPO, TABF.CONSORCIO_COTA, TABF.CONSORCIO_VALOR   FROM IV_Q_COTA_CONSORCIO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  