/* ==============================================================
   Objeto ..........: dbo.IV_Q$VP_TRATOR
   Tipo ............: VIEW
   Criado em .......: 2025-07-14 16:38:52
   Modificado em ...: 2025-07-14 16:38:52
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VP_TRATOR, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VP_TRATOR ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VP_TIPO_EQUIPAMENTO, VP_MARCA_CONCORRENT, VP_MODELO_CONCORRENT, VP_QUANTIDADE_EQUIP, VP_VERSAO_EQUIP, VP_TRANSMISSAO, VP_TECNOLOGIA, VP_ITEM_TECNOLOGIA, VP_PRECO_CONCORRENTE, VP_MODELO_JD, VP_PRECO_JD)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VP_TIPO_EQUIPAMENTO, TABF.VP_MARCA_CONCORRENT, TABF.VP_MODELO_CONCORRENT, TABF.VP_QUANTIDADE_EQUIP, TABF.VP_VERSAO_EQUIP, TABF.VP_TRANSMISSAO, TABF.VP_TECNOLOGIA, TABF.VP_ITEM_TECNOLOGIA, TABF.VP_PRECO_CONCORRENTE, TABF.VP_MODELO_JD, TABF.VP_PRECO_JD   FROM IV_Q_VP_TRATOR TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  