/* ==============================================================
   Objeto ..........: dbo.IV_Q$ACOMP_VENDA_FINANC
   Tipo ............: VIEW
   Criado em .......: 2026-08-18 08:52:20
   Modificado em ...: 2026-08-18 08:52:20
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ACOMP_VENDA_FINANC, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$ACOMP_VENDA_FINANC ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VENDA_FINANC_CHASSI, VENDA_FINANC_NRO_NF, VENDA_FINANC_DATAFAT, VENDA_FINANC_DATAENT, VENDA_FINANC_FILIAL, NUMERO_PROPOSTA, DATA_PROPOSTA, COMAR, DATA_PREVISAO_FAT, COMAR_)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VENDA_FINANC_CHASSI, TABF.VENDA_FINANC_NRO_NF, TABF.VENDA_FINANC_DATAFAT, TABF.VENDA_FINANC_DATAENT, TABF.VENDA_FINANC_FILIAL, TABF.NUMERO_PROPOSTA, TABF.DATA_PROPOSTA, TABF.COMAR, TABF.DATA_PREVISAO_FAT, TABF.COMAR_   FROM IV_Q_ACOMP_VENDA_FINANC TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  