/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PRECISION_UP
   Tipo ............: VIEW
   Criado em .......: 2025-01-21 13:29:49
   Modificado em ...: 2025-01-21 13:29:49
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PRECISION_UP, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PRECISION_UP ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , PUK_TIPO_EQUIP, PUK_MARCA_EQUIP, PUK_MODELO_EQUIP, PUK_QUANTIDADE, PUK_FORMA_PAGTO, PUK_ITENS_AGREGA, PUK_INSTALACAO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.PUK_TIPO_EQUIP, TABF.PUK_MARCA_EQUIP, TABF.PUK_MODELO_EQUIP, TABF.PUK_QUANTIDADE, TABF.PUK_FORMA_PAGTO, TABF.PUK_ITENS_AGREGA, TABF.PUK_INSTALACAO   FROM IV_Q_VENDA_PRECISION_UP TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  