/* ==============================================================
   Objeto ..........: dbo.IV_Q$PRODUTO_RD
   Tipo ............: VIEW
   Criado em .......: 2026-07-13 09:51:22
   Modificado em ...: 2026-07-13 09:51:22
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_PRODUTO_RD, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$PRODUTO_RD ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , PRODUTO_RD, CAMPANHA, QUANTO_TEMPO_DESEJA_, MOTIVO_MIDIA, CONDICAO, FORMA_DE_CONTATO, COTA, PERFIL_DE_COMPRA)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.PRODUTO_RD, TABF.CAMPANHA, TABF.QUANTO_TEMPO_DESEJA_, TABF.MOTIVO_MIDIA, TABF.CONDICAO, TABF.FORMA_DE_CONTATO, TABF.COTA, TABF.PERFIL_DE_COMPRA   FROM IV_Q_PRODUTO_RD TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  