/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_JDE
   Tipo ............: VIEW
   Criado em .......: 2024-01-31 08:32:34
   Modificado em ...: 2024-01-31 08:32:34
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_JDE, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_JDE ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA_VP, REVENDA, MODELO_VP, DATA_DA_VENDA, QUANTIDADE, PRECO_CONCORRENTE, PRECO_JOHN_DEERE, MODELO_JOHN_DEER, MOTIVO, TIPO_EQUIPAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA_VP, TABF.REVENDA, TABF.MODELO_VP, TABF.DATA_DA_VENDA, TABF.QUANTIDADE, TABF.PRECO_CONCORRENTE, TABF.PRECO_JOHN_DEERE, TABF.MODELO_JOHN_DEER, TABF.MOTIVO, TABF.TIPO_EQUIPAMENTO   FROM IV_Q_VENDA_PERDIDA_JDE TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  