/* ==============================================================
   Objeto ..........: dbo.IV_Q$SERVICO_EXTERNOS_JD
   Tipo ............: VIEW
   Criado em .......: 2019-08-16 14:18:20
   Modificado em ...: 2019-08-16 14:18:20
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_SERVICO_EXTERNOS_JD, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$SERVICO_EXTERNOS_JD ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , EQUIPAMENTO, CHASSI, FROTA, CONDICAO_DE_PAGAMENT, DEFEITO_APRESENTADO, LOCALIZACAO_DO_EQUIP, CONTATO_DO_OPERADOR)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.EQUIPAMENTO, TABF.CHASSI, TABF.FROTA, TABF.CONDICAO_DE_PAGAMENT, TABF.DEFEITO_APRESENTADO, TABF.LOCALIZACAO_DO_EQUIP, TABF.CONTATO_DO_OPERADOR    FROM IV_Q_SERVICO_EXTERNOS_JD TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 