/* ==============================================================
   Objeto ..........: dbo.IV_Q$DEMONSTR_COLHEITAD
   Tipo ............: VIEW
   Criado em .......: 2013-03-20 12:26:16
   Modificado em ...: 2016-03-22 19:20:05
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_DEMONSTR_COLHEITAD, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$DEMONSTR_COLHEITAD ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_PLANTADEIRA, MODELO_PLANTADEIRA, NRO_SERIE, DEMONSTRADOR, TIPO_PLANTIO, MODELO_TRATOR, CONFIG_TRATOR)     AS SELECT PES.SEQPESSOA, PES.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_PLANTADEIRA, TABF.MODELO_PLANTADEIRA, TABF.NRO_SERIE, TABF.DEMONSTRADOR, TABF.TIPO_PLANTIO, TABF.MODELO_TRATOR, TABF.CONFIG_TRATOR    FROM  IV_Q_DEMONSTR_COLHEITAD TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA PES ON PES.SEQPESSOA = QST.SEQPESSOA 