/* ==============================================================
   Objeto ..........: dbo.IV_Q$VP_PULVERIZADOR
   Tipo ............: VIEW
   Criado em .......: 2025-07-14 16:39:31
   Modificado em ...: 2025-07-14 16:39:31
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VP_PULVERIZADOR, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VP_PULVERIZADOR ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VP_PV_TIPO_EQUIP, VP_PV_MARCA_CONC, VP_PV_MODELO_CONC, VP_PV_QTDE_CONC, VP_PV_TECNOLOGIA, VP_PV_ITENS_TECNO, VP_PV_PRECO_CONC, VP_PV_MODELO_JD, VP_PV_PRECO_JD)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VP_PV_TIPO_EQUIP, TABF.VP_PV_MARCA_CONC, TABF.VP_PV_MODELO_CONC, TABF.VP_PV_QTDE_CONC, TABF.VP_PV_TECNOLOGIA, TABF.VP_PV_ITENS_TECNO, TABF.VP_PV_PRECO_CONC, TABF.VP_PV_MODELO_JD, TABF.VP_PV_PRECO_JD   FROM IV_Q_VP_PULVERIZADOR TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  