/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_MAQ_3_CONT
   Tipo ............: VIEW
   Criado em .......: 2020-07-23 08:55:11
   Modificado em ...: 2020-07-23 08:55:11
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_MAQ_3_CONT, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_MAQ_3_CONT ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , ENTROU_CONTATO, CONSULTOR_CONTATO, NECESSIDADE_PRODUTO, NPS_0_A_10, SATISFACAO_ESCOLHA, SATISFACAO_DESEMPENH, SATISFACAO_DSIPONIBI, DISPONILIDADE_ESTOQU, SATISFACAO_TEMPO, SATISFACAO_RESPEITO, PROBLEMA_N_RESOLVIDO, MELHOR_EXPERIENCIA)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.ENTROU_CONTATO, TABF.CONSULTOR_CONTATO, TABF.NECESSIDADE_PRODUTO, TABF.NPS_0_A_10, TABF.SATISFACAO_ESCOLHA, TABF.SATISFACAO_DESEMPENH, TABF.SATISFACAO_DSIPONIBI, TABF.DISPONILIDADE_ESTOQU, TABF.SATISFACAO_TEMPO, TABF.SATISFACAO_RESPEITO, TABF.PROBLEMA_N_RESOLVIDO, TABF.MELHOR_EXPERIENCIA    FROM IV_Q_AFERICAO_MAQ_3_CONT TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 