/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA
   Tipo ............: VIEW
   Criado em .......: 2025-05-20 17:34:23
   Modificado em ...: 2025-05-20 17:34:23
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_DO_EQUIPAMENTO, MARCA, MODELO_DO_EQUIPAMENT, VALOR_TOTAL, NRO_PEDIDO_DE_VENDA, DATA_PEDIDO_DE_VENDA, PEDIDO_TIRADO_PARA, ORIGEM_DO_FATURAMENT, VALOR_FINANCIADO, VALOR_RECURSO_PROPRI, INSTITUICAO_FINANCEI, NOME_DO_GERENTE, LINHA_DE_CREDITO, NUMERO_DA_COTACAO, CODIGO_DO_MODELO, PRIMEIRO_JOHN_DEERE, VENDA_COMPARTILHADA, CONSULTOR_1, CONSULTOR_2, TIPO_DE_VENDA, FORMA_DE_PAGAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_DO_EQUIPAMENTO, TABF.MARCA, TABF.MODELO_DO_EQUIPAMENT, TABF.VALOR_TOTAL, TABF.NRO_PEDIDO_DE_VENDA, TABF.DATA_PEDIDO_DE_VENDA, TABF.PEDIDO_TIRADO_PARA, TABF.ORIGEM_DO_FATURAMENT, TABF.VALOR_FINANCIADO, TABF.VALOR_RECURSO_PROPRI, TABF.INSTITUICAO_FINANCEI, TABF.NOME_DO_GERENTE, TABF.LINHA_DE_CREDITO, TABF.NUMERO_DA_COTACAO, TABF.CODIGO_DO_MODELO, TABF.PRIMEIRO_JOHN_DEERE, TABF.VENDA_COMPARTILHADA, TABF.CONSULTOR_1, TABF.CONSULTOR_2, TABF.TIPO_DE_VENDA, TABF.FORMA_DE_PAGAMENTO   FROM IV_Q_VENDA TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  