/* ==============================================================
   Objeto ..........: dbo.IV_Q$ADM_FINANCEIRO
   Tipo ............: VIEW
   Criado em .......: 2025-06-05 12:15:04
   Modificado em ...: 2025-06-05 12:15:04
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ADM_FINANCEIRO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$ADM_FINANCEIRO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CNPJ_CPF_DO_COMPRADO, AGENCIA, NRO_CHASSI, DATA_PROTOCOLO_NO_BA, DATA_AUTORIZACAO_FAT, DATA_FATURAMENTO, NRO_NF, DATA_LIBERACAO_DO_RE, VALOR_RECEBIDO, DATA_DA_PROPOSTA, PFA___PREVISAO_DE_FA, NUMERO_DA_PROPOSTA, LOJA)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CNPJ_CPF_DO_COMPRADO, TABF.AGENCIA, TABF.NRO_CHASSI, TABF.DATA_PROTOCOLO_NO_BA, TABF.DATA_AUTORIZACAO_FAT, TABF.DATA_FATURAMENTO, TABF.NRO_NF, TABF.DATA_LIBERACAO_DO_RE, TABF.VALOR_RECEBIDO, TABF.DATA_DA_PROPOSTA, TABF.PFA___PREVISAO_DE_FA, TABF.NUMERO_DA_PROPOSTA, TABF.LOJA   FROM IV_Q_ADM_FINANCEIRO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  