/* ==============================================================
   Objeto ..........: dbo.IV_Q$ACOMP_VENDA_DIRETA
   Tipo ............: VIEW
   Criado em .......: 2017-06-01 15:13:20
   Modificado em ...: 2017-06-01 15:13:20
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ACOMP_VENDA_DIRETA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$ACOMP_VENDA_DIRETA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CLIENTE_SAM, Q002_COLHEDORAS, Q002_COLHEITADEIRAS, Q002_PULVERIZADORES, Q002_TRATORES, MODELO_DO_EQUIPAMENT, N__PEDIDO, VALOR_DA_VENDA, FRETE, ICMS, PIS___COFINS, BASE_DE_CALCULO, __COMISSAO, COMISSAO_PROVISIONAD, VALOR_FINAL_COMISSAO, CHASSI, N__NF_COMISSAO_VEND_, DATA_MARCADO_ENTREGU, TIPO_CLIENTE)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CLIENTE_SAM, TABF.Q002_COLHEDORAS, TABF.Q002_COLHEITADEIRAS, TABF.Q002_PULVERIZADORES, TABF.Q002_TRATORES, TABF.MODELO_DO_EQUIPAMENT, TABF.N__PEDIDO, TABF.VALOR_DA_VENDA, TABF.FRETE, TABF.ICMS, TABF.PIS___COFINS, TABF.BASE_DE_CALCULO, TABF.__COMISSAO, TABF.COMISSAO_PROVISIONAD, TABF.VALOR_FINAL_COMISSAO, TABF.CHASSI, TABF.N__NF_COMISSAO_VEND_, TABF.DATA_MARCADO_ENTREGU, TABF.TIPO_CLIENTE    FROM IV_Q_ACOMP_VENDA_DIRETA TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 