/* ==============================================================
   Objeto ..........: dbo.IV_Q$INTERESSE_PROJETO_IR
   Tipo ............: VIEW
   Criado em .......: 2024-01-28 22:53:11
   Modificado em ...: 2024-01-28 22:53:11
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_INTERESSE_PROJETO_IR, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$INTERESSE_PROJETO_IR ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CULTURA, AREA_HA, LANCES, STATUS, PROBABILIDADE_FECHAM, VALOR, DATA_FATURAMENTO, VENDEDOR_INDICACAO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CULTURA, TABF.AREA_HA, TABF.LANCES, TABF.STATUS, TABF.PROBABILIDADE_FECHAM, TABF.VALOR, TABF.DATA_FATURAMENTO, TABF.VENDEDOR_INDICACAO   FROM IV_Q_INTERESSE_PROJETO_IR TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  