/* ==============================================================
   Objeto ..........: dbo.IV_Q$COMPETIDORES_NA_NEGO
   Tipo ............: VIEW
   Criado em .......: 2024-01-31 08:55:15
   Modificado em ...: 2024-01-31 08:55:15
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COMPETIDORES_NA_NEGO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COMPETIDORES_NA_NEGO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA, REVENDA, MODELO_COMP, QUANTIDADE, PRECO_CONCORRENTE, CONDICOES_PAGTO_CO, CONDICOES_PAGTO_JO, EXISTE_COMP, TIPO_EQUIPAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA, TABF.REVENDA, TABF.MODELO_COMP, TABF.QUANTIDADE, TABF.PRECO_CONCORRENTE, TABF.CONDICOES_PAGTO_CO, TABF.CONDICOES_PAGTO_JO, TABF.EXISTE_COMP, TABF.TIPO_EQUIPAMENTO   FROM IV_Q_COMPETIDORES_NA_NEGO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  