/* ==============================================================
   Objeto ..........: dbo.IV_Q$VP_PLANTADEIRA
   Tipo ............: VIEW
   Criado em .......: 2025-05-19 16:13:09
   Modificado em ...: 2025-05-19 16:13:09
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VP_PLANTADEIRA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VP_PLANTADEIRA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VP_PL_TIPO_EQUIP_CON, VP_PL_MARCA_CONC, VP_PL_MODELO_CONC, VP_PL_QTDE_LINHAS, VP_PL_CAIXA_SEMENTE, VP_PL_DESLIGAMENTO, VP_PL_MARCADOR_LINHA, VP_PL_DOSADOR_MEC, VP_PL_MONITOR_PLANT, VP_PL_PRECO_CONC, VP_PL_MODELO_JD, VP_PL_PRECO_JD)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VP_PL_TIPO_EQUIP_CON, TABF.VP_PL_MARCA_CONC, TABF.VP_PL_MODELO_CONC, TABF.VP_PL_QTDE_LINHAS, TABF.VP_PL_CAIXA_SEMENTE, TABF.VP_PL_DESLIGAMENTO, TABF.VP_PL_MARCADOR_LINHA, TABF.VP_PL_DOSADOR_MEC, TABF.VP_PL_MONITOR_PLANT, TABF.VP_PL_PRECO_CONC, TABF.VP_PL_MODELO_JD, TABF.VP_PL_PRECO_JD   FROM IV_Q_VP_PLANTADEIRA TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  