/* ==============================================================
   Objeto ..........: dbo.IV_Q$COMPETIDORES_NA_NEG
   Tipo ............: VIEW
   Criado em .......: 2014-12-19 13:05:57
   Modificado em ...: 2016-03-22 19:20:04
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COMPETIDORES_NA_NEG, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COMPETIDORES_NA_NEG ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA, REVENDA, MODELO_COMP, QUANTIDADE, PRECO_CONCORRENTE, CONDICOES_PAGTO_CO, CONDICOES_PAGTO_JO, EXISTE_COMP)     AS SELECT PES.SEQPESSOA, PES.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA, TABF.REVENDA, TABF.MODELO_COMP, TABF.QUANTIDADE, TABF.PRECO_CONCORRENTE, TABF.CONDICOES_PAGTO_CO, TABF.CONDICOES_PAGTO_JO, TABF.EXISTE_COMP    FROM  IV_Q_COMPETIDORES_NA_NEG TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA PES ON PES.SEQPESSOA = QST.SEQPESSOA 