/* ==============================================================
   Objeto ..........: dbo.IV_Q$PROPOSTA_COMERCIAL
   Tipo ............: VIEW
   Criado em .......: 2025-04-09 10:24:00
   Modificado em ...: 2025-04-09 10:24:00
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_PROPOSTA_COMERCIAL, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$PROPOSTA_COMERCIAL ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_DE_EQUIPAMENTO, MARCA, MODELO_DO_EQUIPAMENT, DESCRICAO, VALOR_TOTAL, VALOR_SINAL, VALOR_FINANCIADO, VALOR_RECURSO_PROP, TIPO_DE_PAGAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_DE_EQUIPAMENTO, TABF.MARCA, TABF.MODELO_DO_EQUIPAMENT, TABF.DESCRICAO, TABF.VALOR_TOTAL, TABF.VALOR_SINAL, TABF.VALOR_FINANCIADO, TABF.VALOR_RECURSO_PROP, TABF.TIPO_DE_PAGAMENTO   FROM IV_Q_PROPOSTA_COMERCIAL TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  