/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_FY25
   Tipo ............: VIEW
   Criado em .......: 2026-02-04 17:49:51
   Modificado em ...: 2026-02-04 17:49:51
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_FY25, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_FY25 ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VP_TIPO_EQUIP_CONCOR, VP_MARCA_EQUIP_CONCO, VP_MODELO_EQUIP_CONC, VP_COD_MODELO_CONCOR, VP_QUANTIDADE, VP_REVENDA, VP_DATA_VP, VP_PRECO_CONCORRENTE, VP_PRECO_JD, VP_MODELO_JD, PILOTO, VP_MOTIVO_VP)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VP_TIPO_EQUIP_CONCOR, TABF.VP_MARCA_EQUIP_CONCO, TABF.VP_MODELO_EQUIP_CONC, TABF.VP_COD_MODELO_CONCOR, TABF.VP_QUANTIDADE, TABF.VP_REVENDA, TABF.VP_DATA_VP, TABF.VP_PRECO_CONCORRENTE, TABF.VP_PRECO_JD, TABF.VP_MODELO_JD, TABF.PILOTO, TABF.VP_MOTIVO_VP   FROM IV_Q_VENDA_PERDIDA_FY25 TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  