/* ==============================================================
   Objeto ..........: dbo.IV_Q$VP_COLHEITADEIRA
   Tipo ............: VIEW
   Criado em .......: 2025-05-19 14:59:13
   Modificado em ...: 2025-05-19 14:59:13
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VP_COLHEITADEIRA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VP_COLHEITADEIRA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VP_CA_TIPO, VP_CA_MARCA_CONC, VP_CA_MODELO_CONC, VP_CA_QTDE_CONC, VP_CA_PLATAFORMA_CON, VP_CA_RODADO, VP_CA_TECNOLOGIA, VP_CA_ITENS_TECNOLOG, VP_CA_PRECO_CONC, VP_CA_MODELO_JD, VP_CA_PRECO_JD)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VP_CA_TIPO, TABF.VP_CA_MARCA_CONC, TABF.VP_CA_MODELO_CONC, TABF.VP_CA_QTDE_CONC, TABF.VP_CA_PLATAFORMA_CON, TABF.VP_CA_RODADO, TABF.VP_CA_TECNOLOGIA, TABF.VP_CA_ITENS_TECNOLOG, TABF.VP_CA_PRECO_CONC, TABF.VP_CA_MODELO_JD, TABF.VP_CA_PRECO_JD   FROM IV_Q_VP_COLHEITADEIRA TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  