/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_DE_PECAS
   Tipo ............: VIEW
   Criado em .......: 2020-06-18 09:36:12
   Modificado em ...: 2020-06-18 09:36:12
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_DE_PECAS, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_DE_PECAS ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFEITO_ATENDIMEN, CUMPRIMENTO, PRODUTO, SUGESTAO, NOTA_NPS, PRODUTO_DISP, SUGESTAO_PECAS)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFEITO_ATENDIMEN, TABF.CUMPRIMENTO, TABF.PRODUTO, TABF.SUGESTAO, TABF.NOTA_NPS, TABF.PRODUTO_DISP, TABF.SUGESTAO_PECAS    FROM IV_Q_AFERICAO_DE_PECAS TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 