/* ==============================================================
   Objeto ..........: dbo.IV_Q$GESTAO_PRODUTO_IMPL
   Tipo ............: VIEW
   Criado em .......: 2023-02-24 12:35:02
   Modificado em ...: 2023-02-24 12:35:02
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_GESTAO_PRODUTO_IMPL, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$GESTAO_PRODUTO_IMPL ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , FORMULARIO_NFORMULAR, TIPO_EQUIPAMENTO, MARCA, MODELO_IMPLEMENTO, DESCRICAO_DETALHADA_, COR_IMPLEMENTO, ANO_FABRICACAO, INFORMACAO_PREPARACA, PRODUTO_NOVO_OU_USAD, NUMERO, NUMERO1, CHASSI, VENDA_DO_IMPLEMENTO, DESCONTO_INCONDICION, DATA_ESPERADA_PARA_E, DATA_DE_USO_PARA_SAZ, PREVISAO_ENTREGA_PRE, DATA_ENTREGA, TRANSPORTADORA, VALOR_FRETE, TRANSPORTE_ENTREGA)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.FORMULARIO_NFORMULAR, TABF.TIPO_EQUIPAMENTO, TABF.MARCA, TABF.MODELO_IMPLEMENTO, TABF.DESCRICAO_DETALHADA_, TABF.COR_IMPLEMENTO, TABF.ANO_FABRICACAO, TABF.INFORMACAO_PREPARACA, TABF.PRODUTO_NOVO_OU_USAD, TABF.NUMERO, TABF.NUMERO1, TABF.CHASSI, TABF.VENDA_DO_IMPLEMENTO, TABF.DESCONTO_INCONDICION, TABF.DATA_ESPERADA_PARA_E, TABF.DATA_DE_USO_PARA_SAZ, TABF.PREVISAO_ENTREGA_PRE, TABF.DATA_ENTREGA, TABF.TRANSPORTADORA, TABF.VALOR_FRETE, TABF.TRANSPORTE_ENTREGA    FROM IV_Q_GESTAO_PRODUTO_IMPL TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 