/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_DSI
   Tipo ............: VIEW
   Criado em .......: 2025-01-21 14:32:48
   Modificado em ...: 2025-01-21 14:32:48
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_DSI, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_DSI ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , PEDIDO_PARA, TIPO_SERVICO, TIPO_EQUIP, MARCA, MODELO_EQUIP, VALOR_SERVICO, VALOR_DESLOCAM, DATA_EXEC_SERVICO, SITUACAO_CADASTRAL, QTDE_EQUIPAMENTO, CONDICAO_PAGAMENTO, TIPO_EQUIPAMENTO, MARCA_EQUIPAMENTO, MODELO_EQUIPAMENTO, CHASSIS_EQUIP)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.PEDIDO_PARA, TABF.TIPO_SERVICO, TABF.TIPO_EQUIP, TABF.MARCA, TABF.MODELO_EQUIP, TABF.VALOR_SERVICO, TABF.VALOR_DESLOCAM, TABF.DATA_EXEC_SERVICO, TABF.SITUACAO_CADASTRAL, TABF.QTDE_EQUIPAMENTO, TABF.CONDICAO_PAGAMENTO, TABF.TIPO_EQUIPAMENTO, TABF.MARCA_EQUIPAMENTO, TABF.MODELO_EQUIPAMENTO, TABF.CHASSIS_EQUIP   FROM IV_Q_VENDA_DSI TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  