/* ==============================================================
   Objeto ..........: dbo.IV_Q$ACOMPAN_COMPRA_JDE
   Tipo ............: VIEW
   Criado em .......: 2016-08-23 14:43:29
   Modificado em ...: 2026-05-22 08:44:53
   Linhas ..........: 43
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ACOMPAN_COMPRA_JDE, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

-- dbo.IV_Q$ACOMPAN_COMPRA_JDE fonte

CREATE VIEW dbo.IV_Q$ACOMPAN_COMPRA_JDE (
	SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TP_EQUIP2, MARCAJD2, MDL_EQUIP2, QT2, FDD2, QTD_PES_TRS2, KG_TRAS1_JD2, QTD_PES_TRS_OPC22, KG_TRS2_JD2, QTD_PES_DIAN2, KG_DIANT_JD2, RDD_TRS_JD2, RDD_DIAN_JD2, QTD_VCR_100_JD2, QTDE_VCR_300_JD2, COMPLEMENTO_OBS
) AS

SELECT	TBASE.SEQPESSOA,
		TBASE.NOMERAZAO,
		QST.SEQQUESTIONARIO,
		FRM.SEQFORMULARIO,
		FRM.DESCRICAO,
		QST.DTAREALIZACAO,
		QST.USUINCLUSAO,
		QST.DTAALTERACAO,
		QST.USUALTERACAO,
		QST.OBS,
		QST.SEQHISTORICO,
		QST.RESULTADO,
		QST.PROCESSO,
		QST.DEPARTAMENTO,
		QST.LINKDOCTO,
		QST.LINKNRO,
		QST.LINKSERIE,
		TABF.TP_EQUIP2,
		TABF.MARCAJD2,
		TABF.MDL_EQUIP2,
		TABF.QT2,
		TABF.FDD2,
		TABF.QTD_PES_TRS2,
		TABF.KG_TRAS1_JD2,
		TABF.QTD_PES_TRS_OPC22,
		TABF.KG_TRS2_JD2,
		TABF.QTD_PES_DIAN2,
		TABF.KG_DIANT_JD2,
		TABF.RDD_TRS_JD2,
		TABF.RDD_DIAN_JD2,
		TABF.QTD_VCR_100_JD2,
		TABF.QTDE_VCR_300_JD2,
		TABF.COMPLEMENTO_OBS
FROM	IV_Q_ACOMPAN_COMPRA_JDE		TABF
JOIN	IV_QUESTIONARIO				QST		ON	QST.SEQQUESTIONARIO		=	TABF.SEQQUESTIONARIO
JOIN	IV_FORMULARIO				FRM		ON	FRM.SEQFORMULARIO		=	QST.SEQFORMULARIO
JOIN	GE_PESSOA					TBASE	ON	TBASE.SEQPESSOA			=	QST.SEQPESSOA;