/* ==============================================================
   Objeto ..........: dbo.IV_Q$PECAS_AFERICAO
   Tipo ............: VIEW
   Criado em .......: 2020-06-18 17:31:06
   Modificado em ...: 2020-06-18 17:31:06
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_PECAS_AFERICAO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$PECAS_AFERICAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFACAO_EM_RELACA, QUAL_SETOR_HA_OPORTU, SATISFACAO_AS_ULTIMA, RECOMENDA_A_COLORADO, O_SR__INDICA_UM_AMIG, QUAL_COLABORADOR_SE_, RECOMENDA, SATISFACAO, ACORDADO, PRODUTO, SUGESTAO, NOTA_NPS)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFACAO_EM_RELACA, TABF.QUAL_SETOR_HA_OPORTU, TABF.SATISFACAO_AS_ULTIMA, TABF.RECOMENDA_A_COLORADO, TABF.O_SR__INDICA_UM_AMIG, TABF.QUAL_COLABORADOR_SE_, TABF.RECOMENDA, TABF.SATISFACAO, TABF.ACORDADO, TABF.PRODUTO, TABF.SUGESTAO, TABF.NOTA_NPS    FROM IV_Q_PECAS_AFERICAO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 