/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_MAQIMP
   Tipo ............: VIEW
   Criado em .......: 2025-04-17 08:04:30
   Modificado em ...: 2025-04-17 08:04:30
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_MAQIMP, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_MAQIMP ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA_VP, REVENDA_VP, MODELO_VP, DATA_VENDA_VP, QUANTIDADE_VP, PRECO_CONCORRENTE_VP, PRECO_JOHN_DEERE_VP, MODELO_JOHN_DEERE_VP, MOTIVO_VP, TIPO_EQUIP_VP, COD_MODE_VP)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA_VP, TABF.REVENDA_VP, TABF.MODELO_VP, TABF.DATA_VENDA_VP, TABF.QUANTIDADE_VP, TABF.PRECO_CONCORRENTE_VP, TABF.PRECO_JOHN_DEERE_VP, TABF.MODELO_JOHN_DEERE_VP, TABF.MOTIVO_VP, TABF.TIPO_EQUIP_VP, TABF.COD_MODE_VP   FROM IV_Q_VENDA_PERDIDA_MAQIMP TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  