/* ==============================================================
   Objeto ..........: dbo.IV_Q$COMISSAO_SERV_AMS
   Tipo ............: VIEW
   Criado em .......: 2021-07-27 07:42:05
   Modificado em ...: 2021-07-27 07:42:05
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COMISSAO_SERV_AMS, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COMISSAO_SERV_AMS ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_DE_SERVICO, VALOR_DO_SERVICO, ESPECIALISTA_AMS, __COMISSAO_CEN, __COMISSAO_ESPECIALI, CEN, VALOR_COMISSAO_ESPEC, VALOR_COMISSAO_CEN, CEN_, VALOR_COMISSAO_ESP, VALOR_COMISSAOCEN, _COMISSAO_CEN, _COMISSAO_ESPEC, COMISSAO_PAGA)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_DE_SERVICO, TABF.VALOR_DO_SERVICO, TABF.ESPECIALISTA_AMS, TABF.__COMISSAO_CEN, TABF.__COMISSAO_ESPECIALI, TABF.CEN, TABF.VALOR_COMISSAO_ESPEC, TABF.VALOR_COMISSAO_CEN, TABF.CEN_, TABF.VALOR_COMISSAO_ESP, TABF.VALOR_COMISSAOCEN, TABF._COMISSAO_CEN, TABF._COMISSAO_ESPEC, TABF.COMISSAO_PAGA    FROM IV_Q_COMISSAO_SERV_AMS TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 