/* ==============================================================
   Objeto ..........: dbo.IV_Q$DEMO_IMPLEMENTO
   Tipo ............: VIEW
   Criado em .......: 2015-01-19 00:03:16
   Modificado em ...: 2016-03-22 19:20:06
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_DEMO_IMPLEMENTO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$DEMO_IMPLEMENTO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MODELO_DEMO, N__SERIE, MUNICIPIO, DEMONSTRADOR, RODAGEM_DIANTEIRA, RODAGEM_TRASEIRA, LASTREAMENTO, TIPO_DE_SERVICO, MARCA_DO_IMPLEMENT, TIPO_DO_IMPLEMENTO, GRUPO_CULTURA, TIPO_CULTURA, MARCHA_UTILIZADA, RPM_DO_MOTOR, VELOCIDADE_KM_H, PROFUNDIDADE_DE_CO, HORAS_TRABALHADAS, HORA_INICIAL, HORA_FINAL, DIAS_TRABALHADOS, OPERADOR, LITROS_CONSUMIDOS, TONELADAS_TRABALHA, HECTARES_TRABALHAD)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MODELO_DEMO, TABF.N__SERIE, TABF.MUNICIPIO, TABF.DEMONSTRADOR, TABF.RODAGEM_DIANTEIRA, TABF.RODAGEM_TRASEIRA, TABF.LASTREAMENTO, TABF.TIPO_DE_SERVICO, TABF.MARCA_DO_IMPLEMENT, TABF.TIPO_DO_IMPLEMENTO, TABF.GRUPO_CULTURA, TABF.TIPO_CULTURA, TABF.MARCHA_UTILIZADA, TABF.RPM_DO_MOTOR, TABF.VELOCIDADE_KM_H, TABF.PROFUNDIDADE_DE_CO, TABF.HORAS_TRABALHADAS, TABF.HORA_INICIAL, TABF.HORA_FINAL, TABF.DIAS_TRABALHADOS, TABF.OPERADOR, TABF.LITROS_CONSUMIDOS, TABF.TONELADAS_TRABALHA, TABF.HECTARES_TRABALHAD    FROM IV_Q_DEMO_IMPLEMENTO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 