/* ==============================================================
   Objeto ..........: dbo.IV_Q$CANCEL_RENOVACAO_SEG
   Tipo ............: VIEW
   Criado em .......: 2025-05-07 17:07:20
   Modificado em ...: 2025-05-07 17:07:20
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_CANCEL_RENOVACAO_SEG, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$CANCEL_RENOVACAO_SEG ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CANCEL_RENOV_SEGURO, CANCEL_RENOV_PRECO, CANCEL_SEGUR_MOTIVO, CANCEL_RENOV_SEG_APO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CANCEL_RENOV_SEGURO, TABF.CANCEL_RENOV_PRECO, TABF.CANCEL_SEGUR_MOTIVO, TABF.CANCEL_RENOV_SEG_APO   FROM IV_Q_CANCEL_RENOVACAO_SEG TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  