/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_SEGURO
   Tipo ............: VIEW
   Criado em .......: 2023-05-25 08:51:05
   Modificado em ...: 2023-05-25 08:51:05
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_SEGURO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_SEGURO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , DATA, EQUIPAMENTOS_JD, OUTROS_EQUIPAMENTOS, SEGURADORA_CONCORREN, PRECO_CONCORRENTE, CONDICAO_COMERCIAL_C, SEGURADORA_COLORADO, PRECO_COLORADO, CONDICAO_COMERCIAL, MOTIVO, PRECO_CONCORRENTE1, PRECO_COLORADO1)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.DATA, TABF.EQUIPAMENTOS_JD, TABF.OUTROS_EQUIPAMENTOS, TABF.SEGURADORA_CONCORREN, TABF.PRECO_CONCORRENTE, TABF.CONDICAO_COMERCIAL_C, TABF.SEGURADORA_COLORADO, TABF.PRECO_COLORADO, TABF.CONDICAO_COMERCIAL, TABF.MOTIVO, TABF.PRECO_CONCORRENTE1, TABF.PRECO_COLORADO1    FROM IV_Q_VENDA_PERDIDA_SEGURO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 