/* ==============================================================
   Objeto ..........: dbo.IV_Q$PERCEPCAO_JD
   Tipo ............: VIEW
   Criado em .......: 2026-02-10 14:44:05
   Modificado em ...: 2026-02-10 14:44:05
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_PERCEPCAO_JD, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$PERCEPCAO_JD ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , NOTA_DEMONSTRACAO, POSSUI_EQP_JD, DEMONSTROU_INTERESSE, MODELO_1, DEMONSTRACAO_NEGOC, MODELO_02, ERGONOMIA_ATRATIVA, PERFORMANCE_ATRATIVA, CONSUMO_EXPECTATIVA, AGRICULTURA_VALOR, VALOR_OPERATION, PERCEPCAO_GERAL, EXPECTATIVA, CONSUMO_EXPEC, QUANTIDADE, HORIMETRO_FINAL)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.NOTA_DEMONSTRACAO, TABF.POSSUI_EQP_JD, TABF.DEMONSTROU_INTERESSE, TABF.MODELO_1, TABF.DEMONSTRACAO_NEGOC, TABF.MODELO_02, TABF.ERGONOMIA_ATRATIVA, TABF.PERFORMANCE_ATRATIVA, TABF.CONSUMO_EXPECTATIVA, TABF.AGRICULTURA_VALOR, TABF.VALOR_OPERATION, TABF.PERCEPCAO_GERAL, TABF.EXPECTATIVA, TABF.CONSUMO_EXPEC, TABF.QUANTIDADE, TABF.HORIMETRO_FINAL   FROM IV_Q_PERCEPCAO_JD TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  