/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_AMS
   Tipo ............: VIEW
   Criado em .......: 2019-12-17 16:40:19
   Modificado em ...: 2020-10-27 14:03:21
   Linhas ..........: 16
   Escreve em tabela: nao
   Tabelas referidas: GE_Pessoa, IV_Formulario, IV_Q_VENDA_AMS, IV_Questionario
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_AMS
AS
SELECT TBASE.SeqPessoa, TBASE.NomeRazao AS Pessoa, QST.SeqQuestionario, FRM.SeqFormulario, FRM.Descricao AS Formulario, QST.DtaRealizacao, QST.UsuInclusao, QST.DtaAlteracao, QST.UsuAlteracao, QST.Obs AS Observacao, QST.SeqHistorico, QST.Resultado, QST.Processo, 
             QST.Departamento, QST.LinkDocto, QST.LinkNro, QST.LinkSerie, TABF.NUMERO_PEDIDO_AMS, TABF.VALOR_DA_VENDA, TABF.FORMA_DE_PAGAMENTO, TABF.Q004_MONITOR_GS3, TABF.Q004_RECEPTOR_0908, TABF.Q004_VOLANTE_0520, TABF.Q004_CHICOTE_90687, 
             TABF.Q004_SUPORTE_90385, TABF.Q004_CHICOTE_ISO, TABF.Q004_ANTI_PF90889, TABF.Q004_AUTOTRAC_049, TABF.Q004_SF3_READY, TABF.Q004_RADIO_900_MHZ, TABF.Q004_450MHZ, TABF.Q004_KIT_AL207195, TABF.Q004_RTK_7307PC, TABF.Q004_ANTI_ROTACAO, 
             TABF.Q004_ATIVACAO_RTK, TABF.COM_INSTALACAO_DO_AM, TABF.INFORMAR_AGREGA, TABF.INFORMAR_DESAGREGA_A, TABF.ITENS_DO_AMS, TABF.CHASSI_DO_ITEM_AMS, TABF.NUMERO_NOTA_FISCAL, TABF.DATA_DO_PEDIDO, TABF.TIPO_DE_PAGAMENTO, 
             TABF.INSTITUICAO_FINANCEI, TABF.NRO_DA_AGENCIA, TABF.NOME_DA_AGENCIA, TABF.NOME_DO_GERENTE_DO_B, TABF.VALOR_FINANCIADO, TABF.TELEFONE_DA_AGENCIA, TABF.E_MAIL_DE_CONTATO_DA, TABF.INFORMACOES_PARA_O_F, 
             TABF.PREVISAO_DO_FATURAME, TABF.VALOR_DO_SINAL, TABF.INFORMAR_COMAR, TABF.DATA_APROVACAO, TABF.HAVERA_BONIFICACAO, TABF.VALOR_BONIFICACAO, TABF.CODIGO_FINAME, TABF.SERA_DESMEMBRADO, TABF.DESCONTO_INCODICIONA, 
             TABF.NR_NOTA_FISCAL_DESCO, TABF.NUMERO_OS_AGREGA_DES, TABF.CHASSI_DESCONTO_INCO, TABF.FAT_CENTRO_DE_CUSTO, TABF.NF_REFATURAMENTO_AMS, TABF.QUANTIDADE_DE_ITENS, TABF.CHASSI_DO_ITEM_AMS_2, TABF.CHASSI_DO_ITEM_AMS_3, 
             TABF.CHASSI_DO_ITEM_AMS_4, TABF.CHASSI_DO_ITEM_AMS_5, TABF.CHASSI_DO_ITEM_AMS_6, TABF.CHASSI_DO_ITEM_AMS_7, TABF.CHASI_DO_ITEM_AMS_8, TABF.CHASSI_DO_ITEM_AMS_9, TABF.CHASSI_DO_ITEM_AMS10, TABF.OS_ADICIONAIS, 
             TABF.DESCONTO_INCODICION, TABF.SINAL_EMBUTIDO, TABF.ID_CONTROLADORA, TABF.ID_MONITOR_2, TABF.ID_MONITOR_1
FROM   dbo.IV_Q_VENDA_AMS AS TABF INNER JOIN
             dbo.IV_Questionario AS QST ON QST.SeqQuestionario = TABF.SEQQUESTIONARIO INNER JOIN
             dbo.IV_Formulario AS FRM ON FRM.SeqFormulario = QST.SeqFormulario INNER JOIN
             dbo.GE_Pessoa AS TBASE ON TBASE.SeqPessoa = QST.SeqPessoa
