/* ==============================================================
   Objeto ..........: dbo.IV_Q$VP_COLHEDORA
   Tipo ............: VIEW
   Criado em .......: 2025-09-09 10:21:39
   Modificado em ...: 2025-09-09 10:21:39
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VP_COLHEDORA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VP_COLHEDORA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VP_CH_TIPO, VP_CH_MARCA_CONC, VP_CH_MODELO_CONC, VP_CH_QTDE, VP_CH_RODADO, VP_CH_TECNOLOGIA, VP_ITENS_TECNOLOGIA, VP_CH_PRECO_CONC, VP_CH_MODELO_JD, VP_CH_PRECO_JD)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VP_CH_TIPO, TABF.VP_CH_MARCA_CONC, TABF.VP_CH_MODELO_CONC, TABF.VP_CH_QTDE, TABF.VP_CH_RODADO, TABF.VP_CH_TECNOLOGIA, TABF.VP_ITENS_TECNOLOGIA, TABF.VP_CH_PRECO_CONC, TABF.VP_CH_MODELO_JD, TABF.VP_CH_PRECO_JD   FROM IV_Q_VP_COLHEDORA TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  