/* ==============================================================
   Objeto ..........: dbo.IV_Q$PEDIDO_SAM
   Tipo ............: VIEW
   Criado em .......: 2026-04-01 14:26:24
   Modificado em ...: 2026-04-01 14:26:24
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_PEDIDO_SAM, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$PEDIDO_SAM ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MODELO_DO_PRODUTO, QUANTIDADE, PRECO, COTACAO_MODELO, CNPJ_CPF, INSCRICAO_ESTADUAL, CONDICAO_DE_PAGAMENT, PRAZO_DE_ENTREGA, COMISSAO, SINAL, _SINAL, DATA_VENCIMENTO_SINA, SALDO, BANCO, BONIFICACAO, TIPO_DE_VENDA, TIPO_EQUIPAMENTO, MARCA_EQUIPAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MODELO_DO_PRODUTO, TABF.QUANTIDADE, TABF.PRECO, TABF.COTACAO_MODELO, TABF.CNPJ_CPF, TABF.INSCRICAO_ESTADUAL, TABF.CONDICAO_DE_PAGAMENT, TABF.PRAZO_DE_ENTREGA, TABF.COMISSAO, TABF.SINAL, TABF._SINAL, TABF.DATA_VENCIMENTO_SINA, TABF.SALDO, TABF.BANCO, TABF.BONIFICACAO, TABF.TIPO_DE_VENDA, TABF.TIPO_EQUIPAMENTO, TABF.MARCA_EQUIPAMENTO   FROM IV_Q_PEDIDO_SAM TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  