/* ==============================================================
   Objeto ..........: dbo.IV_Q$OFERECE_RENOV_SEGURO
   Tipo ............: VIEW
   Criado em .......: 2024-12-27 08:29:08
   Modificado em ...: 2024-12-27 08:29:08
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_OFERECE_RENOV_SEGURO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$OFERECE_RENOV_SEGURO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SEGURADORA, CORRETORA, APOLICE, VIGENCIA_INICIO, VIGENCIA_TERMINO, PREMIO_LIQUIDO, QDE_PARCELAS, VALOR_PARCELA, DATA_VENCTO_PRIMEIRA, PART_PORCENT, NUM_PARCELA, VALOR_PAGO, HOUVE_SINISTRO, DATA_SINISTRO_UM, DATA_SINISTRO_DOIS)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SEGURADORA, TABF.CORRETORA, TABF.APOLICE, TABF.VIGENCIA_INICIO, TABF.VIGENCIA_TERMINO, TABF.PREMIO_LIQUIDO, TABF.QDE_PARCELAS, TABF.VALOR_PARCELA, TABF.DATA_VENCTO_PRIMEIRA, TABF.PART_PORCENT, TABF.NUM_PARCELA, TABF.VALOR_PAGO, TABF.HOUVE_SINISTRO, TABF.DATA_SINISTRO_UM, TABF.DATA_SINISTRO_DOIS   FROM IV_Q_OFERECE_RENOV_SEGURO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  