/* ==============================================================
   Objeto ..........: dbo.IV_Q$SEPARACAO_PEDIDO
   Tipo ............: VIEW
   Criado em .......: 2025-09-29 10:53:33
   Modificado em ...: 2025-09-29 10:53:33
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_SEPARACAO_PEDIDO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$SEPARACAO_PEDIDO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , GC_PEDIDO_PARA, GC_TIPO_EQUIP, GC_MARCA_EQUIP, GC_MODELO_EQUIP, GC_QTDE_TOTAL, UNIDADE_1, QUANTIDADE_1, UNIDADE_2, QUANTIDADE_2, UNIDADE_3, QUANTIDADE_3, UNIDADE_4, QUANTIDADE_4, UNIDADE_5, QUANTIDADE_5, UNIDADE_6, QUANTIDADE_6)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.GC_PEDIDO_PARA, TABF.GC_TIPO_EQUIP, TABF.GC_MARCA_EQUIP, TABF.GC_MODELO_EQUIP, TABF.GC_QTDE_TOTAL, TABF.UNIDADE_1, TABF.QUANTIDADE_1, TABF.UNIDADE_2, TABF.QUANTIDADE_2, TABF.UNIDADE_3, TABF.QUANTIDADE_3, TABF.UNIDADE_4, TABF.QUANTIDADE_4, TABF.UNIDADE_5, TABF.QUANTIDADE_5, TABF.UNIDADE_6, TABF.QUANTIDADE_6   FROM IV_Q_SEPARACAO_PEDIDO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  