/* ==============================================================
   Objeto ..........: dbo.IV_Q$AFERICAO_MAQ_1_WEB
   Tipo ............: VIEW
   Criado em .......: 2020-07-23 17:25:17
   Modificado em ...: 2020-07-23 17:25:17
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AFERICAO_MAQ_1_WEB, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AFERICAO_MAQ_1_WEB ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFEITO_VENDA, ATENDEU_NEGOCIACAO, FOI_CUMPRIDO, PROGRAMA_DEMONSTRACA, PROCESSO_FINANCEIRO, PRAZO_ENTREGA, ENTREGA_TECNICA, NPS_MAQUINA)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFEITO_VENDA, TABF.ATENDEU_NEGOCIACAO, TABF.FOI_CUMPRIDO, TABF.PROGRAMA_DEMONSTRACA, TABF.PROCESSO_FINANCEIRO, TABF.PRAZO_ENTREGA, TABF.ENTREGA_TECNICA, TABF.NPS_MAQUINA    FROM IV_Q_AFERICAO_MAQ_1_WEB TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 