/* ==============================================================
   Objeto ..........: dbo.IV_Q$RESULTADO_DEMO
   Tipo ............: VIEW
   Criado em .......: 2021-02-14 11:36:27
   Modificado em ...: 2021-02-14 11:36:27
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_RESULTADO_DEMO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$RESULTADO_DEMO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , SATISFACAO_DO_CLIENT, COMENTARIO_DO_CLIENT, FORMAS_DE_MEDICAO, CONSUMO_DIESEL, CONSUMO_ESPECIFICO, CAPACIDADE_OPERACION, AREA_TRABALHADA, HORIMETRO_INICIAL, HORIMETRO_FINAL, TOTAL_HORAS_TRABALHA, AREA_TOTAL_TRABALHAD, RENDIMENTO_OPERACION, COMBUSTIVEL_CONSUMID, MEDIA_CONSUMO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.SATISFACAO_DO_CLIENT, TABF.COMENTARIO_DO_CLIENT, TABF.FORMAS_DE_MEDICAO, TABF.CONSUMO_DIESEL, TABF.CONSUMO_ESPECIFICO, TABF.CAPACIDADE_OPERACION, TABF.AREA_TRABALHADA, TABF.HORIMETRO_INICIAL, TABF.HORIMETRO_FINAL, TABF.TOTAL_HORAS_TRABALHA, TABF.AREA_TOTAL_TRABALHAD, TABF.RENDIMENTO_OPERACION, TABF.COMBUSTIVEL_CONSUMID, TABF.MEDIA_CONSUMO    FROM IV_Q_RESULTADO_DEMO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 