/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_TESTE
   Tipo ............: VIEW
   Criado em .......: 2024-09-13 10:34:55
   Modificado em ...: 2024-09-13 10:34:55
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_TESTE, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_TESTE ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_EQUIP, MARCA_EQUIP, MODELO_EQUIP, CODIGO_DO_MODELO, QTDE_EQUIP, REVENDA_EQUIP, DATA_VENDA, PRECO_CONC, PRECO_JD, MODELO_JD, MOTIVO_VENDA_PERDIDA)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_EQUIP, TABF.MARCA_EQUIP, TABF.MODELO_EQUIP, TABF.CODIGO_DO_MODELO, TABF.QTDE_EQUIP, TABF.REVENDA_EQUIP, TABF.DATA_VENDA, TABF.PRECO_CONC, TABF.PRECO_JD, TABF.MODELO_JD, TABF.MOTIVO_VENDA_PERDIDA   FROM IV_Q_VENDA_PERDIDA_TESTE TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  