/* ==============================================================
   Objeto ..........: dbo.IV_Q$ACOMP_VENDA_LOCACAO
   Tipo ............: VIEW
   Criado em .......: 2017-11-09 11:52:25
   Modificado em ...: 2017-11-09 11:52:25
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ACOMP_VENDA_LOCACAO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$ACOMP_VENDA_LOCACAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_DE_EQUIPAMENTO, MARCA, MODELO_DO_EQUIPAMENT, TIPO_DE_TORRE, TIPO_DE_RODADO, BITOLA, ACESSORIOS, IMPLEMENTOS, EASY_MANAGER___COMPU, VALOR_TOTAL_DA_NEGOC, DATA_INICIO_DA_LOCAC, DATA_TERMINO_LOCACAO, QUANTIDADE_DE_EQUIPA)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_DE_EQUIPAMENTO, TABF.MARCA, TABF.MODELO_DO_EQUIPAMENT, TABF.TIPO_DE_TORRE, TABF.TIPO_DE_RODADO, TABF.BITOLA, TABF.ACESSORIOS, TABF.IMPLEMENTOS, TABF.EASY_MANAGER___COMPU, TABF.VALOR_TOTAL_DA_NEGOC, TABF.DATA_INICIO_DA_LOCAC, TABF.DATA_TERMINO_LOCACAO, TABF.QUANTIDADE_DE_EQUIPA    FROM IV_Q_ACOMP_VENDA_LOCACAO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 