/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_IMPLEM
   Tipo ............: VIEW
   Criado em .......: 2015-05-28 09:20:11
   Modificado em ...: 2016-03-22 19:20:04
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_IMPLEM, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_IMPLEM ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , MARCA_VC_IMPL, REVENDA_CONC_IMPL, DTA_DA_VENDA, QUANTIDADE_IMPLEMENT, PRECO_CONC, PRECO_JD, MODELO_JD_IMPL, MOTIVO_VD_IMP)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.MARCA_VC_IMPL, TABF.REVENDA_CONC_IMPL, TABF.DTA_DA_VENDA, TABF.QUANTIDADE_IMPLEMENT, TABF.PRECO_CONC, TABF.PRECO_JD, TABF.MODELO_JD_IMPL, TABF.MOTIVO_VD_IMP    FROM IV_Q_VENDA_PERDIDA_IMPLEM TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 