/* ==============================================================
   Objeto ..........: dbo.IV_Q$COMISSAO_VD_LOCACAO
   Tipo ............: VIEW
   Criado em .......: 2017-11-09 14:02:41
   Modificado em ...: 2017-11-09 14:02:41
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COMISSAO_VD_LOCACAO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COMISSAO_VD_LOCACAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , QUANTIDADE_DE_EQUIPA, TIPO_DE_EQUIPAMENTO, MARCA, MODELO_DO_EQUIPAMENT, ANO_MODELO_EQUIPAMEN, N__SERIE, HORIMETRO, DATA_INICIO_LOCACAO, DATA_TERMINO_LOCACAO, VALOR_MENSAL_DO_CONT, VALOR_TOTAL_DO_CONTR, DATA_RENOVACAO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.QUANTIDADE_DE_EQUIPA, TABF.TIPO_DE_EQUIPAMENTO, TABF.MARCA, TABF.MODELO_DO_EQUIPAMENT, TABF.ANO_MODELO_EQUIPAMEN, TABF.N__SERIE, TABF.HORIMETRO, TABF.DATA_INICIO_LOCACAO, TABF.DATA_TERMINO_LOCACAO, TABF.VALOR_MENSAL_DO_CONT, TABF.VALOR_TOTAL_DO_CONTR, TABF.DATA_RENOVACAO    FROM IV_Q_COMISSAO_VD_LOCACAO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 