/* ==============================================================
   Objeto ..........: dbo.IV_Q$VISITA_EXP_CLIENTE
   Tipo ............: VIEW
   Criado em .......: 2018-08-27 14:57:53
   Modificado em ...: 2018-08-27 14:57:53
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VISITA_EXP_CLIENTE, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VISITA_EXP_CLIENTE ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , FICOU_ALGUMA_DUVIDA_, O_EQUIPAMENTO_ESTA_F, TEM_ALGUM_PROBLEMA_N, O_SR_SABE_COM_QUEM_P, ALGO_FOI_PROMETIDO_N, DE_0_A_10_QUAL_NOTA_, O_QUE_O_SR__A__ESPER, O_QUE_A_COLORADO_MAQ, COMO_ESTA_NOSSO_ATEN, SERVICOS)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.FICOU_ALGUMA_DUVIDA_, TABF.O_EQUIPAMENTO_ESTA_F, TABF.TEM_ALGUM_PROBLEMA_N, TABF.O_SR_SABE_COM_QUEM_P, TABF.ALGO_FOI_PROMETIDO_N, TABF.DE_0_A_10_QUAL_NOTA_, TABF.O_QUE_O_SR__A__ESPER, TABF.O_QUE_A_COLORADO_MAQ, TABF.COMO_ESTA_NOSSO_ATEN, TABF.SERVICOS    FROM IV_Q_VISITA_EXP_CLIENTE TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 