/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_PERDIDA_MANITO
   Tipo ............: VIEW
   Criado em .......: 2017-06-05 08:37:45
   Modificado em ...: 2017-06-05 08:37:45
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_PERDIDA_MANITO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_PERDIDA_MANITO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , PART_NEG, REVENDA_GANH, MOD_EQUIP, DT_VENDA, QUANTIDAD, PRECO_CONC, PRECO_COL_EQ, MODELO_COLORADO_EQUI, MOTIVO_EQ)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.PART_NEG, TABF.REVENDA_GANH, TABF.MOD_EQUIP, TABF.DT_VENDA, TABF.QUANTIDAD, TABF.PRECO_CONC, TABF.PRECO_COL_EQ, TABF.MODELO_COLORADO_EQUI, TABF.MOTIVO_EQ    FROM IV_Q_VENDA_PERDIDA_MANITO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 