/* ==============================================================
   Objeto ..........: dbo.IV_Q$RECEBIMENTO_A_PRAZO
   Tipo ............: VIEW
   Criado em .......: 2025-04-11 14:51:39
   Modificado em ...: 2025-04-11 14:51:39
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_RECEBIMENTO_A_PRAZO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$RECEBIMENTO_A_PRAZO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , RECEBIMENTO_NOME_CLI, RECEBIMENTO_CPF_CNPJ, RECEBIMENTO_CIDADE, RECEBIMENTO_ENDERECO, RECEBIMENTO_NUMERO, RECEBIMENTO_BAIRRO, RECEBIMENTO_CEP, RECEBIMENTO_AVALISTA, RECEBIMENTO_CPF_AVAL, RECEBIMENTO_RG_AVALI, RECEBIMENTO_END_AVAL, RECEBIMENTO_FORMA_PA, RECEBIMENTO_EMAIL, RECEBIMENTO_EMAIL_2, RECEBIMENTO_MARGEM, RECEBIMENTO_TEMPO_ES)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.RECEBIMENTO_NOME_CLI, TABF.RECEBIMENTO_CPF_CNPJ, TABF.RECEBIMENTO_CIDADE, TABF.RECEBIMENTO_ENDERECO, TABF.RECEBIMENTO_NUMERO, TABF.RECEBIMENTO_BAIRRO, TABF.RECEBIMENTO_CEP, TABF.RECEBIMENTO_AVALISTA, TABF.RECEBIMENTO_CPF_AVAL, TABF.RECEBIMENTO_RG_AVALI, TABF.RECEBIMENTO_END_AVAL, TABF.RECEBIMENTO_FORMA_PA, TABF.RECEBIMENTO_EMAIL, TABF.RECEBIMENTO_EMAIL_2, TABF.RECEBIMENTO_MARGEM, TABF.RECEBIMENTO_TEMPO_ES   FROM IV_Q_RECEBIMENTO_A_PRAZO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  