/* ==============================================================
   Objeto ..........: dbo.IV_Q$AVAL_USADO_ENTRADA
   Tipo ............: VIEW
   Criado em .......: 2022-06-10 10:13:28
   Modificado em ...: 2022-06-10 10:13:28
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_AVAL_USADO_ENTRADA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$AVAL_USADO_ENTRADA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , EQUIPAMENTO, MARCA, MODELO, VALOR_USADO, VALOR_AVALIACAO_USAD, RETIRADO_DO_USADO, CHASSI, VALOR_VALIDACAO_GEST, ENTRADA_DO_USADO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.EQUIPAMENTO, TABF.MARCA, TABF.MODELO, TABF.VALOR_USADO, TABF.VALOR_AVALIACAO_USAD, TABF.RETIRADO_DO_USADO, TABF.CHASSI, TABF.VALOR_VALIDACAO_GEST, TABF.ENTRADA_DO_USADO    FROM IV_Q_AVAL_USADO_ENTRADA TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 