/* ==============================================================
   Objeto ..........: dbo.IV_Q$COMISSAO_LOCACAO
   Tipo ............: VIEW
   Criado em .......: 2017-11-06 17:39:31
   Modificado em ...: 2017-11-06 17:39:31
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_QUESTIONARIO
   Outras refs .....: IV_Q_COMISSAO_LOCACAO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COMISSAO_LOCACAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TIPO_DE_EQUIPAMENTO_, MARCA, MODELO_DO_EQUIPAMENT, CHASSI, ANO_MODELO_EQUIPAMEN, HORIMETRO, DATA_INICIO_LOCACAO, DATA_TERMINO_LOCACAO, VALOR_MENSAL_DO_CONT, VALOR_TOTAL_DO_CONTR, DATA_RENOVACAO, QUANTIDADE_DE_EQUIPA)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TIPO_DE_EQUIPAMENTO_, TABF.MARCA, TABF.MODELO_DO_EQUIPAMENT, TABF.CHASSI, TABF.ANO_MODELO_EQUIPAMEN, TABF.HORIMETRO, TABF.DATA_INICIO_LOCACAO, TABF.DATA_TERMINO_LOCACAO, TABF.VALOR_MENSAL_DO_CONT, TABF.VALOR_TOTAL_DO_CONTR, TABF.DATA_RENOVACAO, TABF.QUANTIDADE_DE_EQUIPA    FROM IV_Q_COMISSAO_LOCACAO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 