/* ==============================================================
   Objeto ..........: dbo.IV_Q$LICENCAS_PUK
   Tipo ............: VIEW
   Criado em .......: 2026-02-12 11:07:33
   Modificado em ...: 2026-02-12 11:07:33
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_LICENCAS_PUK, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$LICENCAS_PUK ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CHASSI_MAQUINA, LICENCA_RECEPTOR, CHASSI_RECEPTOR, VALOR_RECEPTOR, CODIGO_RECEPTOR, LICENCA_MONITOR, CHASSI_MONITOR, VALOR_MONITOR, CODIGO_MONITOR, VALOR_TOTAL, FORMA_PAGAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CHASSI_MAQUINA, TABF.LICENCA_RECEPTOR, TABF.CHASSI_RECEPTOR, TABF.VALOR_RECEPTOR, TABF.CODIGO_RECEPTOR, TABF.LICENCA_MONITOR, TABF.CHASSI_MONITOR, TABF.VALOR_MONITOR, TABF.CODIGO_MONITOR, TABF.VALOR_TOTAL, TABF.FORMA_PAGAMENTO   FROM IV_Q_LICENCAS_PUK TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  