/* ==============================================================
   Objeto ..........: dbo.IV_Q$SOLICITACAO_TCAT
   Tipo ............: VIEW
   Criado em .......: 2024-11-25 14:56:44
   Modificado em ...: 2024-11-25 14:56:44
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_SOLICITACAO_TCAT, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$SOLICITACAO_TCAT ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , TCAT_DATA_SINISTRO, TCAT_TRANSPORTADORA, TCAT_CTRE, TCAT_MOTORISTA, TCAT_CNH_MOTORISTA, TCAT_PLACA_CAVALO, TCAT_PLACA_CARRETA, TCAT_NF_EQUIPAMENTO, TCAT_DATA_NF, TCAT_VALOR_NF, TCAT_ORIGEM, TCAT_DESTINO, TCAT_EQUIPAMENTO, TCAT_ANO_EQUIPAMENTO, TCAT_CHASSIS_EQUIP, TCAT_OCORRENCIA, TCAT_CAUSA, TCAT_ORIGEM_AVARIA, TCAT_DESCRICAO, TCAT_VALORES_PECAS, TCAT_VALORES_OBRA)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.TCAT_DATA_SINISTRO, TABF.TCAT_TRANSPORTADORA, TABF.TCAT_CTRE, TABF.TCAT_MOTORISTA, TABF.TCAT_CNH_MOTORISTA, TABF.TCAT_PLACA_CAVALO, TABF.TCAT_PLACA_CARRETA, TABF.TCAT_NF_EQUIPAMENTO, TABF.TCAT_DATA_NF, TABF.TCAT_VALOR_NF, TABF.TCAT_ORIGEM, TABF.TCAT_DESTINO, TABF.TCAT_EQUIPAMENTO, TABF.TCAT_ANO_EQUIPAMENTO, TABF.TCAT_CHASSIS_EQUIP, TABF.TCAT_OCORRENCIA, TABF.TCAT_CAUSA, TABF.TCAT_ORIGEM_AVARIA, TABF.TCAT_DESCRICAO, TABF.TCAT_VALORES_PECAS, TABF.TCAT_VALORES_OBRA   FROM IV_Q_SOLICITACAO_TCAT TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  