/* ==============================================================
   Objeto ..........: dbo.IV_Q$PEDIDO_GC
   Tipo ............: VIEW
   Criado em .......: 2025-10-01 09:05:28
   Modificado em ...: 2025-10-01 09:05:28
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_PEDIDO_GC, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$PEDIDO_GC ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , GC_TIPO_EQUIPAMENTO, GC_MODELO_EQUIPAMENT, GC_PRECO_UNITARIO, GC_QUANTIDADE, GC_PRECO_TOTAL, GC_ENTREGA, GC_BONIFICACAO, GC_ITENS_BONIFICADOS, GC_COMISSAO, GC_TECNOLOGIA, GC_ITENS_TECNOLOGIA)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.GC_TIPO_EQUIPAMENTO, TABF.GC_MODELO_EQUIPAMENT, TABF.GC_PRECO_UNITARIO, TABF.GC_QUANTIDADE, TABF.GC_PRECO_TOTAL, TABF.GC_ENTREGA, TABF.GC_BONIFICACAO, TABF.GC_ITENS_BONIFICADOS, TABF.GC_COMISSAO, TABF.GC_TECNOLOGIA, TABF.GC_ITENS_TECNOLOGIA   FROM IV_Q_PEDIDO_GC TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  