/* ==============================================================
   Objeto ..........: dbo.IV_Q$ATUALIZACAO_PUK
   Tipo ............: VIEW
   Criado em .......: 2026-02-10 17:05:16
   Modificado em ...: 2026-02-10 17:05:16
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ATUALIZACAO_PUK, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$ATUALIZACAO_PUK ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , CHASSI_DA_MAQUINA_, VALOR_ATUALIZACAO_DO, CHASSI_DO_RECEPTOR, VALOR_MONITOR, CHASSI_DO_MONITOR, VALOR_MODEM, CHASSI_MODEM, VALOR_TOTAL, FORMA_DE_PAGAMENTO)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.CHASSI_DA_MAQUINA_, TABF.VALOR_ATUALIZACAO_DO, TABF.CHASSI_DO_RECEPTOR, TABF.VALOR_MONITOR, TABF.CHASSI_DO_MONITOR, TABF.VALOR_MODEM, TABF.CHASSI_MODEM, TABF.VALOR_TOTAL, TABF.FORMA_DE_PAGAMENTO   FROM IV_Q_ATUALIZACAO_PUK TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  