/* ==============================================================
   Objeto ..........: dbo.IV_Q$VENDA_DIRETA
   Tipo ............: VIEW
   Criado em .......: 2025-05-19 16:27:06
   Modificado em ...: 2025-05-19 16:27:06
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_VENDA_DIRETA, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$VENDA_DIRETA ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , VD_TIRADO_PARA, VD_NRO_COTACAO, VD_NRO_PEDIDO_VENDA, VD_DATA_PEDIDO_VEND, VD_TIPO_EQUIP, VD_MARCA_EQUIP, VD_MODELO_EQUIP, VD_VALOR_TOTAL, VD_BONIFICACAO, VD_COMISSAO, VD_EMAIL_NF)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.VD_TIRADO_PARA, TABF.VD_NRO_COTACAO, TABF.VD_NRO_PEDIDO_VENDA, TABF.VD_DATA_PEDIDO_VEND, TABF.VD_TIPO_EQUIP, TABF.VD_MARCA_EQUIP, TABF.VD_MODELO_EQUIP, TABF.VD_VALOR_TOTAL, TABF.VD_BONIFICACAO, TABF.VD_COMISSAO, TABF.VD_EMAIL_NF   FROM IV_Q_VENDA_DIRETA TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  