/* ==============================================================
   Objeto ..........: dbo.IV_Q$COM_INTERESSE_FUTURO
   Tipo ............: VIEW
   Criado em .......: 2026-03-31 13:50:17
   Modificado em ...: 2026-03-31 13:50:17
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_COM_INTERESSE_FUTURO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$COM_INTERESSE_FUTURO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario, DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao, SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , INTERESSE_F_TIPO_NEG, INTERESSE_F_TIPO_EQ, INTERESSE_F_MARCA_EQ, INTERESSE_F_MODELO, INTERESSE_F_COMPRA, INTERESSE_F_NIVEL, INTERESSE_F_MOTIVO, INTERESSE_F_VALOR)    AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO, QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS, QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO, QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.INTERESSE_F_TIPO_NEG, TABF.INTERESSE_F_TIPO_EQ, TABF.INTERESSE_F_MARCA_EQ, TABF.INTERESSE_F_MODELO, TABF.INTERESSE_F_COMPRA, TABF.INTERESSE_F_NIVEL, TABF.INTERESSE_F_MOTIVO, TABF.INTERESSE_F_VALOR   FROM IV_Q_COM_INTERESSE_FUTURO TABF 	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO 	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA  