/* ==============================================================
   Objeto ..........: dbo.IV_Q$EVENTOS_AFERICAO
   Tipo ............: VIEW
   Criado em .......: 2023-04-17 12:06:11
   Modificado em ...: 2023-04-17 12:06:11
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_EVENTOS_AFERICAO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE VIEW dbo.IV_Q$EVENTOS_AFERICAO ( SeqPessoa, Pessoa, SeqQuestionario, SeqFormulario, Formulario,  DtaRealizacao, UsuInclusao, DtaAlteracao, UsuAlteracao,  Observacao,  SeqHistorico, Resultado, Processo, Departamento, LinkDocto, LinkNro, LinkSerie , QUAL_EVENTO, O_SR_A___GOSTOU_DO_N, COMO_O_SR_A___SOUBE_, TEM_ALGUMA_SUGESTAO_, COM_BASE_NO_ULTIMO_E, DE_MODO_GERAL_A_FEIR, TEM_UMA_VISITA_AGEND, DESEJA_AGENDAR_UMA_V, A_DATA_E_DURACAO_DO_, O_HORARIO_FOI_CONVEN, DE_FORMA_GERAL__COMO)     AS SELECT TBASE.SEQPESSOA, TBASE.NOMERAZAO, QST.SEQQUESTIONARIO, FRM.SEQFORMULARIO, FRM.DESCRICAO,  QST.DTAREALIZACAO, QST.USUINCLUSAO, QST.DTAALTERACAO, QST.USUALTERACAO, QST.OBS,  QST.SEQHISTORICO, QST.RESULTADO, QST.PROCESSO, QST.DEPARTAMENTO,  QST.LINKDOCTO, QST.LINKNRO, QST.LINKSERIE , TABF.QUAL_EVENTO, TABF.O_SR_A___GOSTOU_DO_N, TABF.COMO_O_SR_A___SOUBE_, TABF.TEM_ALGUMA_SUGESTAO_, TABF.COM_BASE_NO_ULTIMO_E, TABF.DE_MODO_GERAL_A_FEIR, TABF.TEM_UMA_VISITA_AGEND, TABF.DESEJA_AGENDAR_UMA_V, TABF.A_DATA_E_DURACAO_DO_, TABF.O_HORARIO_FOI_CONVEN, TABF.DE_FORMA_GERAL__COMO    FROM IV_Q_EVENTOS_AFERICAO TABF  	JOIN IV_QUESTIONARIO QST ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO  	JOIN IV_FORMULARIO FRM ON   FRM.SEQFORMULARIO = QST.SEQFORMULARIO  	JOIN GE_PESSOA TBASE ON TBASE.SEQPESSOA = QST.SEQPESSOA 