/* ==============================================================
   Objeto ..........: dbo.IV_Q$ADM_FINANCEIRO_N
   Tipo ............: VIEW
   Criado em .......: 2024-03-08 17:17:10
   Modificado em ...: 2024-03-08 17:17:10
   Linhas ..........: 86
   Escreve em tabela: nao
   Tabelas referidas: GE_PESSOA, IV_FORMULARIO, IV_Q_ADM_FINANCEIRO, IV_QUESTIONARIO
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

/*
VIEW CRIADA POR FELIPE VIOLIN - NO DIA 08/03/2024
A VIEW FOI CRIADA PARA REPLICAÇÃO DO RELATÓRIO 101X DA ITAETÉ
SOLICITANTE DO PROJETO = Adilson Jose da Cruz

select * from IV_Q$VENDA_N

*/

CREATE   VIEW IV_Q$ADM_FINANCEIRO_N AS 



SELECT 
	TBASE.SEQPESSOA, 
	TBASE.NOMERAZAO, 
	QST.SEQQUESTIONARIO, 
	FRM.SEQFORMULARIO, 
	FRM.DESCRICAO, 
	QST.DTAREALIZACAO, 
	QST.USUINCLUSAO, 
	QST.DTAALTERACAO, 
	QST.USUALTERACAO, 
	QST.OBS, 
	QST.SEQHISTORICO, 
	QST.RESULTADO, 
	QST.PROCESSO, 
	QST.DEPARTAMENTO, 
	QST.LINKDOCTO, 
	QST.LINKNRO, 
	QST.LINKSERIE, 
	TABF.CNPJ_CPF_DO_COMPRADO			as CNPJ_CPF_DO_COMPRADO, 
	TABF.AGENCIA						as AGENCIA,
	--TABF.NOME_GERENTE, 
	''									as NOME_GERENTE, 
	--TABF.TELEFONE_DA_AGENCI, 
	''									as TELEFONE_DA_AGENCI, 
	cast(TABF.PFA___PREVISAO_DE_FA as date) 	
										as MES_PREVISTO, 
	--TABF.NRO_COTACAO, 
	''									as NRO_COTACAO, 						
	--TABF.FDD, 
	''									as FDD,
	--TABF.PROBABILIDADE_APR, 
	''									as PROBABILIDADE_APR,
	--TABF.ORIGEM_FATURAMENTO, 
	''									as ORIGEM_FATURAMENTO,
	TABF.NRO_CHASSI						as NRO_CHASSI, 
	TABF.DATA_PROTOCOLO_NO_BA 			as PROTOCOLO_BANCO, 
	--TABF.APROVACAO_CREDITO, 
	''									as APROVACAO_CREDITO,
	--TABF.DTA_REGISTRO_CED,
	''									as DTA_REGISTRO_CED,
	TABF.DATA_AUTORIZACAO_FAT			as AUTORIZACAO_FAT, 
	--TABF.DATA_PAC,
	'' 									as DATA_PAC,
	TABF.DATA_FATURAMENTO				as DTA_FATURAMENTO, 
	TABF.NRO_NF							as NRO_NF, 
	--TABF.LOCAL_ENTREGA, 
	''									as LOCAL_ENTREGA, 
	--TABF.PREV_RECBTO,
	''									as PREV_RECBTO,
	--TABF.DTA_ENTREGA, 
	''									as DTA_ENTREGA, 
	TABF.NUMERO_DA_PROPOSTA				as NUMERO_DA_PROPOSTA, 
	TABF.DATA_LIBERACAO_DO_RE			as DTA_LIB_RECURSO, 
	TABF.VALOR_RECEBIDO					as VALOR_RECEBIDO, 
	--TABF.MARCADO_ENTREGUE, 
	''									as MARCADO_ENTREGUE, 
	--TABF.DATA_PENHOR, 
	''									as DATA_PENHOR, 
	--TABF.DATA_INCENTIVO, 
	''									as DATA_INCENTIVO, 
	TABF.DATA_DA_PROPOSTA				as DTA_PROPOSTA, 
	TABF.PFA___PREVISAO_DE_FA			as PFA, 
	--TABF.DTA_CCB_EMITIDA, 
	''									as DTA_CCB_EMITIDA, 
	--TABF.NRO_PAC, 
	''									as NRO_PAC,
	TABF.NUMERO_DA_PROPOSTA				as NRO_PROPOSTA   
FROM 
		IV_Q_ADM_FINANCEIRO	TABF 
JOIN 	IV_QUESTIONARIO 	QST 	ON QST.SEQQUESTIONARIO =  TABF.SEQQUESTIONARIO 
JOIN 	IV_FORMULARIO 		FRM 	ON FRM.SEQFORMULARIO = QST.SEQFORMULARIO 
JOIN 	GE_PESSOA 			TBASE 	ON TBASE.SEQPESSOA = QST.SEQPESSOA 
