/* ==============================================================
   Objeto ..........: dbo.V_C5SYSPK
   Tipo ............: VIEW
   Criado em .......: 2025-02-17 17:35:37
   Modificado em ...: 2025-02-17 17:35:37
   Linhas ..........: 1
   Escreve em tabela: nao
   Tabelas referidas: (nenhuma)
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

 Create View V_C5SYSPK (TBDONO, TBNOME, COLNOME, POSICAO, PKNOME) as     select 		 USER_NAME(o.uid) as TBDONO, 		  convert(sysname, o.name ) as TBNAME, 		 convert(sysname,c.name)as COLNAME, 		case 				when c.name = index_col(o.name, i.indid,  1) then convert (smallint,1) 				when c.name = index_col(o.name, i.indid,  2) then convert (smallint,2) 				when c.name = index_col(o.name, i.indid,  3) then convert (smallint,3) 				when c.name = index_col(o.name, i.indid,  4) then convert (smallint,4) 				when c.name = index_col(o.name, i.indid,  5) then convert (smallint,5) 				when c.name = index_col(o.name, i.indid,  6) then convert (smallint,6) 				when c.name = index_col(o.name, i.indid,  7) then convert (smallint,7) 				when c.name = index_col(o.name, i.indid,  8) then convert (smallint,8) 				when c.name = index_col(o.name, i.indid,  9) then convert (smallint,9) 				when c.name = index_col(o.name, i.indid, 10) then convert (smallint,10) 				when c.name = index_col(o.name, i.indid, 11) then convert (smallint,11) 				when c.name = index_col(o.name, i.indid, 12) then convert (smallint,12) 				when c.name = index_col(o.name, i.indid, 13) then convert (smallint,13) 				when c.name = index_col(o.name, i.indid, 14) then convert (smallint,14) 				when c.name = index_col(o.name, i.indid, 15) then convert (smallint,15) 				when c.name = index_col(o.name, i.indid, 16) then convert (smallint,16) 			end as POSICAO, 		PKNAME = convert(sysname,i.name) 	from 		sysindexes i, syscolumns c, sysobjects o --, syscolumns c1 	where	o.id = c.id 		and o.id = i.id 		and (i.status & 0x800) = 0x800 		and    o.Type != 'S' 		and (c.name = index_col (o.name, i.indid,  1) or 		     c.name = index_col (o.name, i.indid,  2) or 		     c.name = index_col (o.name, i.indid,  3) or 		     c.name = index_col (o.name, i.indid,  4) or 		     c.name = index_col (o.name, i.indid,  5) or 		     c.name = index_col (o.name, i.indid,  6) or 		     c.name = index_col (o.name, i.indid,  7) or 		     c.name = index_col (o.name, i.indid,  8) or 		     c.name = index_col (o.name, i.indid,  9) or 		     c.name = index_col (o.name, i.indid, 10) or 		     c.name = index_col (o.name, i.indid, 11) or 		     c.name = index_col (o.name, i.indid, 12) or 		     c.name = index_col (o.name, i.indid, 13) or 		     c.name = index_col (o.name, i.indid, 14) or 		     c.name = index_col (o.name, i.indid, 15) or 		     c.name = index_col (o.name, i.indid, 16) 		    )   