/* ==============================================================
   Objeto ..........: dbo.VTC_Gera_REL_TBA101
   Tipo ............: SQL_STORED_PROCEDURE
   Criado em .......: 2025-10-29 18:31:23
   Modificado em ...: 2026-03-20 16:16:15
   Linhas ..........: 314
   Escreve em tabela: SIM (INSERT, DELETE)
   Alvos de escrita : IMP_REL_TBA101
   Tabelas referidas: IMP_REL_TBA101
   Fonte: banco CRM (Vortice CRM / Tracbel) - extracao somente leitura
   ============================================================== */

CREATE PROCEDURE [dbo].[VTC_Gera_REL_TBA101]
    @CODUSUARIO        NVARCHAR(50),
    @DT1               DATETIME2(0),
    @DT2               DATETIME2(0),
    @OPT1_ListChave    NVARCHAR(MAX),  -- ex: '759,282,283'
    @LS2_CMD           NVARCHAR(MAX) = N'', -- EMP.NOMEREDUZIDO opcional
    @LS1_CMD           NVARCHAR(MAX) = N'',
    @LS3_CMD           NVARCHAR(MAX) = N'',
    @LTA               NVARCHAR(MAX) = N'',
    @LTB               NVARCHAR(MAX) = N'',
    @Debug             BIT = 0
AS
BEGIN
    SET NOCOUNT ON;
	declare     @XI                NVARCHAR(1);

    DELETE FROM IMP_REL_TBA101 WHERE CODUSUARIO = @CODUSUARIO;

---	IF ISNULL(@LTB,    N'') <> N'' SET @LTB = N'FATURADO,CANCELADO,VENDA PERDIDA';
	SET @XI = '0';
	IF ISNULL(@LTB,    N'') <> N'' SET @XI = '1';

    IF OBJECT_ID('tempdb..#Stage') IS NOT NULL DROP TABLE #Stage;
    CREATE TABLE #Stage
    (
        EMPRESA NVARCHAR(120), CEN NVARCHAR(60), JD_QUOTE NVARCHAR(120),
        TIPO_VENDA NVARCHAR(120), TIPO_DE_EQUIPAMENTO NVARCHAR(120),
        MARCA NVARCHAR(120), MODELO NVARCHAR(200),
        SEQPESSOA INT, NOMERAZAO NVARCHAR(200), CNPJCPF NVARCHAR(32),
        LINHA_CREDITO NVARCHAR(120), INST_FINANCEIRA NVARCHAR(120),
        FINANC_CHASSI NVARCHAR(120), ULT_RESULTADO NVARCHAR(400),
        DTA_FATURAMENTO_D DATETIME, NF_N NVARCHAR(60),
        DTA_PED_D DATETIME, DTA_PRENCH_FORM_D DATETIME,
        VALOR_N DECIMAL(18,2), DTA_ULT_ANDAMENTO_D DATETIME,
        ULT_HISTORICO_L NVARCHAR(MAX), PROCESSO_N INT, CARTEIRA NVARCHAR(60),
        CIDADE NVARCHAR(150), DATA_PEDIDO_HIST_D DATETIME,
        CAMPANHA NVARCHAR(150), PROCESSODNA INT, DTAPROVADO NVARCHAR(10)
    );

    DECLARE @whereExtra NVARCHAR(MAX) = N'';
    IF ISNULL(@LS2_CMD,N'') <> N'' SET @whereExtra += N' AND EMP.NOMEREDUZIDO = @pLS2';
    IF ISNULL(@LS1_CMD,N'') <> N'' SET @whereExtra += NCHAR(10) + @LS1_CMD;
    IF ISNULL(@LS3_CMD,N'') <> N'' SET @whereExtra += NCHAR(10) + @LS3_CMD;
    IF ISNULL(@LTA,    N'') <> N'' SET @whereExtra += N' AND PRC.STATUS = @pLTA OR ADM.VENDA_FINANC_DATAENT IS NOT NULL   AND ADM.DtaRealizacao > CONVERT( DATE, ''16/03/2026'', 103)';
----    IF ISNULL(@LTB,    N'') <> N'' SET @whereExtra += N' AND PRC.STATUS NOT IN (@pLTB)';

    DECLARE @sql NVARCHAR(MAX) = N'
;WITH OptList AS
(
    -- Split de @OPT1_ListChave via XML (sem STRING_SPLIT)
    -- Exige lista no formato "759,282,283"
    SELECT DISTINCT CAST(T.N.value(''.'', ''int'') AS INT) AS SeqCarteira
    FROM (
        SELECT CAST(''<i>'' + REPLACE(@OPT1_ListChave, '','', ''</i><i>'') + ''</i>'' AS XML) AS X
    ) AS S
    CROSS APPLY S.X.nodes(''/i'') AS T(N)
)
INSERT INTO #Stage
(
    EMPRESA, CEN, JD_QUOTE, TIPO_VENDA, TIPO_DE_EQUIPAMENTO, MARCA, MODELO,
    SEQPESSOA, NOMERAZAO, CNPJCPF, LINHA_CREDITO, INST_FINANCEIRA, FINANC_CHASSI,
    ULT_RESULTADO, DTA_FATURAMENTO_D, NF_N, DTA_PED_D, DTA_PRENCH_FORM_D, VALOR_N,
    DTA_ULT_ANDAMENTO_D, ULT_HISTORICO_L, PROCESSO_N, CARTEIRA, CIDADE,
    DATA_PEDIDO_HIST_D, CAMPANHA, PROCESSODNA, DTAPROVADO
)
SELECT DISTINCT
       XA.EMPRESA, XA.CEN, XA.JD_QUOTE, XA.TIPO_VENDA, XA.TIPO_DE_EQUIPAMENTO,
       XA.MARCA, XA.MODELO, XA.SEQPESSOA, XA.NOMERAZAO, XA.CNPJCPF,
       XA.LINHA_CREDITO, XA.INST_FINANCEIRA, XA.FINANC_CHASSI,
       CASE WHEN XA.PROCESSO_N = XH2.PROCESSO THEN XA.ULT_RESULTADO
            ELSE XA2.Descricao + '' - '' + XR2.Descricao END,
       XA.DTA_FATURAMENTO_D, XA.NF_N, XA.DTA_PED_D, XA.DTA_PRENCH_FORM_D,
       XA.VALOR_N, XA.DTA_ULT_ANDAMENTO_D,
       CASE WHEN XA.PROCESSO_N = XH2.PROCESSO THEN XA.ULT_HISTORICO_L
            ELSE (SELECT TOP 1 XH3.DETALHE FROM IV_HISTORICO XH3
                  WHERE XH3.Processo = XP1.PROCESSODNA
                    AND XH3.DtaRealizacao = XP1.DTAPROCESSO) END,
       XA.PROCESSO_N, XA.CARTEIRA, XA.CIDADE, XA.DATA_PEDIDO_HIST_D,
       XA.CAMPANHA, XA.PROCESSODNA,
       (SELECT FORMAT(MAX(DTAREALIZACAO), ''dd/MM/yyyy'')
          FROM IV_PROCDADO PX
          JOIN IV_HISTORICO HX ON HX.Processo = PX.PROCESSO
         WHERE PX.ProcessoDNA = XA.PROCESSODNA
           AND HX.Resultado = 3239)
FROM (
    SELECT DISTINCT
           EMP.NOMEREDUZIDO AS EMPRESA,
       HIST.VENDEDOR AS CEN,
       VND.VENDA_JDQUOTE           AS JD_QUOTE,
       VND.VENDA_TIPO_VENDA        AS TIPO_VENDA,
       VND.VENDA_TIPO_EQUIPAMEN    AS TIPO_DE_EQUIPAMENTO,
       VND.VENDA_MARCA_EQUIPAME    AS MARCA,
       VND.VENDA_MODELO_EQUIPAM    AS MODELO,
       PES.SEQPESSOA               AS SEQPESSOA,
       CASE WHEN ISNULL(VND.VENDA_COMPRADOR,''@'')=''@'' OR VND.VENDA_COMPRADOR=''''
            THEN PES.NOMERAZAO ELSE VND.VENDA_COMPRADOR END AS NOMERAZAO,
       ISNULL(CAST(PES.NROCGCCPF AS VARCHAR(32)),'''') + ISNULL(CAST(PES.DIGCGCCPF AS VARCHAR(8)),'''') AS CNPJCPF,

       -- ESTES DOIS VÊM DO VND (mantendo nomes “finais” iguais aos usados fora):
       VND.VENDA_LINHA_CREDITO     AS LINHA_CREDITO,
       VND.VENDA_INST_FINANC       AS INST_FINANCEIRA,

       -- ESTE VEM DO ADM E PRECISA DO ALIAS EXATO ABAIXO:
       ADM.VENDA_FINANC_CHASSI     AS FINANC_CHASSI,

       ACA.Descricao + '' - '' + RES.Descricao AS ULT_RESULTADO,
       ADM.VENDA_FINANC_DATAFAT    AS DTA_FATURAMENTO_D,
       ADM.VENDA_FINANC_NRO_NF     AS NF_N,
       VND.VENDA_DATA_PEDIDO       AS DTA_PED_D,
       VND.DTAREALIZACAO           AS DTA_PRENCH_FORM_D,
       VND.VENDA_VALOR_TOTAL       AS VALOR_N,
       PDD.DTAULTRESULTADO         AS DTA_ULT_ANDAMENTO_D,
       HIST.DETALHE                AS ULT_HISTORICO_L,
       PRC.PROCESSO                AS PROCESSO_N,
       CASE WHEN ISNULL(RESP.CODUSUARIO,''@'')=''@'' AND ISNULL(RESP3.CODUSUARIO,''@'')=''@'' THEN ''<outro CEN>''
            WHEN ISNULL(RESP.CODUSUARIO,''@'')<>''@'' THEN RESP.CODUSUARIO
            WHEN ISNULL(RESP3.CODUSUARIO,''@'')<>''@'' THEN RESP3.CODUSUARIO END AS CARTEIRA,
       PES.CIDADE + '' - '' + PES.UF AS CIDADE,
       (SELECT MAX(HIST2.DTAREALIZACAO)
          FROM IV_HISTORICO HIST2
         WHERE HIST2.PROCESSO = PRC.PROCESSO
           AND HIST2.RESULTADO = 3231) AS DATA_PEDIDO_HIST_D,
       PDD.Campanha                 AS CAMPANHA,
       PDD.ProcessoDNA             AS PROCESSODNA
    FROM IV_PROCESSO PRC
    JOIN IV_PROCDADO PDD           ON PDD.PROCESSO = PRC.PROCESSO
    JOIN GE_EMPRESA   EMP          ON EMP.NROEMPRESA = PDD.NROEMPRESA
    JOIN GE_PESSOA    PES          ON PES.SEQPESSOA  = PDD.SEQPESSOA
    LEFT JOIN IV_Q$ACOMP_VENDA_FINANC ADM ON ADM.PROCESSO = PRC.PROCESSO
    JOIN (
        SELECT      
			VND2.PROCESSO,
			VND2.COTACAO_MODELO      AS VENDA_JDQUOTE,
			NULL                     AS VENDA_TIPO_VENDA,
			NULL                     AS VENDA_TIPO_EQUIPAMEN,
			NULL                     AS VENDA_MARCA_EQUIPAME,
			VND2.MODELO_DO_PRODUTO   AS VENDA_MODELO_EQUIPAM,
			NULL                     AS VENDA_COMPRADOR,
			NULL                     AS VENDA_LINHA_CREDITO,
			NULL                     AS VENDA_INST_FINANC,
			NULL                     AS VENDA_DATA_PEDIDO,
			VND2.DTAREALIZACAO,
			VND2.PRECO               AS VENDA_VALOR_TOTAL
          FROM IV_Q$PEDIDO_SAM VND2
        UNION
        SELECT  PPD2.PROCESSO, VND3.COTACAO_MODELO, NULL, NULL, NULL,
                VND3.MODELO_DO_PRODUTO, NULL, NULL, NULL, NULL,
                VND3.DTAREALIZACAO, VND3.PRECO
          FROM IV_Q$PEDIDO_SAM VND3
          JOIN IV_PROCDADO PPD2 ON PPD2.PROCESSODNA = VND3.PROCESSO
        UNION
        SELECT  VND4.PROCESSO, VND4.COTACAO_MODELO, NULL, NULL, NULL,
                VND4.MODELO_DO_PRODUTO, NULL, NULL, NULL, NULL,
                VND4.DTAREALIZACAO, VND4.PRECO
          FROM IV_Q$PEDIDO_KAM VND4
        UNION
        SELECT  PPD3.PROCESSO, VND5.COTACAO_MODELO, NULL, NULL, NULL,
                VND5.MODELO_DO_PRODUTO, NULL, NULL, NULL, NULL,
                VND5.DTAREALIZACAO, VND5.PRECO
          FROM IV_Q$PEDIDO_KAM VND5
          JOIN IV_PROCDADO PPD3 ON PPD3.PROCESSODNA = VND5.PROCESSO
    ) VND ON VND.PROCESSO = PRC.PROCESSO
    LEFT JOIN (SELECT HIS.PROCESSO, MAX(HIS.SEQHISTORICO) AS SEQ
               FROM IV_HISTORICO HIS GROUP BY HIS.PROCESSO) Q
           ON Q.PROCESSO = PDD.PROCESSODNA
    LEFT JOIN IV_HISTORICO HIST ON HIST.SEQHISTORICO = Q.SEQ
    JOIN IVS_PES IVP ON IVP.SEQPESSOA = PDD.SEQPESSOA AND IVP.SEQDEPTO IN (2,25)
    JOIN IVS_CARTEIRA CART ON CART.SEQCARTEIRA = IVP.SEQCARTEIRA
                          AND CART.SEQCARTEIRA IN (SELECT SeqCarteira FROM OptList)
    LEFT JOIN IV_RESULTADO RES ON RES.RESULTADO = HIST.RESULTADO
    LEFT JOIN IV_ACAO     ACA ON ACA.ACAO      = RES.ACAO
    LEFT JOIN IVS_PES IVP2       ON IVP2.SeqPessoa = PES.SeqPessoa AND IVP2.SeqDepto = 2
    LEFT JOIN IVS_CARTEIRA CART2 ON CART2.SeqCarteira = IVP2.SeqCarteira
    LEFT JOIN IVS_CartDepto CDEP ON CDEP.SeqDepto = 2 AND CART2.SeqCarteira = CDEP.SeqCarteira
    LEFT JOIN GE_USUARIO RESP    ON RESP.CODUSUARIO = HIST.VENDEDOR AND RESP.SEQUSUARIO = CART2.SeqUsrResp
    LEFT JOIN IVS_PES IVP3       ON IVP3.SeqPessoa = PES.SeqPessoa AND IVP3.SeqDepto = 25
    LEFT JOIN IVS_CARTEIRA CART3 ON CART3.SeqCarteira = IVP3.SeqCarteira
    LEFT JOIN IVS_CartDepto CDEP3 ON CDEP3.SeqDepto = 25 AND CART3.SeqCarteira = CDEP3.SeqCarteira
    LEFT JOIN GE_USUARIO RESP3   ON RESP3.CODUSUARIO = HIST.VENDEDOR AND RESP3.SEQUSUARIO = CART3.SeqUsrResp
    WHERE PDD.CODPROCESSO IN (31,41,50)
      AND VND.DTAREALIZACAO >= @DT1
      AND VND.DTAREALIZACAO <= @DT2
      AND PRC.STATUS NOT IN (''VENDA PERDIDA'',''DESISTIU DA COMPRA'',''CANCELADO'',''PEDIDO NÃO APROVADO'',''CREDITO NAO APROVADO'',''DEVOLVIDO'')
      AND PES.STATUS NOT IN (''F'')
      AND ( EXISTS (SELECT 1 FROM IV_HISTORICO WHERE RESULTADO IN (3232,3663) AND PROCESSO = PDD.PROCESSO)
         OR EXISTS (SELECT 1 FROM IV_HISTORICO H3
                     JOIN IV_PROCDADO P3 ON H3.Processo = P3.ProcessoDNA
                    WHERE H3.RESULTADO IN (3232,3663) AND P3.PROCESSO = PDD.PROCESSO)
      )' + @whereExtra + N'

	  AND ( (PRC.STATUS NOT IN (''FATURADO'',''CANCELADO'',''VENDA PERDIDA'') AND ' + @XI + N' = 1 ) OR (' + @XI + N' = 0 ) )
) XA
JOIN (
    SELECT PXD.ProcessoDNA, PXD2.Processo,
           MAX(HX.DTAREALIZACAO) AS DTAPROCESSO,
           MAX(CASE WHEN HX.RESULTADO IN (3232,3663) THEN HX.DtaRealizacao END) AS DTADNA
    FROM IV_HISTORICO HX
    JOIN IV_PROCDADO PXD  ON PXD.Processo = HX.Processo
    JOIN IV_PROCDADO PXD2 ON PXD2.ProcessoDNA = PXD.ProcessoDNA
    WHERE EXISTS (SELECT 1 FROM IV_HISTORICO WHERE RESULTADO IN (3232,3663) AND PROCESSO = HX.PROCESSO)
    GROUP BY PXD.ProcessoDNA, PXD2.Processo
) XP1 ON XP1.Processo = XA.PROCESSO_N
LEFT JOIN IV_HISTORICO XH2 ON XH2.Processo = XP1.Processo AND XH2.DtaRealizacao = XP1.DTADNA
LEFT JOIN IV_RESULTADO XR2 ON XR2.Resultado = XH2.Resultado
LEFT JOIN IV_ACAO     XA2 ON XA2.Acao = XH2.AcaoGeradora
WHERE 1=1
  AND NOT EXISTS (SELECT 1 FROM IV_Q$PEDIDO_KAM WHERE QUANTIDADE>1 AND PROCESSO = XA.PROCESSO_N AND PROCESSO = XA.PROCESSODNA)
  AND NOT EXISTS (SELECT 1 FROM IV_Q$PEDIDO_SAM WHERE QUANTIDADE>1 AND PROCESSO = XA.PROCESSO_N AND PROCESSO = XA.PROCESSODNA);
';

    IF @Debug = 1
        SELECT @sql AS SqlPreview, @DT1 AS DT1, @DT2 AS DT2, @OPT1_ListChave AS Carteiras, @LS2_CMD AS Empresa;

    EXEC sp_executesql
        @sql,
        N'@DT1 DATETIME2(0), @DT2 DATETIME2(0), @OPT1_ListChave NVARCHAR(MAX), @pLS2 NVARCHAR(MAX), @pLTA NVARCHAR(MAX), @XI NVARCHAR(MAX)',
        @DT1=@DT1, @DT2=@DT2, @OPT1_ListChave=@OPT1_ListChave, @pLS2=@LS2_CMD, @pLTA=@LTA, @XI=@XI;

-----------------------debug
--DECLARE @DebugSQL nvarchar(max) = @sql;

---- Datas em ISO 120/126 para clareza
--SET @DebugSQL = REPLACE(@DebugSQL, '@DT1', '''' + CONVERT(nvarchar(30), @DT1, 120) + '''');
--SET @DebugSQL = REPLACE(@DebugSQL, '@DT2', '''' + CONVERT(nvarchar(30), @DT2, 120) + '''');

---- Strings comuns (escape de aspas simples)
--DECLARE @OPT1_esc nvarchar(max) = REPLACE(@OPT1_ListChave, '''', '''''');
--DECLARE @pLS2_esc  nvarchar(max) = REPLACE(ISNULL(@LS2_CMD, N''), '''', '''''');
--DECLARE @pLTA_esc  nvarchar(max) = REPLACE(ISNULL(@LTA,     N''), '''', '''''');
--DECLARE @pLTB_esc  nvarchar(max) = REPLACE(ISNULL(@LTB,     N''), '''', '''''');

--SET @DebugSQL = REPLACE(@DebugSQL, '@OPT1_ListChave', '''' + @OPT1_esc + '''');
--SET @DebugSQL = REPLACE(@DebugSQL, '@pLS2',  '''' + @pLS2_esc + '''');
--SET @DebugSQL = REPLACE(@DebugSQL, '@pLTA',  '''' + @pLTA_esc + '''');

---- Caso específico: IN (@pLTB)  ->  IN ('A','B','C')
--DECLARE @pLTB_list nvarchar(max) = '''' + REPLACE(@pLTB_esc, ',', ''',''') + '''';
---- Trate as variantes com/sem NOT e espaços
--SET @DebugSQL = REPLACE(@DebugSQL, 'IN (@pLTB)',      'IN ('  + @pLTB_list + ')');
--SET @DebugSQL = REPLACE(@DebugSQL, 'NOT IN (@pLTB)',  'NOT IN ('  + @pLTB_list + ')');
---- Se sobrar @pLTB em outros lugares, deixa entre aspas
--SET @DebugSQL = REPLACE(@DebugSQL, '@pLTB', '''' + @pLTB_esc + '''');

---- Imprimir em blocos (PRINT limita ~4000 NVARCHAR)
--DECLARE @pos int = 1, @len int = LEN(@DebugSQL);
--WHILE @pos <= @len
--BEGIN
--  PRINT SUBSTRING(@DebugSQL, @pos, 4000);
--  SET @pos += 4000;
--END;

-----------------------debug final

    -- Cursor para inserir linha a linha
    DECLARE
        @EMPRESA NVARCHAR(120), @CEN NVARCHAR(60), @JD_QUOTE NVARCHAR(120),
        @TIPO_VENDA NVARCHAR(120), @TIPO_DE_EQUIPAMENTO NVARCHAR(120),
        @MARCA NVARCHAR(120), @MODELO NVARCHAR(200), @SEQPESSOA INT,
        @NOMERAZAO NVARCHAR(200), @CNPJCPF NVARCHAR(32),
        @LINHA_CREDITO NVARCHAR(120), @INST_FINANCEIRA NVARCHAR(120),
        @FINANC_CHASSI NVARCHAR(120), @ULT_RESULTADO NVARCHAR(400),
        @DTA_FATURAMENTO_D DATETIME, @NF_N NVARCHAR(60),
        @DTA_PED_D DATETIME, @DTA_PRENCH_FORM_D DATETIME,
        @VALOR_N DECIMAL(18,2), @DTA_ULT_ANDAMENTO_D DATETIME,
        @ULT_HISTORICO_L NVARCHAR(MAX), @PROCESSO_N INT, @CARTEIRA NVARCHAR(60),
        @CIDADE NVARCHAR(150), @DATA_PEDIDO_HIST_D DATETIME,
        @CAMPANHA NVARCHAR(150), @PROCESSODNA INT, @DTAPROVADO NVARCHAR(10);

    DECLARE cur CURSOR FAST_FORWARD FOR
        SELECT EMPRESA, CEN, JD_QUOTE, TIPO_VENDA, TIPO_DE_EQUIPAMENTO, MARCA, MODELO,
               SEQPESSOA, NOMERAZAO, CNPJCPF, LINHA_CREDITO, INST_FINANCEIRA, FINANC_CHASSI,
               ULT_RESULTADO, DTA_FATURAMENTO_D, NF_N, DTA_PED_D, DTA_PRENCH_FORM_D, VALOR_N,
               DTA_ULT_ANDAMENTO_D, ULT_HISTORICO_L, PROCESSO_N, CARTEIRA, CIDADE,
               DATA_PEDIDO_HIST_D, CAMPANHA, PROCESSODNA, DTAPROVADO
        FROM #Stage;

    OPEN cur;
    FETCH NEXT FROM cur INTO
        @EMPRESA, @CEN, @JD_QUOTE, @TIPO_VENDA, @TIPO_DE_EQUIPAMENTO, @MARCA, @MODELO,
        @SEQPESSOA, @NOMERAZAO, @CNPJCPF, @LINHA_CREDITO, @INST_FINANCEIRA, @FINANC_CHASSI,
        @ULT_RESULTADO, @DTA_FATURAMENTO_D, @NF_N, @DTA_PED_D, @DTA_PRENCH_FORM_D, @VALOR_N,
        @DTA_ULT_ANDAMENTO_D, @ULT_HISTORICO_L, @PROCESSO_N, @CARTEIRA, @CIDADE,
        @DATA_PEDIDO_HIST_D, @CAMPANHA, @PROCESSODNA, @DTAPROVADO;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        INSERT INTO dbo.IMP_REL_TBA101
        (
            CODUSUARIO, EMPRESA, CEN, JD_QUOTE, TIPO_VENDA, TIPO_DE_EQUIPAMENTO, MARCA, MODELO,
            SEQPESSOA, NOMERAZAO, CNPJCPF, LINHA_CREDITO, INST_FINANCEIRA, FINANC_CHASSI,
            ULT_RESULTADO, DTA_FATURAMENTO_D, NF_N, DTA_PED_D, DTA_PRENCH_FORM_D, VALOR_N,
            DTA_ULT_ANDAMENTO_D, ULT_HISTORICO_L, PROCESSO_N, CARTEIRA, CIDADE,
            DATA_PEDIDO_HIST_D, CAMPANHA, PROCESSODNA, DTAPROVADO
        )
        VALUES
        (
            @CODUSUARIO, @EMPRESA, @CEN, @JD_QUOTE, @TIPO_VENDA, @TIPO_DE_EQUIPAMENTO, @MARCA, @MODELO,
            @SEQPESSOA, @NOMERAZAO, @CNPJCPF, @LINHA_CREDITO, @INST_FINANCEIRA, @FINANC_CHASSI,
            @ULT_RESULTADO, @DTA_FATURAMENTO_D, @NF_N, @DTA_PED_D, @DTA_PRENCH_FORM_D, @VALOR_N,
            @DTA_ULT_ANDAMENTO_D, @ULT_HISTORICO_L, @PROCESSO_N, @CARTEIRA, @CIDADE,
            @DATA_PEDIDO_HIST_D, @CAMPANHA, @PROCESSODNA, @DTAPROVADO
        );

        FETCH NEXT FROM cur INTO
            @EMPRESA, @CEN, @JD_QUOTE, @TIPO_VENDA, @TIPO_DE_EQUIPAMENTO, @MARCA, @MODELO,
            @SEQPESSOA, @NOMERAZAO, @CNPJCPF, @LINHA_CREDITO, @INST_FINANCEIRA, @FINANC_CHASSI,
            @ULT_RESULTADO, @DTA_FATURAMENTO_D, @NF_N, @DTA_PED_D, @DTA_PRENCH_FORM_D, @VALOR_N,
            @DTA_ULT_ANDAMENTO_D, @ULT_HISTORICO_L, @PROCESSO_N, @CARTEIRA, @CIDADE,
            @DATA_PEDIDO_HIST_D, @CAMPANHA, @PROCESSODNA, @DTAPROVADO;
    END

    CLOSE cur; DEALLOCATE cur;
END
